// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Apollo.OpenApiClient.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Apollo.OpenApiClient.Emailer_campaigns.Item.Abort
{
    /// <summary>
    /// Builds and executes requests for operations under \emailer_campaigns\{sequenceId}\abort
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class AbortRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Apollo.OpenApiClient.Emailer_campaigns.Item.Abort.AbortRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public AbortRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/emailer_campaigns/{sequenceId}/abort", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Apollo.OpenApiClient.Emailer_campaigns.Item.Abort.AbortRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public AbortRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/emailer_campaigns/{sequenceId}/abort", rawUrl)
        {
        }
        /// <summary>
        /// ## Endpoint essentials**API key access:** `api/v1/emailer_campaigns/abort` or `Master API key`**OAuth scopes:** `emailer_campaigns_abort`**Credit usage:** `0 credits` — [Learn more about API pricing and credits](https://docs.apollo.io/docs/api-pricing).&lt;a href=&quot;https://knowledge.apollo.io/hc/en-us/articles/4409237165837-Sequences-Overview&quot; target=&quot;_blank&quot;&gt;Sequences&lt;/a&gt; are outreach campaigns that sales teams use to reach out to contacts over a planned period of time.&lt;br&gt;&lt;br&gt;Use the Deactivate a Sequence endpoint to stop an active sequence. Once deactivated, the sequence pauses all contacts and stops sending emails.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Apollo.OpenApiClient.Models.AbortSequence200Response"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Apollo.OpenApiClient.Emailer_campaigns.Item.Abort.AbortSequence200Response401Error">When receiving a 401 status code</exception>
        /// <exception cref="global::Soenneker.Apollo.OpenApiClient.Models.AbortSequence403Response">When receiving a 403 status code</exception>
        /// <exception cref="global::Soenneker.Apollo.OpenApiClient.Models.AbortSequence422Response">When receiving a 422 status code</exception>
        /// <exception cref="global::Soenneker.Apollo.OpenApiClient.Models.AbortSequence429Response">When receiving a 429 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Apollo.OpenApiClient.Models.AbortSequence200Response?> PostAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Apollo.OpenApiClient.Models.AbortSequence200Response> PostAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToPostRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "401", global::Soenneker.Apollo.OpenApiClient.Emailer_campaigns.Item.Abort.AbortSequence200Response401Error.CreateFromDiscriminatorValue },
                { "403", global::Soenneker.Apollo.OpenApiClient.Models.AbortSequence403Response.CreateFromDiscriminatorValue },
                { "422", global::Soenneker.Apollo.OpenApiClient.Models.AbortSequence422Response.CreateFromDiscriminatorValue },
                { "429", global::Soenneker.Apollo.OpenApiClient.Models.AbortSequence429Response.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.Apollo.OpenApiClient.Models.AbortSequence200Response>(requestInfo, global::Soenneker.Apollo.OpenApiClient.Models.AbortSequence200Response.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// ## Endpoint essentials**API key access:** `api/v1/emailer_campaigns/abort` or `Master API key`**OAuth scopes:** `emailer_campaigns_abort`**Credit usage:** `0 credits` — [Learn more about API pricing and credits](https://docs.apollo.io/docs/api-pricing).&lt;a href=&quot;https://knowledge.apollo.io/hc/en-us/articles/4409237165837-Sequences-Overview&quot; target=&quot;_blank&quot;&gt;Sequences&lt;/a&gt; are outreach campaigns that sales teams use to reach out to contacts over a planned period of time.&lt;br&gt;&lt;br&gt;Use the Deactivate a Sequence endpoint to stop an active sequence. Once deactivated, the sequence pauses all contacts and stops sending emails.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Apollo.OpenApiClient.Emailer_campaigns.Item.Abort.AbortRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Apollo.OpenApiClient.Emailer_campaigns.Item.Abort.AbortRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Apollo.OpenApiClient.Emailer_campaigns.Item.Abort.AbortRequestBuilder(rawUrl, RequestAdapter);
        }
    }
}
#pragma warning restore CS0618
