// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Apollo.OpenApiClient.Accounts.Bulk_create;
using Soenneker.Apollo.OpenApiClient.Accounts.Bulk_update;
using Soenneker.Apollo.OpenApiClient.Accounts.Item;
using Soenneker.Apollo.OpenApiClient.Accounts.Search;
using Soenneker.Apollo.OpenApiClient.Accounts.Update_owners;
using Soenneker.Apollo.OpenApiClient.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Apollo.OpenApiClient.Accounts
{
    /// <summary>
    /// Builds and executes requests for operations under \accounts
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class AccountsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The bulk_create property</summary>
        public global::Soenneker.Apollo.OpenApiClient.Accounts.Bulk_create.Bulk_createRequestBuilder Bulk_create
        {
            get => new global::Soenneker.Apollo.OpenApiClient.Accounts.Bulk_create.Bulk_createRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The bulk_update property</summary>
        public global::Soenneker.Apollo.OpenApiClient.Accounts.Bulk_update.Bulk_updateRequestBuilder Bulk_update
        {
            get => new global::Soenneker.Apollo.OpenApiClient.Accounts.Bulk_update.Bulk_updateRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The search property</summary>
        public global::Soenneker.Apollo.OpenApiClient.Accounts.Search.SearchRequestBuilder Search
        {
            get => new global::Soenneker.Apollo.OpenApiClient.Accounts.Search.SearchRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The update_owners property</summary>
        public global::Soenneker.Apollo.OpenApiClient.Accounts.Update_owners.Update_ownersRequestBuilder Update_owners
        {
            get => new global::Soenneker.Apollo.OpenApiClient.Accounts.Update_owners.Update_ownersRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>Gets an item from the Soenneker.Apollo.OpenApiClient.accounts.item collection</summary>
        /// <param name="position">The Apollo ID for the account that you want to update. &lt;br&gt;&lt;br&gt;To find account IDs, call the &lt;a href=&quot;https://docs.apollo.io/reference/search-for-accounts&quot; target=&quot;_blank&quot;&gt;search for accounts endpoint&lt;/a&gt; and identify the `id` value for the contact. &lt;br&gt;&lt;br&gt;Example: `66e9abf95ac32901b20d1a0d`</param>
        /// <returns>A <see cref="global::Soenneker.Apollo.OpenApiClient.Accounts.Item.WithAccountItemRequestBuilder"/></returns>
        public global::Soenneker.Apollo.OpenApiClient.Accounts.Item.WithAccountItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("accountId", position);
                return new global::Soenneker.Apollo.OpenApiClient.Accounts.Item.WithAccountItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Apollo.OpenApiClient.Accounts.AccountsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public AccountsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/accounts", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Apollo.OpenApiClient.Accounts.AccountsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public AccountsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/accounts", rawUrl)
        {
        }
        /// <summary>
        /// ## Endpoint essentials**API key access:** `api/v1/accounts/create` or `Master API key`**OAuth scopes:** `account_write`**Credit usage:** `0 credits` — [Learn more about API pricing and credits](https://docs.apollo.io/docs/api-pricing).An &lt;a href=&quot;https://knowledge.apollo.io/hc/en-us/articles/5995865049229-View-and-Edit-Accounts&quot; target=&quot;_blank&quot;&gt;account&lt;/a&gt; is a company saved in Apollo.&lt;br&gt;&lt;br&gt;Use the create an account endpoint to add a new account to your team&apos;s Apollo account.&lt;br&gt;&lt;br&gt;Apollo doesn&apos;t apply deduplication processes when you create a new account via the API. If your entry has the same name, domain, or other details as an existing account, Apollo creates a new account instead of updating the existing account. To update an existing account, use the &lt;a href=&quot;https://docs.apollo.io/reference/update-an-account&quot;&gt;update an account endpoint&lt;/a&gt; instead.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Apollo.OpenApiClient.Models.CreateAnAccount200Response"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Apollo.OpenApiClient.Accounts.CreateAnAccount200Response401Error">When receiving a 401 status code</exception>
        /// <exception cref="global::Soenneker.Apollo.OpenApiClient.Models.CreateAnAccount403Response">When receiving a 403 status code</exception>
        /// <exception cref="global::Soenneker.Apollo.OpenApiClient.Models.CreateAnAccount422Response">When receiving a 422 status code</exception>
        /// <exception cref="global::Soenneker.Apollo.OpenApiClient.Models.CreateAnAccount429Response">When receiving a 429 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Apollo.OpenApiClient.Models.CreateAnAccount200Response?> PostAsync(global::Soenneker.Apollo.OpenApiClient.Models.CreateAnAccountRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Apollo.OpenApiClient.Models.CreateAnAccount200Response> PostAsync(global::Soenneker.Apollo.OpenApiClient.Models.CreateAnAccountRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "401", global::Soenneker.Apollo.OpenApiClient.Accounts.CreateAnAccount200Response401Error.CreateFromDiscriminatorValue },
                { "403", global::Soenneker.Apollo.OpenApiClient.Models.CreateAnAccount403Response.CreateFromDiscriminatorValue },
                { "422", global::Soenneker.Apollo.OpenApiClient.Models.CreateAnAccount422Response.CreateFromDiscriminatorValue },
                { "429", global::Soenneker.Apollo.OpenApiClient.Models.CreateAnAccount429Response.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.Apollo.OpenApiClient.Models.CreateAnAccount200Response>(requestInfo, global::Soenneker.Apollo.OpenApiClient.Models.CreateAnAccount200Response.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// ## Endpoint essentials**API key access:** `api/v1/accounts/create` or `Master API key`**OAuth scopes:** `account_write`**Credit usage:** `0 credits` — [Learn more about API pricing and credits](https://docs.apollo.io/docs/api-pricing).An &lt;a href=&quot;https://knowledge.apollo.io/hc/en-us/articles/5995865049229-View-and-Edit-Accounts&quot; target=&quot;_blank&quot;&gt;account&lt;/a&gt; is a company saved in Apollo.&lt;br&gt;&lt;br&gt;Use the create an account endpoint to add a new account to your team&apos;s Apollo account.&lt;br&gt;&lt;br&gt;Apollo doesn&apos;t apply deduplication processes when you create a new account via the API. If your entry has the same name, domain, or other details as an existing account, Apollo creates a new account instead of updating the existing account. To update an existing account, use the &lt;a href=&quot;https://docs.apollo.io/reference/update-an-account&quot;&gt;update an account endpoint&lt;/a&gt; instead.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(global::Soenneker.Apollo.OpenApiClient.Models.CreateAnAccountRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(global::Soenneker.Apollo.OpenApiClient.Models.CreateAnAccountRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Apollo.OpenApiClient.Accounts.AccountsRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Apollo.OpenApiClient.Accounts.AccountsRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Apollo.OpenApiClient.Accounts.AccountsRequestBuilder(rawUrl, RequestAdapter);
        }
    }
}
#pragma warning restore CS0618
