// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Apollo.OpenApiClient.Models;
using Soenneker.Apollo.OpenApiClient.Sequences.Item;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Apollo.OpenApiClient.Sequences
{
    /// <summary>
    /// Builds and executes requests for operations under \sequences
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class SequencesRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Soenneker.Apollo.OpenApiClient.sequences.item collection</summary>
        /// <param name="position">The Apollo ID for the sequence that you want to update. &lt;br&gt;&lt;br&gt;To find sequence IDs, call the &lt;a href=&quot;https://docs.apollo.io/reference/search-for-sequences&quot; target=&quot;_blank&quot;&gt;Search for Sequences endpoint&lt;/a&gt; and identify the `id` value for the sequence. &lt;br&gt;&lt;br&gt;Example: `66e34b81740c50074e3d1bd4`</param>
        /// <returns>A <see cref="global::Soenneker.Apollo.OpenApiClient.Sequences.Item.SequencesItemRequestBuilder"/></returns>
        public global::Soenneker.Apollo.OpenApiClient.Sequences.Item.SequencesItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("id", position);
                return new global::Soenneker.Apollo.OpenApiClient.Sequences.Item.SequencesItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Apollo.OpenApiClient.Sequences.SequencesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public SequencesRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/sequences", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Apollo.OpenApiClient.Sequences.SequencesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public SequencesRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/sequences", rawUrl)
        {
        }
        /// <summary>
        /// ## Endpoint essentials**API key access:** `api/v1/sequences/create` or `Master API key`**OAuth scopes:** `emailer_campaigns_create`**Credit usage:** `0 credits` — [Learn more about API pricing and credits](https://docs.apollo.io/docs/api-pricing).&lt;a href=&quot;https://knowledge.apollo.io/hc/en-us/articles/4409237165837-Sequences-Overview&quot; target=&quot;_blank&quot;&gt;Sequences&lt;/a&gt; are outreach campaigns that sales teams use to reach out to contacts over a planned period of time.&lt;br&gt;&lt;br&gt;Use the Create a Sequence endpoint to create a new sequence in your team&apos;s Apollo account, including its steps and email templates.&lt;br&gt;&lt;br&gt;To create a sequence with steps, add the `emailer_steps` array to the request body. Each email step (`auto_email`, `manual_email`) can include one or more `emailer_touches` (email variants); adding more than one touch to a step creates an A/B test, which requires a plan with A/B testing access.&lt;br&gt;&lt;br&gt;To activate the sequence immediately after creation, set `active` to `true`. Email touches only send if their `status` is `approved`, and a touch can only be approved if its template has a non-empty body.### Who owns a sequence created via APIThe new sequence is owned by the user your request acts as, returned as `object_owner_id` (and its alias, `user_id`). With an API key that user isn&apos;t the teammate who created the key, so expect `object_owner_id` to differ from that teammate&apos;s profile — see [Authentication](https://docs.apollo.io/reference/authentication) for how the acting user is resolved and how to confirm it.This endpoint ignores `user_id` in the request body, so you can&apos;t choose the owner at creation time. To reassign ownership afterward, call [Update a Sequence](https://docs.apollo.io/reference/update-sequence) with a `user_id`.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Apollo.OpenApiClient.Models.CreateSequence200Response"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Apollo.OpenApiClient.Sequences.CreateSequence200Response401Error">When receiving a 401 status code</exception>
        /// <exception cref="global::Soenneker.Apollo.OpenApiClient.Models.CreateSequence403Response">When receiving a 403 status code</exception>
        /// <exception cref="global::Soenneker.Apollo.OpenApiClient.Models.CreateSequence422Response">When receiving a 422 status code</exception>
        /// <exception cref="global::Soenneker.Apollo.OpenApiClient.Sequences.CreateSequence200Response429Error">When receiving a 429 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Apollo.OpenApiClient.Models.CreateSequence200Response?> PostAsync(global::Soenneker.Apollo.OpenApiClient.Models.CreateSequenceRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Apollo.OpenApiClient.Models.CreateSequence200Response> PostAsync(global::Soenneker.Apollo.OpenApiClient.Models.CreateSequenceRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "401", global::Soenneker.Apollo.OpenApiClient.Sequences.CreateSequence200Response401Error.CreateFromDiscriminatorValue },
                { "403", global::Soenneker.Apollo.OpenApiClient.Models.CreateSequence403Response.CreateFromDiscriminatorValue },
                { "422", global::Soenneker.Apollo.OpenApiClient.Models.CreateSequence422Response.CreateFromDiscriminatorValue },
                { "429", global::Soenneker.Apollo.OpenApiClient.Sequences.CreateSequence200Response429Error.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.Apollo.OpenApiClient.Models.CreateSequence200Response>(requestInfo, global::Soenneker.Apollo.OpenApiClient.Models.CreateSequence200Response.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// ## Endpoint essentials**API key access:** `api/v1/sequences/create` or `Master API key`**OAuth scopes:** `emailer_campaigns_create`**Credit usage:** `0 credits` — [Learn more about API pricing and credits](https://docs.apollo.io/docs/api-pricing).&lt;a href=&quot;https://knowledge.apollo.io/hc/en-us/articles/4409237165837-Sequences-Overview&quot; target=&quot;_blank&quot;&gt;Sequences&lt;/a&gt; are outreach campaigns that sales teams use to reach out to contacts over a planned period of time.&lt;br&gt;&lt;br&gt;Use the Create a Sequence endpoint to create a new sequence in your team&apos;s Apollo account, including its steps and email templates.&lt;br&gt;&lt;br&gt;To create a sequence with steps, add the `emailer_steps` array to the request body. Each email step (`auto_email`, `manual_email`) can include one or more `emailer_touches` (email variants); adding more than one touch to a step creates an A/B test, which requires a plan with A/B testing access.&lt;br&gt;&lt;br&gt;To activate the sequence immediately after creation, set `active` to `true`. Email touches only send if their `status` is `approved`, and a touch can only be approved if its template has a non-empty body.### Who owns a sequence created via APIThe new sequence is owned by the user your request acts as, returned as `object_owner_id` (and its alias, `user_id`). With an API key that user isn&apos;t the teammate who created the key, so expect `object_owner_id` to differ from that teammate&apos;s profile — see [Authentication](https://docs.apollo.io/reference/authentication) for how the acting user is resolved and how to confirm it.This endpoint ignores `user_id` in the request body, so you can&apos;t choose the owner at creation time. To reassign ownership afterward, call [Update a Sequence](https://docs.apollo.io/reference/update-sequence) with a `user_id`.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(global::Soenneker.Apollo.OpenApiClient.Models.CreateSequenceRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(global::Soenneker.Apollo.OpenApiClient.Models.CreateSequenceRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Apollo.OpenApiClient.Sequences.SequencesRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Apollo.OpenApiClient.Sequences.SequencesRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Apollo.OpenApiClient.Sequences.SequencesRequestBuilder(rawUrl, RequestAdapter);
        }
    }
}
#pragma warning restore CS0618
