// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Apollo.OpenApiClient.Models;
using Soenneker.Apollo.OpenApiClient.Tasks.Item.Complete;
using Soenneker.Apollo.OpenApiClient.Tasks.Item.Skip;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Apollo.OpenApiClient.Tasks.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \tasks\{id}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class TasksItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The complete property</summary>
        public global::Soenneker.Apollo.OpenApiClient.Tasks.Item.Complete.CompleteRequestBuilder Complete
        {
            get => new global::Soenneker.Apollo.OpenApiClient.Tasks.Item.Complete.CompleteRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The skip property</summary>
        public global::Soenneker.Apollo.OpenApiClient.Tasks.Item.Skip.SkipRequestBuilder Skip
        {
            get => new global::Soenneker.Apollo.OpenApiClient.Tasks.Item.Skip.SkipRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Apollo.OpenApiClient.Tasks.Item.TasksItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public TasksItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/tasks/{id}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Apollo.OpenApiClient.Tasks.Item.TasksItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public TasksItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/tasks/{id}", rawUrl)
        {
        }
        /// <summary>
        /// ## Endpoint essentials**API key access:** `api/v1/tasks/show` or `Master API key`**OAuth scopes:** `tasks_list`**Credit usage:** `0 credits` — [Learn more about API pricing and credits](https://docs.apollo.io/docs/api-pricing).&lt;a href=&quot;https://knowledge.apollo.io/hc/en-us/articles/28705458602125-Tasks-Overview&quot; target=&quot;_blank&quot;&gt;Tasks&lt;/a&gt; let you track, prioritize, and help you complete actions required for your outbound sales motion.&lt;br&gt;&lt;br&gt;Use the get a task endpoint to retrieve the full details for a single task that belongs to your team&apos;s Apollo account.&lt;br&gt;&lt;br&gt;The response includes the task&apos;s associated &lt;a href=&quot;https://docs.apollo.io/reference/view-an-account&quot;&gt;account&lt;/a&gt; and &lt;a href=&quot;https://docs.apollo.io/reference/view-a-contact&quot;&gt;contact&lt;/a&gt; when the task has one attached. Depending on the task&apos;s `type` and how it was created, the response can also include additional fields, such as `phone_call` for call tasks, `emailer_message` for email tasks, or a LinkedIn message template for LinkedIn-step tasks.&lt;br&gt;&lt;br&gt;To find task IDs, use the &lt;a href=&quot;https://docs.apollo.io/reference/search-tasks&quot;&gt;search for tasks endpoint&lt;/a&gt; and identify the `id` value for the task you want to view.&lt;br&gt;&lt;br&gt;To create a task, use the &lt;a href=&quot;https://docs.apollo.io/reference/create-a-task&quot;&gt;create a task endpoint&lt;/a&gt; instead.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Apollo.OpenApiClient.Models.GetATask200Response"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Apollo.OpenApiClient.Tasks.Item.GetATask200Response401Error">When receiving a 401 status code</exception>
        /// <exception cref="global::Soenneker.Apollo.OpenApiClient.Models.GetATask403Response">When receiving a 403 status code</exception>
        /// <exception cref="global::Soenneker.Apollo.OpenApiClient.Models.GetATask422Response">When receiving a 422 status code</exception>
        /// <exception cref="global::Soenneker.Apollo.OpenApiClient.Models.GetATask429Response">When receiving a 429 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Apollo.OpenApiClient.Models.GetATask200Response?> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Apollo.OpenApiClient.Models.GetATask200Response> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "401", global::Soenneker.Apollo.OpenApiClient.Tasks.Item.GetATask200Response401Error.CreateFromDiscriminatorValue },
                { "403", global::Soenneker.Apollo.OpenApiClient.Models.GetATask403Response.CreateFromDiscriminatorValue },
                { "422", global::Soenneker.Apollo.OpenApiClient.Models.GetATask422Response.CreateFromDiscriminatorValue },
                { "429", global::Soenneker.Apollo.OpenApiClient.Models.GetATask429Response.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.Apollo.OpenApiClient.Models.GetATask200Response>(requestInfo, global::Soenneker.Apollo.OpenApiClient.Models.GetATask200Response.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// ## Endpoint essentials**API key access:** `api/v1/tasks/update` or `Master API key`**OAuth scopes:** `tasks_create`**Credit usage:** `0 credits` — [Learn more about API pricing and credits](https://docs.apollo.io/docs/api-pricing).&lt;a href=&quot;https://knowledge.apollo.io/hc/en-us/articles/28705458602125-Tasks-Overview&quot; target=&quot;_blank&quot;&gt;Tasks&lt;/a&gt; let you track, prioritize, and help you complete actions required for your outbound sales motion.&lt;br&gt;&lt;br&gt;Use the update a task endpoint to change the details of an existing task that belongs to your team&apos;s Apollo account.&lt;br&gt;&lt;br&gt;To find task IDs, use the &lt;a href=&quot;https://docs.apollo.io/reference/search-tasks&quot;&gt;search for tasks endpoint&lt;/a&gt; and identify the `id` value for the task you want to update.&lt;br&gt;&lt;br&gt;The fields you can update depend on the task&apos;s current `status`. For a task with a `scheduled` status, you can update any of the parameters listed below. For a task that&apos;s already `completed` or `skipped`, you can only update `note`, `priority`, `priority_cd`, and `contact_id`.&lt;br&gt;&lt;br&gt;To mark a task as done, use the &lt;a href=&quot;https://docs.apollo.io/reference/complete-a-task&quot;&gt;complete a task&lt;/a&gt; or &lt;a href=&quot;https://docs.apollo.io/reference/skip-a-task&quot;&gt;skip a task&lt;/a&gt; endpoints instead of setting `status` here.&gt; ⚠️ Omitting `priority` or `creator_id` resets them&gt;&gt; If the task you&apos;re updating has a `scheduled` status, and your request doesn&apos;t include a `priority` or `creator_id` parameter, Apollo resets `priority` to `medium` and `creator_id` to the user associated with your API key — even if you didn&apos;t intend to change those fields. To avoid this, always include the task&apos;s current `priority` and `creator_id` in every update request, even when you&apos;re only changing an unrelated field like `note`.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Apollo.OpenApiClient.Models.UpdateATask200Response"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Apollo.OpenApiClient.Tasks.Item.UpdateATask200Response401Error">When receiving a 401 status code</exception>
        /// <exception cref="global::Soenneker.Apollo.OpenApiClient.Models.UpdateATask403Response">When receiving a 403 status code</exception>
        /// <exception cref="global::Soenneker.Apollo.OpenApiClient.Models.UpdateATask422Response">When receiving a 422 status code</exception>
        /// <exception cref="global::Soenneker.Apollo.OpenApiClient.Models.UpdateATask429Response">When receiving a 429 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Apollo.OpenApiClient.Models.UpdateATask200Response?> PatchAsync(global::Soenneker.Apollo.OpenApiClient.Models.UpdateATaskRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Apollo.OpenApiClient.Models.UpdateATask200Response> PatchAsync(global::Soenneker.Apollo.OpenApiClient.Models.UpdateATaskRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPatchRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "401", global::Soenneker.Apollo.OpenApiClient.Tasks.Item.UpdateATask200Response401Error.CreateFromDiscriminatorValue },
                { "403", global::Soenneker.Apollo.OpenApiClient.Models.UpdateATask403Response.CreateFromDiscriminatorValue },
                { "422", global::Soenneker.Apollo.OpenApiClient.Models.UpdateATask422Response.CreateFromDiscriminatorValue },
                { "429", global::Soenneker.Apollo.OpenApiClient.Models.UpdateATask429Response.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.Apollo.OpenApiClient.Models.UpdateATask200Response>(requestInfo, global::Soenneker.Apollo.OpenApiClient.Models.UpdateATask200Response.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// ## Endpoint essentials**API key access:** `api/v1/tasks/show` or `Master API key`**OAuth scopes:** `tasks_list`**Credit usage:** `0 credits` — [Learn more about API pricing and credits](https://docs.apollo.io/docs/api-pricing).&lt;a href=&quot;https://knowledge.apollo.io/hc/en-us/articles/28705458602125-Tasks-Overview&quot; target=&quot;_blank&quot;&gt;Tasks&lt;/a&gt; let you track, prioritize, and help you complete actions required for your outbound sales motion.&lt;br&gt;&lt;br&gt;Use the get a task endpoint to retrieve the full details for a single task that belongs to your team&apos;s Apollo account.&lt;br&gt;&lt;br&gt;The response includes the task&apos;s associated &lt;a href=&quot;https://docs.apollo.io/reference/view-an-account&quot;&gt;account&lt;/a&gt; and &lt;a href=&quot;https://docs.apollo.io/reference/view-a-contact&quot;&gt;contact&lt;/a&gt; when the task has one attached. Depending on the task&apos;s `type` and how it was created, the response can also include additional fields, such as `phone_call` for call tasks, `emailer_message` for email tasks, or a LinkedIn message template for LinkedIn-step tasks.&lt;br&gt;&lt;br&gt;To find task IDs, use the &lt;a href=&quot;https://docs.apollo.io/reference/search-tasks&quot;&gt;search for tasks endpoint&lt;/a&gt; and identify the `id` value for the task you want to view.&lt;br&gt;&lt;br&gt;To create a task, use the &lt;a href=&quot;https://docs.apollo.io/reference/create-a-task&quot;&gt;create a task endpoint&lt;/a&gt; instead.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// ## Endpoint essentials**API key access:** `api/v1/tasks/update` or `Master API key`**OAuth scopes:** `tasks_create`**Credit usage:** `0 credits` — [Learn more about API pricing and credits](https://docs.apollo.io/docs/api-pricing).&lt;a href=&quot;https://knowledge.apollo.io/hc/en-us/articles/28705458602125-Tasks-Overview&quot; target=&quot;_blank&quot;&gt;Tasks&lt;/a&gt; let you track, prioritize, and help you complete actions required for your outbound sales motion.&lt;br&gt;&lt;br&gt;Use the update a task endpoint to change the details of an existing task that belongs to your team&apos;s Apollo account.&lt;br&gt;&lt;br&gt;To find task IDs, use the &lt;a href=&quot;https://docs.apollo.io/reference/search-tasks&quot;&gt;search for tasks endpoint&lt;/a&gt; and identify the `id` value for the task you want to update.&lt;br&gt;&lt;br&gt;The fields you can update depend on the task&apos;s current `status`. For a task with a `scheduled` status, you can update any of the parameters listed below. For a task that&apos;s already `completed` or `skipped`, you can only update `note`, `priority`, `priority_cd`, and `contact_id`.&lt;br&gt;&lt;br&gt;To mark a task as done, use the &lt;a href=&quot;https://docs.apollo.io/reference/complete-a-task&quot;&gt;complete a task&lt;/a&gt; or &lt;a href=&quot;https://docs.apollo.io/reference/skip-a-task&quot;&gt;skip a task&lt;/a&gt; endpoints instead of setting `status` here.&gt; ⚠️ Omitting `priority` or `creator_id` resets them&gt;&gt; If the task you&apos;re updating has a `scheduled` status, and your request doesn&apos;t include a `priority` or `creator_id` parameter, Apollo resets `priority` to `medium` and `creator_id` to the user associated with your API key — even if you didn&apos;t intend to change those fields. To avoid this, always include the task&apos;s current `priority` and `creator_id` in every update request, even when you&apos;re only changing an unrelated field like `note`.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPatchRequestInformation(global::Soenneker.Apollo.OpenApiClient.Models.UpdateATaskRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPatchRequestInformation(global::Soenneker.Apollo.OpenApiClient.Models.UpdateATaskRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.PATCH, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Apollo.OpenApiClient.Tasks.Item.TasksItemRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Apollo.OpenApiClient.Tasks.Item.TasksItemRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Apollo.OpenApiClient.Tasks.Item.TasksItemRequestBuilder(rawUrl, RequestAdapter);
        }
    }
}
#pragma warning restore CS0618
