// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Apollo.OpenApiClient.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Apollo.OpenApiClient.Accounts.Bulk_create
{
    /// <summary>
    /// Builds and executes requests for operations under \accounts\bulk_create
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class Bulk_createRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Apollo.OpenApiClient.Accounts.Bulk_create.Bulk_createRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public Bulk_createRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/accounts/bulk_create", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Apollo.OpenApiClient.Accounts.Bulk_create.Bulk_createRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public Bulk_createRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/accounts/bulk_create", rawUrl)
        {
        }
        /// <summary>
        /// ## Endpoint essentials**API key access:** `api/v1/accounts/bulk_create` or `Master API key`**OAuth scopes:** `account_bulk_create`**Credit usage:** `0 credits` — [Learn more about API pricing and credits](https://docs.apollo.io/docs/api-pricing).An &lt;a href=&quot;https://knowledge.apollo.io/hc/en-us/articles/5995865049229-View-and-Edit-Accounts&quot; target=&quot;_blank&quot;&gt;account&lt;/a&gt; is a company saved in Apollo.&lt;br&gt;&lt;br&gt;Use the bulk create accounts endpoint to create up to one hundred accounts in a single API request. This endpoint supports intelligent deduplication and returns separate arrays for newly created and existing accounts. &lt;br&gt;&lt;br&gt;**Important**: This endpoint creates new accounts but doesn&apos;t update existing ones. Existing accounts that match the criteria are returned in the &lt;code&gt;existing_accounts&lt;/code&gt; array without modification. &lt;br&gt;&lt;br&gt;To update existing accounts, use the &lt;a href=&quot;https://docs.apollo.io/reference/bulk-update-accounts&quot;&gt;Bulk Update Accounts endpoint&lt;/a&gt;.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Apollo.OpenApiClient.Models.BulkCreateAccounts200Response"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Apollo.OpenApiClient.Accounts.Bulk_create.BulkCreateAccounts200Response401Error">When receiving a 401 status code</exception>
        /// <exception cref="global::Soenneker.Apollo.OpenApiClient.Models.BulkCreateAccounts422Response">When receiving a 422 status code</exception>
        /// <exception cref="global::Soenneker.Apollo.OpenApiClient.Models.BulkCreateAccounts429Response">When receiving a 429 status code</exception>
        /// <exception cref="global::Soenneker.Apollo.OpenApiClient.Models.BulkCreateAccounts500Response">When receiving a 500 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Apollo.OpenApiClient.Models.BulkCreateAccounts200Response?> PostAsync(global::Soenneker.Apollo.OpenApiClient.Models.BulkCreateAccountsRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Apollo.OpenApiClient.Models.BulkCreateAccounts200Response> PostAsync(global::Soenneker.Apollo.OpenApiClient.Models.BulkCreateAccountsRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "401", global::Soenneker.Apollo.OpenApiClient.Accounts.Bulk_create.BulkCreateAccounts200Response401Error.CreateFromDiscriminatorValue },
                { "422", global::Soenneker.Apollo.OpenApiClient.Models.BulkCreateAccounts422Response.CreateFromDiscriminatorValue },
                { "429", global::Soenneker.Apollo.OpenApiClient.Models.BulkCreateAccounts429Response.CreateFromDiscriminatorValue },
                { "500", global::Soenneker.Apollo.OpenApiClient.Models.BulkCreateAccounts500Response.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.Apollo.OpenApiClient.Models.BulkCreateAccounts200Response>(requestInfo, global::Soenneker.Apollo.OpenApiClient.Models.BulkCreateAccounts200Response.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// ## Endpoint essentials**API key access:** `api/v1/accounts/bulk_create` or `Master API key`**OAuth scopes:** `account_bulk_create`**Credit usage:** `0 credits` — [Learn more about API pricing and credits](https://docs.apollo.io/docs/api-pricing).An &lt;a href=&quot;https://knowledge.apollo.io/hc/en-us/articles/5995865049229-View-and-Edit-Accounts&quot; target=&quot;_blank&quot;&gt;account&lt;/a&gt; is a company saved in Apollo.&lt;br&gt;&lt;br&gt;Use the bulk create accounts endpoint to create up to one hundred accounts in a single API request. This endpoint supports intelligent deduplication and returns separate arrays for newly created and existing accounts. &lt;br&gt;&lt;br&gt;**Important**: This endpoint creates new accounts but doesn&apos;t update existing ones. Existing accounts that match the criteria are returned in the &lt;code&gt;existing_accounts&lt;/code&gt; array without modification. &lt;br&gt;&lt;br&gt;To update existing accounts, use the &lt;a href=&quot;https://docs.apollo.io/reference/bulk-update-accounts&quot;&gt;Bulk Update Accounts endpoint&lt;/a&gt;.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(global::Soenneker.Apollo.OpenApiClient.Models.BulkCreateAccountsRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(global::Soenneker.Apollo.OpenApiClient.Models.BulkCreateAccountsRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Apollo.OpenApiClient.Accounts.Bulk_create.Bulk_createRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Apollo.OpenApiClient.Accounts.Bulk_create.Bulk_createRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Apollo.OpenApiClient.Accounts.Bulk_create.Bulk_createRequestBuilder(rawUrl, RequestAdapter);
        }
    }
}
#pragma warning restore CS0618
