// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Apollo.OpenApiClient.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Apollo.OpenApiClient.Accounts.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \accounts\{accountId}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithAccountItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Apollo.OpenApiClient.Accounts.Item.WithAccountItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithAccountItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/accounts/{accountId}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Apollo.OpenApiClient.Accounts.Item.WithAccountItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithAccountItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/accounts/{accountId}", rawUrl)
        {
        }
        /// <summary>
        /// ## Endpoint essentials**API key access:** `api/v1/accounts/show` or `Master API key`**OAuth scopes:** `account_read`**Credit usage:** `0 credits` — [Learn more about API pricing and credits](https://docs.apollo.io/docs/api-pricing).An &lt;a href=&quot;https://knowledge.apollo.io/hc/en-us/articles/5995865049229-View-and-Edit-Accounts&quot; target=&quot;_blank&quot;&gt;account&lt;/a&gt; is a company saved in Apollo.&lt;br&gt;&lt;br&gt;Use the view an account endpoint to retrieve details for an existing account.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Apollo.OpenApiClient.Accounts.Item.WithAccountGetResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Apollo.OpenApiClient.Accounts.Item.WithAccount401Error">When receiving a 401 status code</exception>
        /// <exception cref="global::Soenneker.Apollo.OpenApiClient.Accounts.Item.WithAccount403Error">When receiving a 403 status code</exception>
        /// <exception cref="global::Soenneker.Apollo.OpenApiClient.Accounts.Item.WithAccount422Error">When receiving a 422 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Apollo.OpenApiClient.Accounts.Item.WithAccountGetResponse?> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Apollo.OpenApiClient.Accounts.Item.WithAccountGetResponse> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "401", global::Soenneker.Apollo.OpenApiClient.Accounts.Item.WithAccount401Error.CreateFromDiscriminatorValue },
                { "403", global::Soenneker.Apollo.OpenApiClient.Accounts.Item.WithAccount403Error.CreateFromDiscriminatorValue },
                { "422", global::Soenneker.Apollo.OpenApiClient.Accounts.Item.WithAccount422Error.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.Apollo.OpenApiClient.Accounts.Item.WithAccountGetResponse>(requestInfo, global::Soenneker.Apollo.OpenApiClient.Accounts.Item.WithAccountGetResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// ## Endpoint essentials**API key access:** `api/v1/accounts/update` or `Master API key`**OAuth scopes:** `account_update`**Credit usage:** `0 credits` — [Learn more about API pricing and credits](https://docs.apollo.io/docs/api-pricing). An &lt;a href=&quot;https://knowledge.apollo.io/hc/en-us/articles/5995865049229-View-and-Edit-Accounts&quot; target=&quot;_blank&quot;&gt;account&lt;/a&gt; is a company saved in Apollo.&lt;br&gt;&lt;br&gt;Use the update an account endpoint to update existing accounts in your team&apos;s Apollo account.&lt;br&gt;&lt;br&gt;To create a new account, use the &lt;a href=&quot;https://docs.apollo.io/reference/create-an-account&quot;&gt;create an account endpoint&lt;/a&gt; instead. To update the account stage for multiple accounts, use the &lt;a href=&quot;https://docs.apollo.io/reference/bulk-update-accounts&quot;&gt;bulk update accounts endpoint&lt;/a&gt;.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Apollo.OpenApiClient.Models.UpdateAnAccount200Response"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Apollo.OpenApiClient.Accounts.Item.UpdateAnAccount200Response401Error">When receiving a 401 status code</exception>
        /// <exception cref="global::Soenneker.Apollo.OpenApiClient.Models.UpdateAnAccount403Response">When receiving a 403 status code</exception>
        /// <exception cref="global::Soenneker.Apollo.OpenApiClient.Models.UpdateAnAccount429Response">When receiving a 429 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Apollo.OpenApiClient.Models.UpdateAnAccount200Response?> PatchAsync(global::Soenneker.Apollo.OpenApiClient.Models.UpdateAnAccountRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Apollo.OpenApiClient.Models.UpdateAnAccount200Response> PatchAsync(global::Soenneker.Apollo.OpenApiClient.Models.UpdateAnAccountRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPatchRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "401", global::Soenneker.Apollo.OpenApiClient.Accounts.Item.UpdateAnAccount200Response401Error.CreateFromDiscriminatorValue },
                { "403", global::Soenneker.Apollo.OpenApiClient.Models.UpdateAnAccount403Response.CreateFromDiscriminatorValue },
                { "429", global::Soenneker.Apollo.OpenApiClient.Models.UpdateAnAccount429Response.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.Apollo.OpenApiClient.Models.UpdateAnAccount200Response>(requestInfo, global::Soenneker.Apollo.OpenApiClient.Models.UpdateAnAccount200Response.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// ## Endpoint essentials**API key access:** `api/v1/accounts/show` or `Master API key`**OAuth scopes:** `account_read`**Credit usage:** `0 credits` — [Learn more about API pricing and credits](https://docs.apollo.io/docs/api-pricing).An &lt;a href=&quot;https://knowledge.apollo.io/hc/en-us/articles/5995865049229-View-and-Edit-Accounts&quot; target=&quot;_blank&quot;&gt;account&lt;/a&gt; is a company saved in Apollo.&lt;br&gt;&lt;br&gt;Use the view an account endpoint to retrieve details for an existing account.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// ## Endpoint essentials**API key access:** `api/v1/accounts/update` or `Master API key`**OAuth scopes:** `account_update`**Credit usage:** `0 credits` — [Learn more about API pricing and credits](https://docs.apollo.io/docs/api-pricing). An &lt;a href=&quot;https://knowledge.apollo.io/hc/en-us/articles/5995865049229-View-and-Edit-Accounts&quot; target=&quot;_blank&quot;&gt;account&lt;/a&gt; is a company saved in Apollo.&lt;br&gt;&lt;br&gt;Use the update an account endpoint to update existing accounts in your team&apos;s Apollo account.&lt;br&gt;&lt;br&gt;To create a new account, use the &lt;a href=&quot;https://docs.apollo.io/reference/create-an-account&quot;&gt;create an account endpoint&lt;/a&gt; instead. To update the account stage for multiple accounts, use the &lt;a href=&quot;https://docs.apollo.io/reference/bulk-update-accounts&quot;&gt;bulk update accounts endpoint&lt;/a&gt;.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPatchRequestInformation(global::Soenneker.Apollo.OpenApiClient.Models.UpdateAnAccountRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPatchRequestInformation(global::Soenneker.Apollo.OpenApiClient.Models.UpdateAnAccountRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.PATCH, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Apollo.OpenApiClient.Accounts.Item.WithAccountItemRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Apollo.OpenApiClient.Accounts.Item.WithAccountItemRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Apollo.OpenApiClient.Accounts.Item.WithAccountItemRequestBuilder(rawUrl, RequestAdapter);
        }
    }
}
#pragma warning restore CS0618
