// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Apollo.OpenApiClient.Emailer_campaigns.Activity_feed;
using Soenneker.Apollo.OpenApiClient.Emailer_campaigns.Item;
using Soenneker.Apollo.OpenApiClient.Emailer_campaigns.Remove_or_stop_contact_ids;
using Soenneker.Apollo.OpenApiClient.Emailer_campaigns.Search;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Apollo.OpenApiClient.Emailer_campaigns
{
    /// <summary>
    /// Builds and executes requests for operations under \emailer_campaigns
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class Emailer_campaignsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The activity_feed property</summary>
        public global::Soenneker.Apollo.OpenApiClient.Emailer_campaigns.Activity_feed.Activity_feedRequestBuilder Activity_feed
        {
            get => new global::Soenneker.Apollo.OpenApiClient.Emailer_campaigns.Activity_feed.Activity_feedRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The remove_or_stop_contact_ids property</summary>
        public global::Soenneker.Apollo.OpenApiClient.Emailer_campaigns.Remove_or_stop_contact_ids.Remove_or_stop_contact_idsRequestBuilder Remove_or_stop_contact_ids
        {
            get => new global::Soenneker.Apollo.OpenApiClient.Emailer_campaigns.Remove_or_stop_contact_ids.Remove_or_stop_contact_idsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The search property</summary>
        public global::Soenneker.Apollo.OpenApiClient.Emailer_campaigns.Search.SearchRequestBuilder Search
        {
            get => new global::Soenneker.Apollo.OpenApiClient.Emailer_campaigns.Search.SearchRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>Gets an item from the Soenneker.Apollo.OpenApiClient.emailer_campaigns.item collection</summary>
        /// <param name="position">The Apollo ID for the sequence to which you want to add contacts. &lt;br&gt;&lt;br&gt;To find sequence IDs, call the &lt;a href=&quot;https://docs.apollo.io/reference/search-for-sequences&quot; target=&quot;_blank&quot;&gt;Search for Sequences endpoint&lt;/a&gt; and identify the `id` value for the sequence. &lt;br&gt;&lt;br&gt;Example: `66e9e215ece19801b219997f`</param>
        /// <returns>A <see cref="global::Soenneker.Apollo.OpenApiClient.Emailer_campaigns.Item.WithSequenceItemRequestBuilder"/></returns>
        public global::Soenneker.Apollo.OpenApiClient.Emailer_campaigns.Item.WithSequenceItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("sequenceId", position);
                return new global::Soenneker.Apollo.OpenApiClient.Emailer_campaigns.Item.WithSequenceItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Apollo.OpenApiClient.Emailer_campaigns.Emailer_campaignsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public Emailer_campaignsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/emailer_campaigns", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Apollo.OpenApiClient.Emailer_campaigns.Emailer_campaignsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public Emailer_campaignsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/emailer_campaigns", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
