// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Apollo.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum AddContactsToSequence200ResponseEmailerStepsItemType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "auto_email")]
        #pragma warning disable CS1591
        AutoEmail,
        #pragma warning restore CS1591
        [EnumMember(Value = "call")]
        #pragma warning disable CS1591
        Call,
        #pragma warning restore CS1591
        [EnumMember(Value = "action_item")]
        #pragma warning disable CS1591
        ActionItem,
        #pragma warning restore CS1591
        [EnumMember(Value = "manual_email")]
        #pragma warning disable CS1591
        ManualEmail,
        #pragma warning restore CS1591
    }
}
