// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Apollo.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class AddContactsToSequence200ResponseEmailerTouchesItem : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The bounce_rate property</summary>
        public double? BounceRate { get; set; }
        /// <summary>The emailer_step_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? EmailerStepId { get; set; }
#nullable restore
#else
        public string EmailerStepId { get; set; }
#endif
        /// <summary>The emailer_template_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? EmailerTemplateId { get; set; }
#nullable restore
#else
        public string EmailerTemplateId { get; set; }
#endif
        /// <summary>The has_personalized_opener property</summary>
        public bool? HasPersonalizedOpener { get; set; }
        /// <summary>The id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>The include_signature property</summary>
        public bool? IncludeSignature { get; set; }
        /// <summary>The open_rate property</summary>
        public double? OpenRate { get; set; }
        /// <summary>The reply_rate property</summary>
        public double? ReplyRate { get; set; }
        /// <summary>The status property</summary>
        public global::Soenneker.Apollo.OpenApiClient.Models.AddContactsToSequence200ResponseEmailerTouchesItemStatus? Status { get; set; }
        /// <summary>The template_type property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TemplateType { get; set; }
#nullable restore
#else
        public string TemplateType { get; set; }
#endif
        /// <summary>The type property</summary>
        public global::Soenneker.Apollo.OpenApiClient.Models.AddContactsToSequence200ResponseEmailerTouchesItemType? Type { get; set; }
        /// <summary>The unique_bounced property</summary>
        public int? UniqueBounced { get; set; }
        /// <summary>The unique_delivered property</summary>
        public int? UniqueDelivered { get; set; }
        /// <summary>The unique_opened property</summary>
        public int? UniqueOpened { get; set; }
        /// <summary>The unique_replied property</summary>
        public int? UniqueReplied { get; set; }
        /// <summary>The unique_scheduled property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Apollo.OpenApiClient.Models.AddContactsToSequence200ResponseEmailerTouchesItemUniqueScheduled? UniqueScheduled { get; set; }
#nullable restore
#else
        public global::Soenneker.Apollo.OpenApiClient.Models.AddContactsToSequence200ResponseEmailerTouchesItemUniqueScheduled UniqueScheduled { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Apollo.OpenApiClient.Models.AddContactsToSequence200ResponseEmailerTouchesItem"/> and sets the default values.
        /// </summary>
        public AddContactsToSequence200ResponseEmailerTouchesItem()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Apollo.OpenApiClient.Models.AddContactsToSequence200ResponseEmailerTouchesItem"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Apollo.OpenApiClient.Models.AddContactsToSequence200ResponseEmailerTouchesItem CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Apollo.OpenApiClient.Models.AddContactsToSequence200ResponseEmailerTouchesItem();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "bounce_rate", n => { BounceRate = n.GetDoubleValue(); } },
                { "emailer_step_id", n => { EmailerStepId = n.GetStringValue(); } },
                { "emailer_template_id", n => { EmailerTemplateId = n.GetStringValue(); } },
                { "has_personalized_opener", n => { HasPersonalizedOpener = n.GetBoolValue(); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "include_signature", n => { IncludeSignature = n.GetBoolValue(); } },
                { "open_rate", n => { OpenRate = n.GetDoubleValue(); } },
                { "reply_rate", n => { ReplyRate = n.GetDoubleValue(); } },
                { "status", n => { Status = n.GetEnumValue<global::Soenneker.Apollo.OpenApiClient.Models.AddContactsToSequence200ResponseEmailerTouchesItemStatus>(); } },
                { "template_type", n => { TemplateType = n.GetStringValue(); } },
                { "type", n => { Type = n.GetEnumValue<global::Soenneker.Apollo.OpenApiClient.Models.AddContactsToSequence200ResponseEmailerTouchesItemType>(); } },
                { "unique_bounced", n => { UniqueBounced = n.GetIntValue(); } },
                { "unique_delivered", n => { UniqueDelivered = n.GetIntValue(); } },
                { "unique_opened", n => { UniqueOpened = n.GetIntValue(); } },
                { "unique_replied", n => { UniqueReplied = n.GetIntValue(); } },
                { "unique_scheduled", n => { UniqueScheduled = n.GetObjectValue<global::Soenneker.Apollo.OpenApiClient.Models.AddContactsToSequence200ResponseEmailerTouchesItemUniqueScheduled>(global::Soenneker.Apollo.OpenApiClient.Models.AddContactsToSequence200ResponseEmailerTouchesItemUniqueScheduled.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteDoubleValue("bounce_rate", BounceRate);
            writer.WriteStringValue("emailer_step_id", EmailerStepId);
            writer.WriteStringValue("emailer_template_id", EmailerTemplateId);
            writer.WriteBoolValue("has_personalized_opener", HasPersonalizedOpener);
            writer.WriteStringValue("id", Id);
            writer.WriteBoolValue("include_signature", IncludeSignature);
            writer.WriteDoubleValue("open_rate", OpenRate);
            writer.WriteDoubleValue("reply_rate", ReplyRate);
            writer.WriteEnumValue<global::Soenneker.Apollo.OpenApiClient.Models.AddContactsToSequence200ResponseEmailerTouchesItemStatus>("status", Status);
            writer.WriteStringValue("template_type", TemplateType);
            writer.WriteEnumValue<global::Soenneker.Apollo.OpenApiClient.Models.AddContactsToSequence200ResponseEmailerTouchesItemType>("type", Type);
            writer.WriteIntValue("unique_bounced", UniqueBounced);
            writer.WriteIntValue("unique_delivered", UniqueDelivered);
            writer.WriteIntValue("unique_opened", UniqueOpened);
            writer.WriteIntValue("unique_replied", UniqueReplied);
            writer.WriteObjectValue<global::Soenneker.Apollo.OpenApiClient.Models.AddContactsToSequence200ResponseEmailerTouchesItemUniqueScheduled>("unique_scheduled", UniqueScheduled);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
