// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Apollo.OpenApiClient.Models
{
    /// <summary>
    /// Returned instead of `labels` when `async` is `true`. Represents the background job processing the request; poll it to track progress.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class AddRecordsToAList200ResponseEntityProgressJob : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The batch_size property</summary>
        public int? BatchSize { get; set; }
        /// <summary>The entity_ids property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? EntityIds { get; set; }
#nullable restore
#else
        public List<string> EntityIds { get; set; }
#endif
        /// <summary>The id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>The job_type property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? JobType { get; set; }
#nullable restore
#else
        public string JobType { get; set; }
#endif
        /// <summary>The params property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Apollo.OpenApiClient.Models.AddRecordsToAList200ResponseEntityProgressJobParams? Params { get; set; }
#nullable restore
#else
        public global::Soenneker.Apollo.OpenApiClient.Models.AddRecordsToAList200ResponseEntityProgressJobParams Params { get; set; }
#endif
        /// <summary>`-1` before processing starts, a fraction while in progress, and `1` when complete.</summary>
        public double? Progress { get; set; }
        /// <summary>The user_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? UserId { get; set; }
#nullable restore
#else
        public string UserId { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Apollo.OpenApiClient.Models.AddRecordsToAList200ResponseEntityProgressJob"/> and sets the default values.
        /// </summary>
        public AddRecordsToAList200ResponseEntityProgressJob()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Apollo.OpenApiClient.Models.AddRecordsToAList200ResponseEntityProgressJob"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Apollo.OpenApiClient.Models.AddRecordsToAList200ResponseEntityProgressJob CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Apollo.OpenApiClient.Models.AddRecordsToAList200ResponseEntityProgressJob();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "batch_size", n => { BatchSize = n.GetIntValue(); } },
                { "entity_ids", n => { EntityIds = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "job_type", n => { JobType = n.GetStringValue(); } },
                { "params", n => { Params = n.GetObjectValue<global::Soenneker.Apollo.OpenApiClient.Models.AddRecordsToAList200ResponseEntityProgressJobParams>(global::Soenneker.Apollo.OpenApiClient.Models.AddRecordsToAList200ResponseEntityProgressJobParams.CreateFromDiscriminatorValue); } },
                { "progress", n => { Progress = n.GetDoubleValue(); } },
                { "user_id", n => { UserId = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteIntValue("batch_size", BatchSize);
            writer.WriteCollectionOfPrimitiveValues<string>("entity_ids", EntityIds);
            writer.WriteStringValue("id", Id);
            writer.WriteStringValue("job_type", JobType);
            writer.WriteObjectValue<global::Soenneker.Apollo.OpenApiClient.Models.AddRecordsToAList200ResponseEntityProgressJobParams>("params", Params);
            writer.WriteDoubleValue("progress", Progress);
            writer.WriteStringValue("user_id", UserId);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
