// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Apollo.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class BulkUpdateAccountsRequest : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Array of account objects with individual updates. Use this for applying different updates to each account.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Apollo.OpenApiClient.Models.BulkUpdateAccountsRequestAccountAttributesItem>? AccountAttributes { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Apollo.OpenApiClient.Models.BulkUpdateAccountsRequestAccountAttributesItem> AccountAttributes { get; set; }
#endif
        /// <summary>Array of account IDs to update with the same values. Use this for applying the same updates to multiple accounts.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? AccountIds { get; set; }
#nullable restore
#else
        public List<string> AccountIds { get; set; }
#endif
        /// <summary>When using account_ids, apply this account stage to all accounts</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AccountStageId { get; set; }
#nullable restore
#else
        public string AccountStageId { get; set; }
#endif
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Set to true to process updates asynchronously. Only available when using account_ids. Not supported with account_attributes.</summary>
        public bool? Async { get; set; }
        /// <summary>When using account_ids, apply this name to all accounts</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>When using account_ids, apply this owner to all accounts</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? OwnerId { get; set; }
#nullable restore
#else
        public string OwnerId { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Apollo.OpenApiClient.Models.BulkUpdateAccountsRequest"/> and sets the default values.
        /// </summary>
        public BulkUpdateAccountsRequest()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Apollo.OpenApiClient.Models.BulkUpdateAccountsRequest"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Apollo.OpenApiClient.Models.BulkUpdateAccountsRequest CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Apollo.OpenApiClient.Models.BulkUpdateAccountsRequest();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "account_attributes", n => { AccountAttributes = n.GetCollectionOfObjectValues<global::Soenneker.Apollo.OpenApiClient.Models.BulkUpdateAccountsRequestAccountAttributesItem>(global::Soenneker.Apollo.OpenApiClient.Models.BulkUpdateAccountsRequestAccountAttributesItem.CreateFromDiscriminatorValue)?.AsList(); } },
                { "account_ids", n => { AccountIds = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "account_stage_id", n => { AccountStageId = n.GetStringValue(); } },
                { "async", n => { Async = n.GetBoolValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "owner_id", n => { OwnerId = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::Soenneker.Apollo.OpenApiClient.Models.BulkUpdateAccountsRequestAccountAttributesItem>("account_attributes", AccountAttributes);
            writer.WriteCollectionOfPrimitiveValues<string>("account_ids", AccountIds);
            writer.WriteStringValue("account_stage_id", AccountStageId);
            writer.WriteBoolValue("async", Async);
            writer.WriteStringValue("name", Name);
            writer.WriteStringValue("owner_id", OwnerId);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
