// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Apollo.OpenApiClient.Models
{
    /// <summary>`pending` means enrichment is running and a webhook will follow. `skipped` means the matched people already had an enrichment in progress from an earlier request, so no webhook will be sent for this request — the results arrive via the earlier request instead.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum BulkPeopleEnrichment200ResponsePhoneEnrichmentStatus
    {
        [EnumMember(Value = "pending")]
        #pragma warning disable CS1591
        Pending,
        #pragma warning restore CS1591
        [EnumMember(Value = "skipped")]
        #pragma warning disable CS1591
        Skipped,
        #pragma warning restore CS1591
    }
}
