// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Apollo.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class BulkOrganizationEnrichment200Response : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The error_code property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Apollo.OpenApiClient.Models.BulkOrganizationEnrichment200ResponseErrorCode? ErrorCode { get; set; }
#nullable restore
#else
        public global::Soenneker.Apollo.OpenApiClient.Models.BulkOrganizationEnrichment200ResponseErrorCode ErrorCode { get; set; }
#endif
        /// <summary>The error_message property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Apollo.OpenApiClient.Models.BulkOrganizationEnrichment200ResponseErrorMessage? ErrorMessage { get; set; }
#nullable restore
#else
        public global::Soenneker.Apollo.OpenApiClient.Models.BulkOrganizationEnrichment200ResponseErrorMessage ErrorMessage { get; set; }
#endif
        /// <summary>The missing_records property</summary>
        public int? MissingRecords { get; set; }
        /// <summary>The organizations property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Apollo.OpenApiClient.Models.BulkOrganizationEnrichment200ResponseOrganizationsItem>? Organizations { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Apollo.OpenApiClient.Models.BulkOrganizationEnrichment200ResponseOrganizationsItem> Organizations { get; set; }
#endif
        /// <summary>The status property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Status { get; set; }
#nullable restore
#else
        public string Status { get; set; }
#endif
        /// <summary>The total number of domains submitted via the `domains[]` query parameter, including duplicates. Returned only for `domains[]` requests; `null` when you enrich using the `details` payload.</summary>
        public int? TotalRequestedDomains { get; set; }
        /// <summary>The total number of companies submitted in the `details` payload, including duplicates. Returned only when you enrich using the `details` request body; `null` for `domains[]` requests.</summary>
        public int? TotalRequestedRecords { get; set; }
        /// <summary>The number of unique domains submitted via the `domains[]` query parameter. Returned only for `domains[]` requests; `null` when you enrich using the `details` payload.</summary>
        public int? UniqueDomains { get; set; }
        /// <summary>The unique_enriched_records property</summary>
        public int? UniqueEnrichedRecords { get; set; }
        /// <summary>The number of unique companies submitted in the `details` payload after de-duplication. Returned only when you enrich using the `details` request body; `null` for `domains[]` requests.</summary>
        public int? UniqueRecords { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Apollo.OpenApiClient.Models.BulkOrganizationEnrichment200Response"/> and sets the default values.
        /// </summary>
        public BulkOrganizationEnrichment200Response()
        {
            AdditionalData = new Dictionary<string, object>();
            MissingRecords = 0;
            TotalRequestedDomains = 0;
            TotalRequestedRecords = 0;
            UniqueDomains = 0;
            UniqueEnrichedRecords = 0;
            UniqueRecords = 0;
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Apollo.OpenApiClient.Models.BulkOrganizationEnrichment200Response"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Apollo.OpenApiClient.Models.BulkOrganizationEnrichment200Response CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Apollo.OpenApiClient.Models.BulkOrganizationEnrichment200Response();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "error_code", n => { ErrorCode = n.GetObjectValue<global::Soenneker.Apollo.OpenApiClient.Models.BulkOrganizationEnrichment200ResponseErrorCode>(global::Soenneker.Apollo.OpenApiClient.Models.BulkOrganizationEnrichment200ResponseErrorCode.CreateFromDiscriminatorValue); } },
                { "error_message", n => { ErrorMessage = n.GetObjectValue<global::Soenneker.Apollo.OpenApiClient.Models.BulkOrganizationEnrichment200ResponseErrorMessage>(global::Soenneker.Apollo.OpenApiClient.Models.BulkOrganizationEnrichment200ResponseErrorMessage.CreateFromDiscriminatorValue); } },
                { "missing_records", n => { MissingRecords = n.GetIntValue(); } },
                { "organizations", n => { Organizations = n.GetCollectionOfObjectValues<global::Soenneker.Apollo.OpenApiClient.Models.BulkOrganizationEnrichment200ResponseOrganizationsItem>(global::Soenneker.Apollo.OpenApiClient.Models.BulkOrganizationEnrichment200ResponseOrganizationsItem.CreateFromDiscriminatorValue)?.AsList(); } },
                { "status", n => { Status = n.GetStringValue(); } },
                { "total_requested_domains", n => { TotalRequestedDomains = n.GetIntValue(); } },
                { "total_requested_records", n => { TotalRequestedRecords = n.GetIntValue(); } },
                { "unique_domains", n => { UniqueDomains = n.GetIntValue(); } },
                { "unique_enriched_records", n => { UniqueEnrichedRecords = n.GetIntValue(); } },
                { "unique_records", n => { UniqueRecords = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Apollo.OpenApiClient.Models.BulkOrganizationEnrichment200ResponseErrorCode>("error_code", ErrorCode);
            writer.WriteObjectValue<global::Soenneker.Apollo.OpenApiClient.Models.BulkOrganizationEnrichment200ResponseErrorMessage>("error_message", ErrorMessage);
            writer.WriteIntValue("missing_records", MissingRecords);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Apollo.OpenApiClient.Models.BulkOrganizationEnrichment200ResponseOrganizationsItem>("organizations", Organizations);
            writer.WriteStringValue("status", Status);
            writer.WriteIntValue("total_requested_domains", TotalRequestedDomains);
            writer.WriteIntValue("total_requested_records", TotalRequestedRecords);
            writer.WriteIntValue("unique_domains", UniqueDomains);
            writer.WriteIntValue("unique_enriched_records", UniqueEnrichedRecords);
            writer.WriteIntValue("unique_records", UniqueRecords);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
