// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Apollo.OpenApiClient.Models
{
    /// <summary>
    /// Details about the logged phone call for this task. Only present for `call` type tasks that have an associated call log.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class CompleteATask200ResponseTaskPhoneCall : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The answered property</summary>
        public bool? Answered { get; set; }
        /// <summary>The created_at property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CreatedAt { get; set; }
#nullable restore
#else
        public string CreatedAt { get; set; }
#endif
        /// <summary>The id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>The phone_call_outcome_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Apollo.OpenApiClient.Models.CompleteATask200ResponseTaskPhoneCallPhoneCallOutcomeId? PhoneCallOutcomeId { get; set; }
#nullable restore
#else
        public global::Soenneker.Apollo.OpenApiClient.Models.CompleteATask200ResponseTaskPhoneCallPhoneCallOutcomeId PhoneCallOutcomeId { get; set; }
#endif
        /// <summary>The phone_call_purpose_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Apollo.OpenApiClient.Models.CompleteATask200ResponseTaskPhoneCallPhoneCallPurposeId? PhoneCallPurposeId { get; set; }
#nullable restore
#else
        public global::Soenneker.Apollo.OpenApiClient.Models.CompleteATask200ResponseTaskPhoneCallPhoneCallPurposeId PhoneCallPurposeId { get; set; }
#endif
        /// <summary>The number that was called. May be partially masked depending on your team&apos;s phone number redaction settings.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ToNumber { get; set; }
#nullable restore
#else
        public string ToNumber { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Apollo.OpenApiClient.Models.CompleteATask200ResponseTaskPhoneCall"/> and sets the default values.
        /// </summary>
        public CompleteATask200ResponseTaskPhoneCall()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Apollo.OpenApiClient.Models.CompleteATask200ResponseTaskPhoneCall"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Apollo.OpenApiClient.Models.CompleteATask200ResponseTaskPhoneCall CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Apollo.OpenApiClient.Models.CompleteATask200ResponseTaskPhoneCall();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "answered", n => { Answered = n.GetBoolValue(); } },
                { "created_at", n => { CreatedAt = n.GetStringValue(); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "phone_call_outcome_id", n => { PhoneCallOutcomeId = n.GetObjectValue<global::Soenneker.Apollo.OpenApiClient.Models.CompleteATask200ResponseTaskPhoneCallPhoneCallOutcomeId>(global::Soenneker.Apollo.OpenApiClient.Models.CompleteATask200ResponseTaskPhoneCallPhoneCallOutcomeId.CreateFromDiscriminatorValue); } },
                { "phone_call_purpose_id", n => { PhoneCallPurposeId = n.GetObjectValue<global::Soenneker.Apollo.OpenApiClient.Models.CompleteATask200ResponseTaskPhoneCallPhoneCallPurposeId>(global::Soenneker.Apollo.OpenApiClient.Models.CompleteATask200ResponseTaskPhoneCallPhoneCallPurposeId.CreateFromDiscriminatorValue); } },
                { "to_number", n => { ToNumber = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("answered", Answered);
            writer.WriteStringValue("created_at", CreatedAt);
            writer.WriteStringValue("id", Id);
            writer.WriteObjectValue<global::Soenneker.Apollo.OpenApiClient.Models.CompleteATask200ResponseTaskPhoneCallPhoneCallOutcomeId>("phone_call_outcome_id", PhoneCallOutcomeId);
            writer.WriteObjectValue<global::Soenneker.Apollo.OpenApiClient.Models.CompleteATask200ResponseTaskPhoneCallPhoneCallPurposeId>("phone_call_purpose_id", PhoneCallPurposeId);
            writer.WriteStringValue("to_number", ToNumber);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
