// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Apollo.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class CreateAContactRequest : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>&quot;The Apollo ID for the account. Example: `63f53afe4ceeca00016bdd2f`&quot;</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AccountId { get; set; }
#nullable restore
#else
        public string AccountId { get; set; }
#endif
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>&quot;The Apollo ID for the contact stage. Example: `6095a710bd01d100a506d4ae`&quot;</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ContactStageId { get; set; }
#nullable restore
#else
        public string ContactStageId { get; set; }
#endif
        /// <summary>&quot;The work/office phone number. Example: `+44 7700 900852`&quot;</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CorporatePhone { get; set; }
#nullable restore
#else
        public string CorporatePhone { get; set; }
#endif
        /// <summary>&quot;The primary phone number. Example: `555-555-0133`&quot;</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DirectPhone { get; set; }
#nullable restore
#else
        public string DirectPhone { get; set; }
#endif
        /// <summary>&quot;The email address of the contact. Example: `example@email.com`&quot;</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Email { get; set; }
#nullable restore
#else
        public string Email { get; set; }
#endif
        /// <summary>&quot;The first name of the contact you want to create. Example: `Tim`&quot;</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? FirstName { get; set; }
#nullable restore
#else
        public string FirstName { get; set; }
#endif
        /// <summary>&quot;The home phone number. Example: `555-555-0133`&quot;</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? HomePhone { get; set; }
#nullable restore
#else
        public string HomePhone { get; set; }
#endif
        /// <summary>Lists to which the contact belongs.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? LabelNames { get; set; }
#nullable restore
#else
        public List<string> LabelNames { get; set; }
#endif
        /// <summary>&quot;The last name of the contact you want to create. Example: `Zheng`&quot;</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? LastName { get; set; }
#nullable restore
#else
        public string LastName { get; set; }
#endif
        /// <summary>&quot;The mobile phone number. Example: `555-555-0133`&quot;</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? MobilePhone { get; set; }
#nullable restore
#else
        public string MobilePhone { get; set; }
#endif
        /// <summary>&quot;The name of the contact&apos;s employer (company). Example: `apollo`&quot;</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? OrganizationName { get; set; }
#nullable restore
#else
        public string OrganizationName { get; set; }
#endif
        /// <summary>&quot;Alternative phone number. Example: `555-555-0133`&quot;</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? OtherPhone { get; set; }
#nullable restore
#else
        public string OtherPhone { get; set; }
#endif
        /// <summary>&quot;The personal location for the contact. Example: `Atlanta, United States`&quot;</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PresentRawAddress { get; set; }
#nullable restore
#else
        public string PresentRawAddress { get; set; }
#endif
        /// <summary>&quot;Set to `true` to match against your existing contacts instead of always creating a new one. The default value is `false`. &lt;br&gt;&lt;br&gt;When a match is found, Apollo **updates that existing contact in place** with the values you sent and returns it — the `id` in the response belongs to the pre-existing contact, not a new record. Fields you send overwrite the stored values, fields you omit are left untouched, and sending an empty value clears the field. &lt;br&gt;&lt;br&gt;Matching is checked in order: `id`, CRM identifiers, `person_id`, `email` (against the contact&apos;s primary and additional emails), then name plus company. Because of the last rule, a contact can be matched and updated even when the email differs. &lt;br&gt;&lt;br&gt;When deduplication is enabled, performance may be slightly impacted due to the additional matching checks. See the endpoint description for full details.&quot;</summary>
        public bool? RunDedupe { get; set; }
        /// <summary>&quot;The current job title that the contact holds. Example: `senior research analyst`&quot;</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Title { get; set; }
#nullable restore
#else
        public string Title { get; set; }
#endif
        /// <summary>&quot;Add information to &lt;a href=\&quot;https://knowledge.apollo.io/hc/en-us/articles/4412498825869-Create-Custom-Contact-Fields\&quot; target=\&quot;_blank\&quot;&gt;custom fields&lt;/a&gt; in Apollo. &lt;br&gt;&lt;br&gt;&lt;b&gt;Your custom fields are unique to your team&apos;s Apollo account. This means that the examples in this documentation may not work for your testing purposes.&lt;/b&gt; &lt;br&gt;&lt;br&gt;To utilize this parameter successfully, call the &lt;a href=\&quot;https://docs.apollo.io/reference/get-a-list-of-all-custom-fields\&quot;&gt;Get a List of All Custom Fields&lt;/a&gt; endpoint and identify the `id` value for the custom field, as well as the appropriate data type. For example, if a custom field accepts picklist entries, you need to pass the accompanying `id` value for the picklist entry that you want to use as the input value. &lt;br&gt;&lt;br&gt;&lt;b&gt;Example&lt;/b&gt;: When the &lt;a href=\&quot;https://docs.apollo.io/reference/get-a-list-of-all-custom-fields\&quot;&gt;Get a List of All Custom Fields&lt;/a&gt; endpoint returns an `id` of field:  * `\&quot;60c39ed82bd02f01154c470a\&quot;` (datetime)   then the value passed should be:  `{\&quot;60c39ed82bd02f01154c470a\&quot;: \&quot;2025-08-07\&quot;}`&quot;</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Apollo.OpenApiClient.Models.CreateAContactRequestTypedCustomFields? TypedCustomFields { get; set; }
#nullable restore
#else
        public global::Soenneker.Apollo.OpenApiClient.Models.CreateAContactRequestTypedCustomFields TypedCustomFields { get; set; }
#endif
        /// <summary>&quot;The corporate website URL. Example: `https://www.apollo.io/`&quot;</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? WebsiteUrl { get; set; }
#nullable restore
#else
        public string WebsiteUrl { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Apollo.OpenApiClient.Models.CreateAContactRequest"/> and sets the default values.
        /// </summary>
        public CreateAContactRequest()
        {
            AdditionalData = new Dictionary<string, object>();
            RunDedupe = false;
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Apollo.OpenApiClient.Models.CreateAContactRequest"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Apollo.OpenApiClient.Models.CreateAContactRequest CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Apollo.OpenApiClient.Models.CreateAContactRequest();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "account_id", n => { AccountId = n.GetStringValue(); } },
                { "contact_stage_id", n => { ContactStageId = n.GetStringValue(); } },
                { "corporate_phone", n => { CorporatePhone = n.GetStringValue(); } },
                { "direct_phone", n => { DirectPhone = n.GetStringValue(); } },
                { "email", n => { Email = n.GetStringValue(); } },
                { "first_name", n => { FirstName = n.GetStringValue(); } },
                { "home_phone", n => { HomePhone = n.GetStringValue(); } },
                { "label_names", n => { LabelNames = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "last_name", n => { LastName = n.GetStringValue(); } },
                { "mobile_phone", n => { MobilePhone = n.GetStringValue(); } },
                { "organization_name", n => { OrganizationName = n.GetStringValue(); } },
                { "other_phone", n => { OtherPhone = n.GetStringValue(); } },
                { "present_raw_address", n => { PresentRawAddress = n.GetStringValue(); } },
                { "run_dedupe", n => { RunDedupe = n.GetBoolValue(); } },
                { "title", n => { Title = n.GetStringValue(); } },
                { "typed_custom_fields", n => { TypedCustomFields = n.GetObjectValue<global::Soenneker.Apollo.OpenApiClient.Models.CreateAContactRequestTypedCustomFields>(global::Soenneker.Apollo.OpenApiClient.Models.CreateAContactRequestTypedCustomFields.CreateFromDiscriminatorValue); } },
                { "website_url", n => { WebsiteUrl = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("account_id", AccountId);
            writer.WriteStringValue("contact_stage_id", ContactStageId);
            writer.WriteStringValue("corporate_phone", CorporatePhone);
            writer.WriteStringValue("direct_phone", DirectPhone);
            writer.WriteStringValue("email", Email);
            writer.WriteStringValue("first_name", FirstName);
            writer.WriteStringValue("home_phone", HomePhone);
            writer.WriteCollectionOfPrimitiveValues<string>("label_names", LabelNames);
            writer.WriteStringValue("last_name", LastName);
            writer.WriteStringValue("mobile_phone", MobilePhone);
            writer.WriteStringValue("organization_name", OrganizationName);
            writer.WriteStringValue("other_phone", OtherPhone);
            writer.WriteStringValue("present_raw_address", PresentRawAddress);
            writer.WriteBoolValue("run_dedupe", RunDedupe);
            writer.WriteStringValue("title", Title);
            writer.WriteObjectValue<global::Soenneker.Apollo.OpenApiClient.Models.CreateAContactRequestTypedCustomFields>("typed_custom_fields", TypedCustomFields);
            writer.WriteStringValue("website_url", WebsiteUrl);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
