// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Apollo.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class CreateATask200ResponseTask : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The account_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Apollo.OpenApiClient.Models.CreateATask200ResponseTaskAccountId? AccountId { get; set; }
#nullable restore
#else
        public global::Soenneker.Apollo.OpenApiClient.Models.CreateATask200ResponseTaskAccountId AccountId { get; set; }
#endif
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The answered property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Apollo.OpenApiClient.Models.CreateATask200ResponseTaskAnswered? Answered { get; set; }
#nullable restore
#else
        public global::Soenneker.Apollo.OpenApiClient.Models.CreateATask200ResponseTaskAnswered Answered { get; set; }
#endif
        /// <summary>The completed_at property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Apollo.OpenApiClient.Models.CreateATask200ResponseTaskCompletedAt? CompletedAt { get; set; }
#nullable restore
#else
        public global::Soenneker.Apollo.OpenApiClient.Models.CreateATask200ResponseTaskCompletedAt CompletedAt { get; set; }
#endif
        /// <summary>The contact_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Apollo.OpenApiClient.Models.CreateATask200ResponseTaskContactId? ContactId { get; set; }
#nullable restore
#else
        public global::Soenneker.Apollo.OpenApiClient.Models.CreateATask200ResponseTaskContactId ContactId { get; set; }
#endif
        /// <summary>The created_at property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CreatedAt { get; set; }
#nullable restore
#else
        public string CreatedAt { get; set; }
#endif
        /// <summary>The created_from property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Apollo.OpenApiClient.Models.CreateATask200ResponseTaskCreatedFrom? CreatedFrom { get; set; }
#nullable restore
#else
        public global::Soenneker.Apollo.OpenApiClient.Models.CreateATask200ResponseTaskCreatedFrom CreatedFrom { get; set; }
#endif
        /// <summary>The creator_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CreatorId { get; set; }
#nullable restore
#else
        public string CreatorId { get; set; }
#endif
        /// <summary>The due_at property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DueAt { get; set; }
#nullable restore
#else
        public string DueAt { get; set; }
#endif
        /// <summary>The emailer_campaign_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Apollo.OpenApiClient.Models.CreateATask200ResponseTaskEmailerCampaignId? EmailerCampaignId { get; set; }
#nullable restore
#else
        public global::Soenneker.Apollo.OpenApiClient.Models.CreateATask200ResponseTaskEmailerCampaignId EmailerCampaignId { get; set; }
#endif
        /// <summary>The hubspot_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Apollo.OpenApiClient.Models.CreateATask200ResponseTaskHubspotId? HubspotId { get; set; }
#nullable restore
#else
        public global::Soenneker.Apollo.OpenApiClient.Models.CreateATask200ResponseTaskHubspotId HubspotId { get; set; }
#endif
        /// <summary>The id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>The needs_playbook_autoprospecting property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Apollo.OpenApiClient.Models.CreateATask200ResponseTaskNeedsPlaybookAutoprospecting? NeedsPlaybookAutoprospecting { get; set; }
#nullable restore
#else
        public global::Soenneker.Apollo.OpenApiClient.Models.CreateATask200ResponseTaskNeedsPlaybookAutoprospecting NeedsPlaybookAutoprospecting { get; set; }
#endif
        /// <summary>The note property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Apollo.OpenApiClient.Models.CreateATask200ResponseTaskNote? Note { get; set; }
#nullable restore
#else
        public global::Soenneker.Apollo.OpenApiClient.Models.CreateATask200ResponseTaskNote Note { get; set; }
#endif
        /// <summary>The opportunity property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Apollo.OpenApiClient.Models.CreateATask200ResponseTaskOpportunity? Opportunity { get; set; }
#nullable restore
#else
        public global::Soenneker.Apollo.OpenApiClient.Models.CreateATask200ResponseTaskOpportunity Opportunity { get; set; }
#endif
        /// <summary>The opportunity_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? OpportunityId { get; set; }
#nullable restore
#else
        public string OpportunityId { get; set; }
#endif
        /// <summary>The organization_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Apollo.OpenApiClient.Models.CreateATask200ResponseTaskOrganizationId? OrganizationId { get; set; }
#nullable restore
#else
        public global::Soenneker.Apollo.OpenApiClient.Models.CreateATask200ResponseTaskOrganizationId OrganizationId { get; set; }
#endif
        /// <summary>The persona_ids property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Apollo.OpenApiClient.Models.CreateATask200ResponseTask_persona_ids>? PersonaIds { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Apollo.OpenApiClient.Models.CreateATask200ResponseTask_persona_ids> PersonaIds { get; set; }
#endif
        /// <summary>The person_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Apollo.OpenApiClient.Models.CreateATask200ResponseTaskPersonId? PersonId { get; set; }
#nullable restore
#else
        public global::Soenneker.Apollo.OpenApiClient.Models.CreateATask200ResponseTaskPersonId PersonId { get; set; }
#endif
        /// <summary>The playbook_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Apollo.OpenApiClient.Models.CreateATask200ResponseTaskPlaybookId? PlaybookId { get; set; }
#nullable restore
#else
        public global::Soenneker.Apollo.OpenApiClient.Models.CreateATask200ResponseTaskPlaybookId PlaybookId { get; set; }
#endif
        /// <summary>The playbook_step_ids property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Apollo.OpenApiClient.Models.CreateATask200ResponseTask_playbook_step_ids>? PlaybookStepIds { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Apollo.OpenApiClient.Models.CreateATask200ResponseTask_playbook_step_ids> PlaybookStepIds { get; set; }
#endif
        /// <summary>The priority property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Priority { get; set; }
#nullable restore
#else
        public string Priority { get; set; }
#endif
        /// <summary>The rule_config_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Apollo.OpenApiClient.Models.CreateATask200ResponseTaskRuleConfigId? RuleConfigId { get; set; }
#nullable restore
#else
        public global::Soenneker.Apollo.OpenApiClient.Models.CreateATask200ResponseTaskRuleConfigId RuleConfigId { get; set; }
#endif
        /// <summary>The salesforce_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Apollo.OpenApiClient.Models.CreateATask200ResponseTaskSalesforceId? SalesforceId { get; set; }
#nullable restore
#else
        public global::Soenneker.Apollo.OpenApiClient.Models.CreateATask200ResponseTaskSalesforceId SalesforceId { get; set; }
#endif
        /// <summary>The salesforce_type property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Apollo.OpenApiClient.Models.CreateATask200ResponseTaskSalesforceType? SalesforceType { get; set; }
#nullable restore
#else
        public global::Soenneker.Apollo.OpenApiClient.Models.CreateATask200ResponseTaskSalesforceType SalesforceType { get; set; }
#endif
        /// <summary>The skipped_at property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Apollo.OpenApiClient.Models.CreateATask200ResponseTaskSkippedAt? SkippedAt { get; set; }
#nullable restore
#else
        public global::Soenneker.Apollo.OpenApiClient.Models.CreateATask200ResponseTaskSkippedAt SkippedAt { get; set; }
#endif
        /// <summary>The starred_by_user_ids property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Apollo.OpenApiClient.Models.CreateATask200ResponseTask_starred_by_user_ids>? StarredByUserIds { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Apollo.OpenApiClient.Models.CreateATask200ResponseTask_starred_by_user_ids> StarredByUserIds { get; set; }
#endif
        /// <summary>The status property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Status { get; set; }
#nullable restore
#else
        public string Status { get; set; }
#endif
        /// <summary>The subject property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Apollo.OpenApiClient.Models.CreateATask200ResponseTaskSubject? Subject { get; set; }
#nullable restore
#else
        public global::Soenneker.Apollo.OpenApiClient.Models.CreateATask200ResponseTaskSubject Subject { get; set; }
#endif
        /// <summary>The title property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Title { get; set; }
#nullable restore
#else
        public string Title { get; set; }
#endif
        /// <summary>The type property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Type { get; set; }
#nullable restore
#else
        public string Type { get; set; }
#endif
        /// <summary>The user_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? UserId { get; set; }
#nullable restore
#else
        public string UserId { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Apollo.OpenApiClient.Models.CreateATask200ResponseTask"/> and sets the default values.
        /// </summary>
        public CreateATask200ResponseTask()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Apollo.OpenApiClient.Models.CreateATask200ResponseTask"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Apollo.OpenApiClient.Models.CreateATask200ResponseTask CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Apollo.OpenApiClient.Models.CreateATask200ResponseTask();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "account_id", n => { AccountId = n.GetObjectValue<global::Soenneker.Apollo.OpenApiClient.Models.CreateATask200ResponseTaskAccountId>(global::Soenneker.Apollo.OpenApiClient.Models.CreateATask200ResponseTaskAccountId.CreateFromDiscriminatorValue); } },
                { "answered", n => { Answered = n.GetObjectValue<global::Soenneker.Apollo.OpenApiClient.Models.CreateATask200ResponseTaskAnswered>(global::Soenneker.Apollo.OpenApiClient.Models.CreateATask200ResponseTaskAnswered.CreateFromDiscriminatorValue); } },
                { "completed_at", n => { CompletedAt = n.GetObjectValue<global::Soenneker.Apollo.OpenApiClient.Models.CreateATask200ResponseTaskCompletedAt>(global::Soenneker.Apollo.OpenApiClient.Models.CreateATask200ResponseTaskCompletedAt.CreateFromDiscriminatorValue); } },
                { "contact_id", n => { ContactId = n.GetObjectValue<global::Soenneker.Apollo.OpenApiClient.Models.CreateATask200ResponseTaskContactId>(global::Soenneker.Apollo.OpenApiClient.Models.CreateATask200ResponseTaskContactId.CreateFromDiscriminatorValue); } },
                { "created_at", n => { CreatedAt = n.GetStringValue(); } },
                { "created_from", n => { CreatedFrom = n.GetObjectValue<global::Soenneker.Apollo.OpenApiClient.Models.CreateATask200ResponseTaskCreatedFrom>(global::Soenneker.Apollo.OpenApiClient.Models.CreateATask200ResponseTaskCreatedFrom.CreateFromDiscriminatorValue); } },
                { "creator_id", n => { CreatorId = n.GetStringValue(); } },
                { "due_at", n => { DueAt = n.GetStringValue(); } },
                { "emailer_campaign_id", n => { EmailerCampaignId = n.GetObjectValue<global::Soenneker.Apollo.OpenApiClient.Models.CreateATask200ResponseTaskEmailerCampaignId>(global::Soenneker.Apollo.OpenApiClient.Models.CreateATask200ResponseTaskEmailerCampaignId.CreateFromDiscriminatorValue); } },
                { "hubspot_id", n => { HubspotId = n.GetObjectValue<global::Soenneker.Apollo.OpenApiClient.Models.CreateATask200ResponseTaskHubspotId>(global::Soenneker.Apollo.OpenApiClient.Models.CreateATask200ResponseTaskHubspotId.CreateFromDiscriminatorValue); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "needs_playbook_autoprospecting", n => { NeedsPlaybookAutoprospecting = n.GetObjectValue<global::Soenneker.Apollo.OpenApiClient.Models.CreateATask200ResponseTaskNeedsPlaybookAutoprospecting>(global::Soenneker.Apollo.OpenApiClient.Models.CreateATask200ResponseTaskNeedsPlaybookAutoprospecting.CreateFromDiscriminatorValue); } },
                { "note", n => { Note = n.GetObjectValue<global::Soenneker.Apollo.OpenApiClient.Models.CreateATask200ResponseTaskNote>(global::Soenneker.Apollo.OpenApiClient.Models.CreateATask200ResponseTaskNote.CreateFromDiscriminatorValue); } },
                { "opportunity", n => { Opportunity = n.GetObjectValue<global::Soenneker.Apollo.OpenApiClient.Models.CreateATask200ResponseTaskOpportunity>(global::Soenneker.Apollo.OpenApiClient.Models.CreateATask200ResponseTaskOpportunity.CreateFromDiscriminatorValue); } },
                { "opportunity_id", n => { OpportunityId = n.GetStringValue(); } },
                { "organization_id", n => { OrganizationId = n.GetObjectValue<global::Soenneker.Apollo.OpenApiClient.Models.CreateATask200ResponseTaskOrganizationId>(global::Soenneker.Apollo.OpenApiClient.Models.CreateATask200ResponseTaskOrganizationId.CreateFromDiscriminatorValue); } },
                { "person_id", n => { PersonId = n.GetObjectValue<global::Soenneker.Apollo.OpenApiClient.Models.CreateATask200ResponseTaskPersonId>(global::Soenneker.Apollo.OpenApiClient.Models.CreateATask200ResponseTaskPersonId.CreateFromDiscriminatorValue); } },
                { "persona_ids", n => { PersonaIds = n.GetCollectionOfObjectValues<global::Soenneker.Apollo.OpenApiClient.Models.CreateATask200ResponseTask_persona_ids>(global::Soenneker.Apollo.OpenApiClient.Models.CreateATask200ResponseTask_persona_ids.CreateFromDiscriminatorValue)?.AsList(); } },
                { "playbook_id", n => { PlaybookId = n.GetObjectValue<global::Soenneker.Apollo.OpenApiClient.Models.CreateATask200ResponseTaskPlaybookId>(global::Soenneker.Apollo.OpenApiClient.Models.CreateATask200ResponseTaskPlaybookId.CreateFromDiscriminatorValue); } },
                { "playbook_step_ids", n => { PlaybookStepIds = n.GetCollectionOfObjectValues<global::Soenneker.Apollo.OpenApiClient.Models.CreateATask200ResponseTask_playbook_step_ids>(global::Soenneker.Apollo.OpenApiClient.Models.CreateATask200ResponseTask_playbook_step_ids.CreateFromDiscriminatorValue)?.AsList(); } },
                { "priority", n => { Priority = n.GetStringValue(); } },
                { "rule_config_id", n => { RuleConfigId = n.GetObjectValue<global::Soenneker.Apollo.OpenApiClient.Models.CreateATask200ResponseTaskRuleConfigId>(global::Soenneker.Apollo.OpenApiClient.Models.CreateATask200ResponseTaskRuleConfigId.CreateFromDiscriminatorValue); } },
                { "salesforce_id", n => { SalesforceId = n.GetObjectValue<global::Soenneker.Apollo.OpenApiClient.Models.CreateATask200ResponseTaskSalesforceId>(global::Soenneker.Apollo.OpenApiClient.Models.CreateATask200ResponseTaskSalesforceId.CreateFromDiscriminatorValue); } },
                { "salesforce_type", n => { SalesforceType = n.GetObjectValue<global::Soenneker.Apollo.OpenApiClient.Models.CreateATask200ResponseTaskSalesforceType>(global::Soenneker.Apollo.OpenApiClient.Models.CreateATask200ResponseTaskSalesforceType.CreateFromDiscriminatorValue); } },
                { "skipped_at", n => { SkippedAt = n.GetObjectValue<global::Soenneker.Apollo.OpenApiClient.Models.CreateATask200ResponseTaskSkippedAt>(global::Soenneker.Apollo.OpenApiClient.Models.CreateATask200ResponseTaskSkippedAt.CreateFromDiscriminatorValue); } },
                { "starred_by_user_ids", n => { StarredByUserIds = n.GetCollectionOfObjectValues<global::Soenneker.Apollo.OpenApiClient.Models.CreateATask200ResponseTask_starred_by_user_ids>(global::Soenneker.Apollo.OpenApiClient.Models.CreateATask200ResponseTask_starred_by_user_ids.CreateFromDiscriminatorValue)?.AsList(); } },
                { "status", n => { Status = n.GetStringValue(); } },
                { "subject", n => { Subject = n.GetObjectValue<global::Soenneker.Apollo.OpenApiClient.Models.CreateATask200ResponseTaskSubject>(global::Soenneker.Apollo.OpenApiClient.Models.CreateATask200ResponseTaskSubject.CreateFromDiscriminatorValue); } },
                { "title", n => { Title = n.GetStringValue(); } },
                { "type", n => { Type = n.GetStringValue(); } },
                { "user_id", n => { UserId = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Apollo.OpenApiClient.Models.CreateATask200ResponseTaskAccountId>("account_id", AccountId);
            writer.WriteObjectValue<global::Soenneker.Apollo.OpenApiClient.Models.CreateATask200ResponseTaskAnswered>("answered", Answered);
            writer.WriteObjectValue<global::Soenneker.Apollo.OpenApiClient.Models.CreateATask200ResponseTaskCompletedAt>("completed_at", CompletedAt);
            writer.WriteObjectValue<global::Soenneker.Apollo.OpenApiClient.Models.CreateATask200ResponseTaskContactId>("contact_id", ContactId);
            writer.WriteStringValue("created_at", CreatedAt);
            writer.WriteObjectValue<global::Soenneker.Apollo.OpenApiClient.Models.CreateATask200ResponseTaskCreatedFrom>("created_from", CreatedFrom);
            writer.WriteStringValue("creator_id", CreatorId);
            writer.WriteStringValue("due_at", DueAt);
            writer.WriteObjectValue<global::Soenneker.Apollo.OpenApiClient.Models.CreateATask200ResponseTaskEmailerCampaignId>("emailer_campaign_id", EmailerCampaignId);
            writer.WriteObjectValue<global::Soenneker.Apollo.OpenApiClient.Models.CreateATask200ResponseTaskHubspotId>("hubspot_id", HubspotId);
            writer.WriteStringValue("id", Id);
            writer.WriteObjectValue<global::Soenneker.Apollo.OpenApiClient.Models.CreateATask200ResponseTaskNeedsPlaybookAutoprospecting>("needs_playbook_autoprospecting", NeedsPlaybookAutoprospecting);
            writer.WriteObjectValue<global::Soenneker.Apollo.OpenApiClient.Models.CreateATask200ResponseTaskNote>("note", Note);
            writer.WriteObjectValue<global::Soenneker.Apollo.OpenApiClient.Models.CreateATask200ResponseTaskOpportunity>("opportunity", Opportunity);
            writer.WriteStringValue("opportunity_id", OpportunityId);
            writer.WriteObjectValue<global::Soenneker.Apollo.OpenApiClient.Models.CreateATask200ResponseTaskOrganizationId>("organization_id", OrganizationId);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Apollo.OpenApiClient.Models.CreateATask200ResponseTask_persona_ids>("persona_ids", PersonaIds);
            writer.WriteObjectValue<global::Soenneker.Apollo.OpenApiClient.Models.CreateATask200ResponseTaskPersonId>("person_id", PersonId);
            writer.WriteObjectValue<global::Soenneker.Apollo.OpenApiClient.Models.CreateATask200ResponseTaskPlaybookId>("playbook_id", PlaybookId);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Apollo.OpenApiClient.Models.CreateATask200ResponseTask_playbook_step_ids>("playbook_step_ids", PlaybookStepIds);
            writer.WriteStringValue("priority", Priority);
            writer.WriteObjectValue<global::Soenneker.Apollo.OpenApiClient.Models.CreateATask200ResponseTaskRuleConfigId>("rule_config_id", RuleConfigId);
            writer.WriteObjectValue<global::Soenneker.Apollo.OpenApiClient.Models.CreateATask200ResponseTaskSalesforceId>("salesforce_id", SalesforceId);
            writer.WriteObjectValue<global::Soenneker.Apollo.OpenApiClient.Models.CreateATask200ResponseTaskSalesforceType>("salesforce_type", SalesforceType);
            writer.WriteObjectValue<global::Soenneker.Apollo.OpenApiClient.Models.CreateATask200ResponseTaskSkippedAt>("skipped_at", SkippedAt);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Apollo.OpenApiClient.Models.CreateATask200ResponseTask_starred_by_user_ids>("starred_by_user_ids", StarredByUserIds);
            writer.WriteStringValue("status", Status);
            writer.WriteObjectValue<global::Soenneker.Apollo.OpenApiClient.Models.CreateATask200ResponseTaskSubject>("subject", Subject);
            writer.WriteStringValue("title", Title);
            writer.WriteStringValue("type", Type);
            writer.WriteStringValue("user_id", UserId);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
