// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Apollo.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum CreateSequence200ResponseEmailerCampaignSharingPermissionVisibility
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "restricted")]
        #pragma warning disable CS1591
        Restricted,
        #pragma warning restore CS1591
        [EnumMember(Value = "everyone")]
        #pragma warning disable CS1591
        Everyone,
        #pragma warning restore CS1591
    }
}
