// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Apollo.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class CreateAnEmailDraft200ResponseEmailerMessageSendFrom : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The contact_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Apollo.OpenApiClient.Models.CreateAnEmailDraft200ResponseEmailerMessageSendFromContactId? ContactId { get; set; }
#nullable restore
#else
        public global::Soenneker.Apollo.OpenApiClient.Models.CreateAnEmailDraft200ResponseEmailerMessageSendFromContactId ContactId { get; set; }
#endif
        /// <summary>The email property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Email { get; set; }
#nullable restore
#else
        public string Email { get; set; }
#endif
        /// <summary>The raw_name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Apollo.OpenApiClient.Models.CreateAnEmailDraft200ResponseEmailerMessageSendFromRawName? RawName { get; set; }
#nullable restore
#else
        public global::Soenneker.Apollo.OpenApiClient.Models.CreateAnEmailDraft200ResponseEmailerMessageSendFromRawName RawName { get; set; }
#endif
        /// <summary>The recipient_type_cd property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Apollo.OpenApiClient.Models.CreateAnEmailDraft200ResponseEmailerMessageSendFromRecipientTypeCd? RecipientTypeCd { get; set; }
#nullable restore
#else
        public global::Soenneker.Apollo.OpenApiClient.Models.CreateAnEmailDraft200ResponseEmailerMessageSendFromRecipientTypeCd RecipientTypeCd { get; set; }
#endif
        /// <summary>The user_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? UserId { get; set; }
#nullable restore
#else
        public string UserId { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Apollo.OpenApiClient.Models.CreateAnEmailDraft200ResponseEmailerMessageSendFrom"/> and sets the default values.
        /// </summary>
        public CreateAnEmailDraft200ResponseEmailerMessageSendFrom()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Apollo.OpenApiClient.Models.CreateAnEmailDraft200ResponseEmailerMessageSendFrom"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Apollo.OpenApiClient.Models.CreateAnEmailDraft200ResponseEmailerMessageSendFrom CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Apollo.OpenApiClient.Models.CreateAnEmailDraft200ResponseEmailerMessageSendFrom();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "contact_id", n => { ContactId = n.GetObjectValue<global::Soenneker.Apollo.OpenApiClient.Models.CreateAnEmailDraft200ResponseEmailerMessageSendFromContactId>(global::Soenneker.Apollo.OpenApiClient.Models.CreateAnEmailDraft200ResponseEmailerMessageSendFromContactId.CreateFromDiscriminatorValue); } },
                { "email", n => { Email = n.GetStringValue(); } },
                { "raw_name", n => { RawName = n.GetObjectValue<global::Soenneker.Apollo.OpenApiClient.Models.CreateAnEmailDraft200ResponseEmailerMessageSendFromRawName>(global::Soenneker.Apollo.OpenApiClient.Models.CreateAnEmailDraft200ResponseEmailerMessageSendFromRawName.CreateFromDiscriminatorValue); } },
                { "recipient_type_cd", n => { RecipientTypeCd = n.GetObjectValue<global::Soenneker.Apollo.OpenApiClient.Models.CreateAnEmailDraft200ResponseEmailerMessageSendFromRecipientTypeCd>(global::Soenneker.Apollo.OpenApiClient.Models.CreateAnEmailDraft200ResponseEmailerMessageSendFromRecipientTypeCd.CreateFromDiscriminatorValue); } },
                { "user_id", n => { UserId = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Apollo.OpenApiClient.Models.CreateAnEmailDraft200ResponseEmailerMessageSendFromContactId>("contact_id", ContactId);
            writer.WriteStringValue("email", Email);
            writer.WriteObjectValue<global::Soenneker.Apollo.OpenApiClient.Models.CreateAnEmailDraft200ResponseEmailerMessageSendFromRawName>("raw_name", RawName);
            writer.WriteObjectValue<global::Soenneker.Apollo.OpenApiClient.Models.CreateAnEmailDraft200ResponseEmailerMessageSendFromRecipientTypeCd>("recipient_type_cd", RecipientTypeCd);
            writer.WriteStringValue("user_id", UserId);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
