// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Apollo.OpenApiClient.Models
{
    /// <summary>Returned when the Assistant is awaiting input.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum ElicitationRequiredErrorType
    {
        [EnumMember(Value = "elicitation_required")]
        #pragma warning disable CS1591
        ElicitationRequired,
        #pragma warning restore CS1591
    }
}
