// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Apollo.OpenApiClient.Models
{
    /// <summary>
    /// Machine-readable detail for an error that uses the new format, returned alongside the endpoint&apos;s existing error fields. The legacy error fields at the root level (`error`, `error_code`, `message`, etc) are removed on 2027-02-16, after which `error_details` is the only error payload. Some errors already return `error_details` on its own.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ErrorDetails : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Stable identifier in the form `DOMAIN.CATEGORY.REASON`. Branch on this value; the human-readable `message` can change.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Code { get; set; }
#nullable restore
#else
        public string Code { get; set; }
#endif
        /// <summary>Values from your request that explain the refusal. Each entry is an object rather than a bare value, so read `context.&lt;key&gt;.value`. Absent when the error needs no context.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Apollo.OpenApiClient.Models.ErrorDetailsContextProperty? Context { get; set; }
#nullable restore
#else
        public global::Soenneker.Apollo.OpenApiClient.Models.ErrorDetailsContextProperty Context { get; set; }
#endif
        /// <summary>Human-readable explanation of what went wrong.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Message { get; set; }
#nullable restore
#else
        public string Message { get; set; }
#endif
        /// <summary>Ordered, actionable next steps. Each entry carries a `label`, and where relevant the `parameter`, `header`, or `url` it refers to.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Apollo.OpenApiClient.Models.ErrorDetailsSuggestionsItem>? Suggestions { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Apollo.OpenApiClient.Models.ErrorDetailsSuggestionsItem> Suggestions { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Apollo.OpenApiClient.Models.ErrorDetails"/> and sets the default values.
        /// </summary>
        public ErrorDetails()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Apollo.OpenApiClient.Models.ErrorDetails"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Apollo.OpenApiClient.Models.ErrorDetails CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Apollo.OpenApiClient.Models.ErrorDetails();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "code", n => { Code = n.GetStringValue(); } },
                { "context", n => { Context = n.GetObjectValue<global::Soenneker.Apollo.OpenApiClient.Models.ErrorDetailsContextProperty>(global::Soenneker.Apollo.OpenApiClient.Models.ErrorDetailsContextProperty.CreateFromDiscriminatorValue); } },
                { "message", n => { Message = n.GetStringValue(); } },
                { "suggestions", n => { Suggestions = n.GetCollectionOfObjectValues<global::Soenneker.Apollo.OpenApiClient.Models.ErrorDetailsSuggestionsItem>(global::Soenneker.Apollo.OpenApiClient.Models.ErrorDetailsSuggestionsItem.CreateFromDiscriminatorValue)?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("code", Code);
            writer.WriteObjectValue<global::Soenneker.Apollo.OpenApiClient.Models.ErrorDetailsContextProperty>("context", Context);
            writer.WriteStringValue("message", Message);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Apollo.OpenApiClient.Models.ErrorDetailsSuggestionsItem>("suggestions", Suggestions);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
