// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Apollo.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class GetAListOfNotes200ResponseNotesItem : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The ID of the associated account.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AccountId { get; set; }
#nullable restore
#else
        public string AccountId { get; set; }
#endif
        /// <summary>Array of associated account IDs.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? AccountIds { get; set; }
#nullable restore
#else
        public List<string> AccountIds { get; set; }
#endif
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Array of associated calendar event IDs.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? CalendarEventIds { get; set; }
#nullable restore
#else
        public List<string> CalendarEventIds { get; set; }
#endif
        /// <summary>The ID of the associated contact.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ContactId { get; set; }
#nullable restore
#else
        public string ContactId { get; set; }
#endif
        /// <summary>Array of associated contact IDs.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? ContactIds { get; set; }
#nullable restore
#else
        public List<string> ContactIds { get; set; }
#endif
        /// <summary>The content of the note.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Content { get; set; }
#nullable restore
#else
        public string Content { get; set; }
#endif
        /// <summary>The ID of the associated conversation.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ConversationId { get; set; }
#nullable restore
#else
        public string ConversationId { get; set; }
#endif
        /// <summary>Array of associated conversation IDs.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? ConversationIds { get; set; }
#nullable restore
#else
        public List<string> ConversationIds { get; set; }
#endif
        /// <summary>The timestamp when the note was created.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CreatedAt { get; set; }
#nullable restore
#else
        public string CreatedAt { get; set; }
#endif
        /// <summary>Array of associated CRM note records.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Apollo.OpenApiClient.Models.GetAListOfNotes200ResponseNotesItem_crm_notes>? CrmNotes { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Apollo.OpenApiClient.Models.GetAListOfNotes200ResponseNotesItem_crm_notes> CrmNotes { get; set; }
#endif
        /// <summary>The unique identifier of the note.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>Whether this note is an org chart note.</summary>
        public bool? IsOrgChartNote { get; set; }
        /// <summary>The ID of the associated opportunity.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? OpportunityId { get; set; }
#nullable restore
#else
        public string OpportunityId { get; set; }
#endif
        /// <summary>Array of associated opportunity IDs.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? OpportunityIds { get; set; }
#nullable restore
#else
        public List<string> OpportunityIds { get; set; }
#endif
        /// <summary>Whether the note is pinned to the top.</summary>
        public bool? PinnedToTop { get; set; }
        /// <summary>Whether this is a system-generated note.</summary>
        public bool? System { get; set; }
        /// <summary>The timestamp when the note was last updated.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? UpdatedAt { get; set; }
#nullable restore
#else
        public string UpdatedAt { get; set; }
#endif
        /// <summary>The ID of the user who created the note.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? UserId { get; set; }
#nullable restore
#else
        public string UserId { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Apollo.OpenApiClient.Models.GetAListOfNotes200ResponseNotesItem"/> and sets the default values.
        /// </summary>
        public GetAListOfNotes200ResponseNotesItem()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Apollo.OpenApiClient.Models.GetAListOfNotes200ResponseNotesItem"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Apollo.OpenApiClient.Models.GetAListOfNotes200ResponseNotesItem CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Apollo.OpenApiClient.Models.GetAListOfNotes200ResponseNotesItem();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "account_id", n => { AccountId = n.GetStringValue(); } },
                { "account_ids", n => { AccountIds = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "calendar_event_ids", n => { CalendarEventIds = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "contact_id", n => { ContactId = n.GetStringValue(); } },
                { "contact_ids", n => { ContactIds = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "content", n => { Content = n.GetStringValue(); } },
                { "conversation_id", n => { ConversationId = n.GetStringValue(); } },
                { "conversation_ids", n => { ConversationIds = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "created_at", n => { CreatedAt = n.GetStringValue(); } },
                { "crm_notes", n => { CrmNotes = n.GetCollectionOfObjectValues<global::Soenneker.Apollo.OpenApiClient.Models.GetAListOfNotes200ResponseNotesItem_crm_notes>(global::Soenneker.Apollo.OpenApiClient.Models.GetAListOfNotes200ResponseNotesItem_crm_notes.CreateFromDiscriminatorValue)?.AsList(); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "is_org_chart_note", n => { IsOrgChartNote = n.GetBoolValue(); } },
                { "opportunity_id", n => { OpportunityId = n.GetStringValue(); } },
                { "opportunity_ids", n => { OpportunityIds = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "pinned_to_top", n => { PinnedToTop = n.GetBoolValue(); } },
                { "system", n => { System = n.GetBoolValue(); } },
                { "updated_at", n => { UpdatedAt = n.GetStringValue(); } },
                { "user_id", n => { UserId = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("account_id", AccountId);
            writer.WriteCollectionOfPrimitiveValues<string>("account_ids", AccountIds);
            writer.WriteCollectionOfPrimitiveValues<string>("calendar_event_ids", CalendarEventIds);
            writer.WriteStringValue("contact_id", ContactId);
            writer.WriteCollectionOfPrimitiveValues<string>("contact_ids", ContactIds);
            writer.WriteStringValue("content", Content);
            writer.WriteStringValue("conversation_id", ConversationId);
            writer.WriteCollectionOfPrimitiveValues<string>("conversation_ids", ConversationIds);
            writer.WriteStringValue("created_at", CreatedAt);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Apollo.OpenApiClient.Models.GetAListOfNotes200ResponseNotesItem_crm_notes>("crm_notes", CrmNotes);
            writer.WriteStringValue("id", Id);
            writer.WriteBoolValue("is_org_chart_note", IsOrgChartNote);
            writer.WriteStringValue("opportunity_id", OpportunityId);
            writer.WriteCollectionOfPrimitiveValues<string>("opportunity_ids", OpportunityIds);
            writer.WriteBoolValue("pinned_to_top", PinnedToTop);
            writer.WriteBoolValue("system", System);
            writer.WriteStringValue("updated_at", UpdatedAt);
            writer.WriteStringValue("user_id", UserId);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
