// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Apollo.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class GetAccountsId200ResponseAccountContactCampaignStatusTally : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The active property</summary>
        public long? Active { get; set; }
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The bounced property</summary>
        public long? Bounced { get; set; }
        /// <summary>The finished property</summary>
        public long? Finished { get; set; }
        /// <summary>The not_sent property</summary>
        public long? NotSent { get; set; }
        /// <summary>The paused property</summary>
        public long? Paused { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Apollo.OpenApiClient.Models.GetAccountsId200ResponseAccountContactCampaignStatusTally"/> and sets the default values.
        /// </summary>
        public GetAccountsId200ResponseAccountContactCampaignStatusTally()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Apollo.OpenApiClient.Models.GetAccountsId200ResponseAccountContactCampaignStatusTally"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Apollo.OpenApiClient.Models.GetAccountsId200ResponseAccountContactCampaignStatusTally CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Apollo.OpenApiClient.Models.GetAccountsId200ResponseAccountContactCampaignStatusTally();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "active", n => { Active = n.GetLongValue(); } },
                { "bounced", n => { Bounced = n.GetLongValue(); } },
                { "finished", n => { Finished = n.GetLongValue(); } },
                { "not_sent", n => { NotSent = n.GetLongValue(); } },
                { "paused", n => { Paused = n.GetLongValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteLongValue("active", Active);
            writer.WriteLongValue("bounced", Bounced);
            writer.WriteLongValue("finished", Finished);
            writer.WriteLongValue("not_sent", NotSent);
            writer.WriteLongValue("paused", Paused);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
