// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Apollo.OpenApiClient.Models
{
    /// <summary>Type of conversation.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum GetConversationsInfo200ResponseConversationType
    {
        [EnumMember(Value = "video_conference")]
        #pragma warning disable CS1591
        VideoConference,
        #pragma warning restore CS1591
        [EnumMember(Value = "phone_call")]
        #pragma warning disable CS1591
        PhoneCall,
        #pragma warning restore CS1591
    }
}
