// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Apollo.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class GetEmailContent200ResponseEmailerMessagesItem : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The body of the email, in the format given by `body_format`. If Apollo has no stored body for the email, this is `null` when `body_format` is `html`, and an empty string when `body_format` is `plain`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Body { get; set; }
#nullable restore
#else
        public string Body { get; set; }
#endif
        /// <summary>The format of the `body` value. This matches the `body_format` that Apollo applied to your request.</summary>
        public global::Soenneker.Apollo.OpenApiClient.Models.GetEmailContent200ResponseEmailerMessagesItemBodyFormat? BodyFormat { get; set; }
        /// <summary>The Apollo ID of the email.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>The recipients of the email.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Apollo.OpenApiClient.Models.GetEmailContent200ResponseEmailerMessagesItemRecipientsItem>? Recipients { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Apollo.OpenApiClient.Models.GetEmailContent200ResponseEmailerMessagesItemRecipientsItem> Recipients { get; set; }
#endif
        /// <summary>The ISO 8601 timestamp for when Apollo finished sending the email. This is `null` if no send-completion time was recorded for the email.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SentAt { get; set; }
#nullable restore
#else
        public string SentAt { get; set; }
#endif
        /// <summary>The send status of the email. This is always `completed`, because the endpoint only returns emails that Apollo has finished sending.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Status { get; set; }
#nullable restore
#else
        public string Status { get; set; }
#endif
        /// <summary>The subject line of the email. This is `null` if the email has no subject line.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Subject { get; set; }
#nullable restore
#else
        public string Subject { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Apollo.OpenApiClient.Models.GetEmailContent200ResponseEmailerMessagesItem"/> and sets the default values.
        /// </summary>
        public GetEmailContent200ResponseEmailerMessagesItem()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Apollo.OpenApiClient.Models.GetEmailContent200ResponseEmailerMessagesItem"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Apollo.OpenApiClient.Models.GetEmailContent200ResponseEmailerMessagesItem CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Apollo.OpenApiClient.Models.GetEmailContent200ResponseEmailerMessagesItem();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "body", n => { Body = n.GetStringValue(); } },
                { "body_format", n => { BodyFormat = n.GetEnumValue<global::Soenneker.Apollo.OpenApiClient.Models.GetEmailContent200ResponseEmailerMessagesItemBodyFormat>(); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "recipients", n => { Recipients = n.GetCollectionOfObjectValues<global::Soenneker.Apollo.OpenApiClient.Models.GetEmailContent200ResponseEmailerMessagesItemRecipientsItem>(global::Soenneker.Apollo.OpenApiClient.Models.GetEmailContent200ResponseEmailerMessagesItemRecipientsItem.CreateFromDiscriminatorValue)?.AsList(); } },
                { "sent_at", n => { SentAt = n.GetStringValue(); } },
                { "status", n => { Status = n.GetStringValue(); } },
                { "subject", n => { Subject = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("body", Body);
            writer.WriteEnumValue<global::Soenneker.Apollo.OpenApiClient.Models.GetEmailContent200ResponseEmailerMessagesItemBodyFormat>("body_format", BodyFormat);
            writer.WriteStringValue("id", Id);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Apollo.OpenApiClient.Models.GetEmailContent200ResponseEmailerMessagesItemRecipientsItem>("recipients", Recipients);
            writer.WriteStringValue("sent_at", SentAt);
            writer.WriteStringValue("status", Status);
            writer.WriteStringValue("subject", Subject);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
