// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Apollo.OpenApiClient.Models
{
    /// <summary>The recipient type.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum GetEmailContent200ResponseEmailerMessagesItemRecipientsItemType
    {
        [EnumMember(Value = "to")]
        #pragma warning disable CS1591
        To,
        #pragma warning restore CS1591
        [EnumMember(Value = "cc")]
        #pragma warning disable CS1591
        Cc,
        #pragma warning restore CS1591
        [EnumMember(Value = "bcc")]
        #pragma warning disable CS1591
        Bcc,
        #pragma warning restore CS1591
    }
}
