// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Apollo.OpenApiClient.Models
{
    /// <summary>The format of the `body` value. This matches the `body_format` that Apollo applied to your request.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum GetEmailContent200ResponseEmailerMessagesItemBodyFormat
    {
        [EnumMember(Value = "plain")]
        #pragma warning disable CS1591
        Plain,
        #pragma warning restore CS1591
        [EnumMember(Value = "html")]
        #pragma warning disable CS1591
        Html,
        #pragma warning restore CS1591
    }
}
