// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Apollo.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class GetOrganizationsId200ResponseOrganizationAccount : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The account_playbook_statuses property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Apollo.OpenApiClient.Models.GetOrganizationsId200ResponseOrganizationAccountAccountPlaybookStatusesItem>? AccountPlaybookStatuses { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Apollo.OpenApiClient.Models.GetOrganizationsId200ResponseOrganizationAccountAccountPlaybookStatusesItem> AccountPlaybookStatuses { get; set; }
#endif
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The created_at property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CreatedAt { get; set; }
#nullable restore
#else
        public string CreatedAt { get; set; }
#endif
        /// <summary>The crm_record_url property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public UntypedNode? CrmRecordUrl { get; set; }
#nullable restore
#else
        public UntypedNode CrmRecordUrl { get; set; }
#endif
        /// <summary>The custom_field_errors property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Apollo.OpenApiClient.Models.GetOrganizationsId200ResponseOrganizationAccountCustomFieldErrors? CustomFieldErrors { get; set; }
#nullable restore
#else
        public global::Soenneker.Apollo.OpenApiClient.Models.GetOrganizationsId200ResponseOrganizationAccountCustomFieldErrors CustomFieldErrors { get; set; }
#endif
        /// <summary>The domain property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Domain { get; set; }
#nullable restore
#else
        public string Domain { get; set; }
#endif
        /// <summary>The existence_level property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ExistenceLevel { get; set; }
#nullable restore
#else
        public string ExistenceLevel { get; set; }
#endif
        /// <summary>The generic_org_insights property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public UntypedNode? GenericOrgInsights { get; set; }
#nullable restore
#else
        public UntypedNode GenericOrgInsights { get; set; }
#endif
        /// <summary>The has_intent_signal_account property</summary>
        public bool? HasIntentSignalAccount { get; set; }
        /// <summary>The id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>The intent_signal_account property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Apollo.OpenApiClient.Models.GetOrganizationsId200ResponseOrganizationAccountIntentSignalAccount? IntentSignalAccount { get; set; }
#nullable restore
#else
        public global::Soenneker.Apollo.OpenApiClient.Models.GetOrganizationsId200ResponseOrganizationAccountIntentSignalAccount IntentSignalAccount { get; set; }
#endif
        /// <summary>The label_ids property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Apollo.OpenApiClient.Models.GetOrganizationsId200ResponseOrganizationAccountLabelIdsItem>? LabelIds { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Apollo.OpenApiClient.Models.GetOrganizationsId200ResponseOrganizationAccountLabelIdsItem> LabelIds { get; set; }
#endif
        /// <summary>The modality property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Modality { get; set; }
#nullable restore
#else
        public string Modality { get; set; }
#endif
        /// <summary>The name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>The organization_headcount_six_month_growth property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public UntypedNode? OrganizationHeadcountSixMonthGrowth { get; set; }
#nullable restore
#else
        public UntypedNode OrganizationHeadcountSixMonthGrowth { get; set; }
#endif
        /// <summary>The organization_headcount_twelve_month_growth property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public UntypedNode? OrganizationHeadcountTwelveMonthGrowth { get; set; }
#nullable restore
#else
        public UntypedNode OrganizationHeadcountTwelveMonthGrowth { get; set; }
#endif
        /// <summary>The organization_headcount_twenty_four_month_growth property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public UntypedNode? OrganizationHeadcountTwentyFourMonthGrowth { get; set; }
#nullable restore
#else
        public UntypedNode OrganizationHeadcountTwentyFourMonthGrowth { get; set; }
#endif
        /// <summary>The organization_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? OrganizationId { get; set; }
#nullable restore
#else
        public string OrganizationId { get; set; }
#endif
        /// <summary>The original_source property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? OriginalSource { get; set; }
#nullable restore
#else
        public string OriginalSource { get; set; }
#endif
        /// <summary>The owner_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? OwnerId { get; set; }
#nullable restore
#else
        public string OwnerId { get; set; }
#endif
        /// <summary>The phone property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Phone { get; set; }
#nullable restore
#else
        public string Phone { get; set; }
#endif
        /// <summary>The phone_status property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PhoneStatus { get; set; }
#nullable restore
#else
        public string PhoneStatus { get; set; }
#endif
        /// <summary>The sanitized_phone property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SanitizedPhone { get; set; }
#nullable restore
#else
        public string SanitizedPhone { get; set; }
#endif
        /// <summary>The show_intent property</summary>
        public bool? ShowIntent { get; set; }
        /// <summary>The source property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Source { get; set; }
#nullable restore
#else
        public string Source { get; set; }
#endif
        /// <summary>The source_display_name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SourceDisplayName { get; set; }
#nullable restore
#else
        public string SourceDisplayName { get; set; }
#endif
        /// <summary>The team_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TeamId { get; set; }
#nullable restore
#else
        public string TeamId { get; set; }
#endif
        /// <summary>The typed_custom_fields property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Apollo.OpenApiClient.Models.GetOrganizationsId200ResponseOrganizationAccountTypedCustomFields? TypedCustomFields { get; set; }
#nullable restore
#else
        public global::Soenneker.Apollo.OpenApiClient.Models.GetOrganizationsId200ResponseOrganizationAccountTypedCustomFields TypedCustomFields { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Apollo.OpenApiClient.Models.GetOrganizationsId200ResponseOrganizationAccount"/> and sets the default values.
        /// </summary>
        public GetOrganizationsId200ResponseOrganizationAccount()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Apollo.OpenApiClient.Models.GetOrganizationsId200ResponseOrganizationAccount"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Apollo.OpenApiClient.Models.GetOrganizationsId200ResponseOrganizationAccount CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Apollo.OpenApiClient.Models.GetOrganizationsId200ResponseOrganizationAccount();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "account_playbook_statuses", n => { AccountPlaybookStatuses = n.GetCollectionOfObjectValues<global::Soenneker.Apollo.OpenApiClient.Models.GetOrganizationsId200ResponseOrganizationAccountAccountPlaybookStatusesItem>(global::Soenneker.Apollo.OpenApiClient.Models.GetOrganizationsId200ResponseOrganizationAccountAccountPlaybookStatusesItem.CreateFromDiscriminatorValue)?.AsList(); } },
                { "created_at", n => { CreatedAt = n.GetStringValue(); } },
                { "crm_record_url", n => { CrmRecordUrl = n.GetObjectValue<UntypedNode>(UntypedNode.CreateFromDiscriminatorValue); } },
                { "custom_field_errors", n => { CustomFieldErrors = n.GetObjectValue<global::Soenneker.Apollo.OpenApiClient.Models.GetOrganizationsId200ResponseOrganizationAccountCustomFieldErrors>(global::Soenneker.Apollo.OpenApiClient.Models.GetOrganizationsId200ResponseOrganizationAccountCustomFieldErrors.CreateFromDiscriminatorValue); } },
                { "domain", n => { Domain = n.GetStringValue(); } },
                { "existence_level", n => { ExistenceLevel = n.GetStringValue(); } },
                { "generic_org_insights", n => { GenericOrgInsights = n.GetObjectValue<UntypedNode>(UntypedNode.CreateFromDiscriminatorValue); } },
                { "has_intent_signal_account", n => { HasIntentSignalAccount = n.GetBoolValue(); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "intent_signal_account", n => { IntentSignalAccount = n.GetObjectValue<global::Soenneker.Apollo.OpenApiClient.Models.GetOrganizationsId200ResponseOrganizationAccountIntentSignalAccount>(global::Soenneker.Apollo.OpenApiClient.Models.GetOrganizationsId200ResponseOrganizationAccountIntentSignalAccount.CreateFromDiscriminatorValue); } },
                { "label_ids", n => { LabelIds = n.GetCollectionOfObjectValues<global::Soenneker.Apollo.OpenApiClient.Models.GetOrganizationsId200ResponseOrganizationAccountLabelIdsItem>(global::Soenneker.Apollo.OpenApiClient.Models.GetOrganizationsId200ResponseOrganizationAccountLabelIdsItem.CreateFromDiscriminatorValue)?.AsList(); } },
                { "modality", n => { Modality = n.GetStringValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "organization_headcount_six_month_growth", n => { OrganizationHeadcountSixMonthGrowth = n.GetObjectValue<UntypedNode>(UntypedNode.CreateFromDiscriminatorValue); } },
                { "organization_headcount_twelve_month_growth", n => { OrganizationHeadcountTwelveMonthGrowth = n.GetObjectValue<UntypedNode>(UntypedNode.CreateFromDiscriminatorValue); } },
                { "organization_headcount_twenty_four_month_growth", n => { OrganizationHeadcountTwentyFourMonthGrowth = n.GetObjectValue<UntypedNode>(UntypedNode.CreateFromDiscriminatorValue); } },
                { "organization_id", n => { OrganizationId = n.GetStringValue(); } },
                { "original_source", n => { OriginalSource = n.GetStringValue(); } },
                { "owner_id", n => { OwnerId = n.GetStringValue(); } },
                { "phone", n => { Phone = n.GetStringValue(); } },
                { "phone_status", n => { PhoneStatus = n.GetStringValue(); } },
                { "sanitized_phone", n => { SanitizedPhone = n.GetStringValue(); } },
                { "show_intent", n => { ShowIntent = n.GetBoolValue(); } },
                { "source", n => { Source = n.GetStringValue(); } },
                { "source_display_name", n => { SourceDisplayName = n.GetStringValue(); } },
                { "team_id", n => { TeamId = n.GetStringValue(); } },
                { "typed_custom_fields", n => { TypedCustomFields = n.GetObjectValue<global::Soenneker.Apollo.OpenApiClient.Models.GetOrganizationsId200ResponseOrganizationAccountTypedCustomFields>(global::Soenneker.Apollo.OpenApiClient.Models.GetOrganizationsId200ResponseOrganizationAccountTypedCustomFields.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::Soenneker.Apollo.OpenApiClient.Models.GetOrganizationsId200ResponseOrganizationAccountAccountPlaybookStatusesItem>("account_playbook_statuses", AccountPlaybookStatuses);
            writer.WriteStringValue("created_at", CreatedAt);
            writer.WriteObjectValue<UntypedNode>("crm_record_url", CrmRecordUrl);
            writer.WriteObjectValue<global::Soenneker.Apollo.OpenApiClient.Models.GetOrganizationsId200ResponseOrganizationAccountCustomFieldErrors>("custom_field_errors", CustomFieldErrors);
            writer.WriteStringValue("domain", Domain);
            writer.WriteStringValue("existence_level", ExistenceLevel);
            writer.WriteObjectValue<UntypedNode>("generic_org_insights", GenericOrgInsights);
            writer.WriteBoolValue("has_intent_signal_account", HasIntentSignalAccount);
            writer.WriteStringValue("id", Id);
            writer.WriteObjectValue<global::Soenneker.Apollo.OpenApiClient.Models.GetOrganizationsId200ResponseOrganizationAccountIntentSignalAccount>("intent_signal_account", IntentSignalAccount);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Apollo.OpenApiClient.Models.GetOrganizationsId200ResponseOrganizationAccountLabelIdsItem>("label_ids", LabelIds);
            writer.WriteStringValue("modality", Modality);
            writer.WriteStringValue("name", Name);
            writer.WriteObjectValue<UntypedNode>("organization_headcount_six_month_growth", OrganizationHeadcountSixMonthGrowth);
            writer.WriteObjectValue<UntypedNode>("organization_headcount_twelve_month_growth", OrganizationHeadcountTwelveMonthGrowth);
            writer.WriteObjectValue<UntypedNode>("organization_headcount_twenty_four_month_growth", OrganizationHeadcountTwentyFourMonthGrowth);
            writer.WriteStringValue("organization_id", OrganizationId);
            writer.WriteStringValue("original_source", OriginalSource);
            writer.WriteStringValue("owner_id", OwnerId);
            writer.WriteStringValue("phone", Phone);
            writer.WriteStringValue("phone_status", PhoneStatus);
            writer.WriteStringValue("sanitized_phone", SanitizedPhone);
            writer.WriteBoolValue("show_intent", ShowIntent);
            writer.WriteStringValue("source", Source);
            writer.WriteStringValue("source_display_name", SourceDisplayName);
            writer.WriteStringValue("team_id", TeamId);
            writer.WriteObjectValue<global::Soenneker.Apollo.OpenApiClient.Models.GetOrganizationsId200ResponseOrganizationAccountTypedCustomFields>("typed_custom_fields", TypedCustomFields);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
