// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Apollo.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class GetOrganizationsId200ResponseOrganizationAccountIntentSignalAccountDomainAggregatesItem : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The domain property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Domain { get; set; }
#nullable restore
#else
        public string Domain { get; set; }
#endif
        /// <summary>The first_visit property</summary>
        public long? FirstVisit { get; set; }
        /// <summary>The intent property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Intent { get; set; }
#nullable restore
#else
        public string Intent { get; set; }
#endif
        /// <summary>The intent_score property</summary>
        public long? IntentScore { get; set; }
        /// <summary>The last_visit property</summary>
        public long? LastVisit { get; set; }
        /// <summary>The top_5_paths property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Apollo.OpenApiClient.Models.GetOrganizationsId200ResponseOrganizationAccountIntentSignalAccountDomainAggregatesItemTop5PathsItem>? Top5Paths { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Apollo.OpenApiClient.Models.GetOrganizationsId200ResponseOrganizationAccountIntentSignalAccountDomainAggregatesItemTop5PathsItem> Top5Paths { get; set; }
#endif
        /// <summary>The total_visits property</summary>
        public long? TotalVisits { get; set; }
        /// <summary>The unique_visitors property</summary>
        public long? UniqueVisitors { get; set; }
        /// <summary>The weekly_aggregates property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Apollo.OpenApiClient.Models.GetOrganizationsId200ResponseOrganizationAccountIntentSignalAccountDomainAggregatesItemWeeklyAggregatesItem>? WeeklyAggregates { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Apollo.OpenApiClient.Models.GetOrganizationsId200ResponseOrganizationAccountIntentSignalAccountDomainAggregatesItemWeeklyAggregatesItem> WeeklyAggregates { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Apollo.OpenApiClient.Models.GetOrganizationsId200ResponseOrganizationAccountIntentSignalAccountDomainAggregatesItem"/> and sets the default values.
        /// </summary>
        public GetOrganizationsId200ResponseOrganizationAccountIntentSignalAccountDomainAggregatesItem()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Apollo.OpenApiClient.Models.GetOrganizationsId200ResponseOrganizationAccountIntentSignalAccountDomainAggregatesItem"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Apollo.OpenApiClient.Models.GetOrganizationsId200ResponseOrganizationAccountIntentSignalAccountDomainAggregatesItem CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Apollo.OpenApiClient.Models.GetOrganizationsId200ResponseOrganizationAccountIntentSignalAccountDomainAggregatesItem();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "domain", n => { Domain = n.GetStringValue(); } },
                { "first_visit", n => { FirstVisit = n.GetLongValue(); } },
                { "intent", n => { Intent = n.GetStringValue(); } },
                { "intent_score", n => { IntentScore = n.GetLongValue(); } },
                { "last_visit", n => { LastVisit = n.GetLongValue(); } },
                { "top_5_paths", n => { Top5Paths = n.GetCollectionOfObjectValues<global::Soenneker.Apollo.OpenApiClient.Models.GetOrganizationsId200ResponseOrganizationAccountIntentSignalAccountDomainAggregatesItemTop5PathsItem>(global::Soenneker.Apollo.OpenApiClient.Models.GetOrganizationsId200ResponseOrganizationAccountIntentSignalAccountDomainAggregatesItemTop5PathsItem.CreateFromDiscriminatorValue)?.AsList(); } },
                { "total_visits", n => { TotalVisits = n.GetLongValue(); } },
                { "unique_visitors", n => { UniqueVisitors = n.GetLongValue(); } },
                { "weekly_aggregates", n => { WeeklyAggregates = n.GetCollectionOfObjectValues<global::Soenneker.Apollo.OpenApiClient.Models.GetOrganizationsId200ResponseOrganizationAccountIntentSignalAccountDomainAggregatesItemWeeklyAggregatesItem>(global::Soenneker.Apollo.OpenApiClient.Models.GetOrganizationsId200ResponseOrganizationAccountIntentSignalAccountDomainAggregatesItemWeeklyAggregatesItem.CreateFromDiscriminatorValue)?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("domain", Domain);
            writer.WriteLongValue("first_visit", FirstVisit);
            writer.WriteStringValue("intent", Intent);
            writer.WriteLongValue("intent_score", IntentScore);
            writer.WriteLongValue("last_visit", LastVisit);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Apollo.OpenApiClient.Models.GetOrganizationsId200ResponseOrganizationAccountIntentSignalAccountDomainAggregatesItemTop5PathsItem>("top_5_paths", Top5Paths);
            writer.WriteLongValue("total_visits", TotalVisits);
            writer.WriteLongValue("unique_visitors", UniqueVisitors);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Apollo.OpenApiClient.Models.GetOrganizationsId200ResponseOrganizationAccountIntentSignalAccountDomainAggregatesItemWeeklyAggregatesItem>("weekly_aggregates", WeeklyAggregates);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
