// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Apollo.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class PeopleEnrichment200ResponsePersonOrganization : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The alexa_ranking property</summary>
        public int? AlexaRanking { get; set; }
        /// <summary>The angellist_url property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Apollo.OpenApiClient.Models.PeopleEnrichment200ResponsePersonOrganizationAngellistUrl? AngellistUrl { get; set; }
#nullable restore
#else
        public global::Soenneker.Apollo.OpenApiClient.Models.PeopleEnrichment200ResponsePersonOrganizationAngellistUrl AngellistUrl { get; set; }
#endif
        /// <summary>The annual_revenue property</summary>
        public int? AnnualRevenue { get; set; }
        /// <summary>The annual_revenue_printed property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AnnualRevenuePrinted { get; set; }
#nullable restore
#else
        public string AnnualRevenuePrinted { get; set; }
#endif
        /// <summary>The blog_url property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Apollo.OpenApiClient.Models.PeopleEnrichment200ResponsePersonOrganizationBlogUrl? BlogUrl { get; set; }
#nullable restore
#else
        public global::Soenneker.Apollo.OpenApiClient.Models.PeopleEnrichment200ResponsePersonOrganizationBlogUrl BlogUrl { get; set; }
#endif
        /// <summary>The city property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? City { get; set; }
#nullable restore
#else
        public string City { get; set; }
#endif
        /// <summary>The country property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Country { get; set; }
#nullable restore
#else
        public string Country { get; set; }
#endif
        /// <summary>The crunchbase_url property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Apollo.OpenApiClient.Models.PeopleEnrichment200ResponsePersonOrganizationCrunchbaseUrl? CrunchbaseUrl { get; set; }
#nullable restore
#else
        public global::Soenneker.Apollo.OpenApiClient.Models.PeopleEnrichment200ResponsePersonOrganizationCrunchbaseUrl CrunchbaseUrl { get; set; }
#endif
        /// <summary>The current_technologies property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Apollo.OpenApiClient.Models.PeopleEnrichment200ResponsePersonOrganizationCurrentTechnologiesItem>? CurrentTechnologies { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Apollo.OpenApiClient.Models.PeopleEnrichment200ResponsePersonOrganizationCurrentTechnologiesItem> CurrentTechnologies { get; set; }
#endif
        /// <summary>The estimated_num_employees property</summary>
        public int? EstimatedNumEmployees { get; set; }
        /// <summary>The facebook_url property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? FacebookUrl { get; set; }
#nullable restore
#else
        public string FacebookUrl { get; set; }
#endif
        /// <summary>The founded_year property</summary>
        public int? FoundedYear { get; set; }
        /// <summary>The funding_events property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Apollo.OpenApiClient.Models.PeopleEnrichment200ResponsePersonOrganizationFundingEventsItem>? FundingEvents { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Apollo.OpenApiClient.Models.PeopleEnrichment200ResponsePersonOrganizationFundingEventsItem> FundingEvents { get; set; }
#endif
        /// <summary>The id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>The industries property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? Industries { get; set; }
#nullable restore
#else
        public List<string> Industries { get; set; }
#endif
        /// <summary>The industry property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Industry { get; set; }
#nullable restore
#else
        public string Industry { get; set; }
#endif
        /// <summary>The industry_tag_hash property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Apollo.OpenApiClient.Models.PeopleEnrichment200ResponsePersonOrganizationIndustryTagHash? IndustryTagHash { get; set; }
#nullable restore
#else
        public global::Soenneker.Apollo.OpenApiClient.Models.PeopleEnrichment200ResponsePersonOrganizationIndustryTagHash IndustryTagHash { get; set; }
#endif
        /// <summary>The industry_tag_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? IndustryTagId { get; set; }
#nullable restore
#else
        public string IndustryTagId { get; set; }
#endif
        /// <summary>The keywords property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? Keywords { get; set; }
#nullable restore
#else
        public List<string> Keywords { get; set; }
#endif
        /// <summary>The languages property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Apollo.OpenApiClient.Models.PeopleEnrichment200ResponsePersonOrganization_languages>? Languages { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Apollo.OpenApiClient.Models.PeopleEnrichment200ResponsePersonOrganization_languages> Languages { get; set; }
#endif
        /// <summary>The latest_funding_round_date property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? LatestFundingRoundDate { get; set; }
#nullable restore
#else
        public string LatestFundingRoundDate { get; set; }
#endif
        /// <summary>The latest_funding_stage property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? LatestFundingStage { get; set; }
#nullable restore
#else
        public string LatestFundingStage { get; set; }
#endif
        /// <summary>The linkedin_uid property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? LinkedinUid { get; set; }
#nullable restore
#else
        public string LinkedinUid { get; set; }
#endif
        /// <summary>The linkedin_url property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? LinkedinUrl { get; set; }
#nullable restore
#else
        public string LinkedinUrl { get; set; }
#endif
        /// <summary>The logo_url property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? LogoUrl { get; set; }
#nullable restore
#else
        public string LogoUrl { get; set; }
#endif
        /// <summary>The name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>The num_suborganizations property</summary>
        public int? NumSuborganizations { get; set; }
        /// <summary>The org_chart_removed property</summary>
        public bool? OrgChartRemoved { get; set; }
        /// <summary>The org_chart_root_people_ids property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? OrgChartRootPeopleIds { get; set; }
#nullable restore
#else
        public List<string> OrgChartRootPeopleIds { get; set; }
#endif
        /// <summary>The org_chart_sector property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? OrgChartSector { get; set; }
#nullable restore
#else
        public string OrgChartSector { get; set; }
#endif
        /// <summary>The org_chart_show_department_filter property</summary>
        public bool? OrgChartShowDepartmentFilter { get; set; }
        /// <summary>The owned_by_organization_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Apollo.OpenApiClient.Models.PeopleEnrichment200ResponsePersonOrganizationOwnedByOrganizationId? OwnedByOrganizationId { get; set; }
#nullable restore
#else
        public global::Soenneker.Apollo.OpenApiClient.Models.PeopleEnrichment200ResponsePersonOrganizationOwnedByOrganizationId OwnedByOrganizationId { get; set; }
#endif
        /// <summary>The phone property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Apollo.OpenApiClient.Models.PeopleEnrichment200ResponsePersonOrganizationPhone? Phone { get; set; }
#nullable restore
#else
        public global::Soenneker.Apollo.OpenApiClient.Models.PeopleEnrichment200ResponsePersonOrganizationPhone Phone { get; set; }
#endif
        /// <summary>The postal_code property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PostalCode { get; set; }
#nullable restore
#else
        public string PostalCode { get; set; }
#endif
        /// <summary>The primary_domain property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PrimaryDomain { get; set; }
#nullable restore
#else
        public string PrimaryDomain { get; set; }
#endif
        /// <summary>The primary_phone property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Apollo.OpenApiClient.Models.PeopleEnrichment200ResponsePersonOrganizationPrimaryPhone? PrimaryPhone { get; set; }
#nullable restore
#else
        public global::Soenneker.Apollo.OpenApiClient.Models.PeopleEnrichment200ResponsePersonOrganizationPrimaryPhone PrimaryPhone { get; set; }
#endif
        /// <summary>The publicly_traded_exchange property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Apollo.OpenApiClient.Models.PeopleEnrichment200ResponsePersonOrganizationPubliclyTradedExchange? PubliclyTradedExchange { get; set; }
#nullable restore
#else
        public global::Soenneker.Apollo.OpenApiClient.Models.PeopleEnrichment200ResponsePersonOrganizationPubliclyTradedExchange PubliclyTradedExchange { get; set; }
#endif
        /// <summary>The publicly_traded_symbol property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Apollo.OpenApiClient.Models.PeopleEnrichment200ResponsePersonOrganizationPubliclyTradedSymbol? PubliclyTradedSymbol { get; set; }
#nullable restore
#else
        public global::Soenneker.Apollo.OpenApiClient.Models.PeopleEnrichment200ResponsePersonOrganizationPubliclyTradedSymbol PubliclyTradedSymbol { get; set; }
#endif
        /// <summary>The raw_address property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? RawAddress { get; set; }
#nullable restore
#else
        public string RawAddress { get; set; }
#endif
        /// <summary>The retail_location_count property</summary>
        public int? RetailLocationCount { get; set; }
        /// <summary>The secondary_industries property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Apollo.OpenApiClient.Models.PeopleEnrichment200ResponsePersonOrganization_secondary_industries>? SecondaryIndustries { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Apollo.OpenApiClient.Models.PeopleEnrichment200ResponsePersonOrganization_secondary_industries> SecondaryIndustries { get; set; }
#endif
        /// <summary>The seo_description property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SeoDescription { get; set; }
#nullable restore
#else
        public string SeoDescription { get; set; }
#endif
        /// <summary>The short_description property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ShortDescription { get; set; }
#nullable restore
#else
        public string ShortDescription { get; set; }
#endif
        /// <summary>The snippets_loaded property</summary>
        public bool? SnippetsLoaded { get; set; }
        /// <summary>The state property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? State { get; set; }
#nullable restore
#else
        public string State { get; set; }
#endif
        /// <summary>The street_address property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? StreetAddress { get; set; }
#nullable restore
#else
        public string StreetAddress { get; set; }
#endif
        /// <summary>The suborganizations property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Apollo.OpenApiClient.Models.PeopleEnrichment200ResponsePersonOrganization_suborganizations>? Suborganizations { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Apollo.OpenApiClient.Models.PeopleEnrichment200ResponsePersonOrganization_suborganizations> Suborganizations { get; set; }
#endif
        /// <summary>The technology_names property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? TechnologyNames { get; set; }
#nullable restore
#else
        public List<string> TechnologyNames { get; set; }
#endif
        /// <summary>The total_funding property</summary>
        public int? TotalFunding { get; set; }
        /// <summary>The total_funding_printed property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TotalFundingPrinted { get; set; }
#nullable restore
#else
        public string TotalFundingPrinted { get; set; }
#endif
        /// <summary>The twitter_url property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TwitterUrl { get; set; }
#nullable restore
#else
        public string TwitterUrl { get; set; }
#endif
        /// <summary>The website_url property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? WebsiteUrl { get; set; }
#nullable restore
#else
        public string WebsiteUrl { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Apollo.OpenApiClient.Models.PeopleEnrichment200ResponsePersonOrganization"/> and sets the default values.
        /// </summary>
        public PeopleEnrichment200ResponsePersonOrganization()
        {
            AdditionalData = new Dictionary<string, object>();
            AlexaRanking = 0;
            AnnualRevenue = 0;
            EstimatedNumEmployees = 0;
            FoundedYear = 0;
            NumSuborganizations = 0;
            OrgChartRemoved = true;
            OrgChartShowDepartmentFilter = true;
            RetailLocationCount = 0;
            SnippetsLoaded = true;
            TotalFunding = 0;
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Apollo.OpenApiClient.Models.PeopleEnrichment200ResponsePersonOrganization"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Apollo.OpenApiClient.Models.PeopleEnrichment200ResponsePersonOrganization CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Apollo.OpenApiClient.Models.PeopleEnrichment200ResponsePersonOrganization();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "alexa_ranking", n => { AlexaRanking = n.GetIntValue(); } },
                { "angellist_url", n => { AngellistUrl = n.GetObjectValue<global::Soenneker.Apollo.OpenApiClient.Models.PeopleEnrichment200ResponsePersonOrganizationAngellistUrl>(global::Soenneker.Apollo.OpenApiClient.Models.PeopleEnrichment200ResponsePersonOrganizationAngellistUrl.CreateFromDiscriminatorValue); } },
                { "annual_revenue", n => { AnnualRevenue = n.GetIntValue(); } },
                { "annual_revenue_printed", n => { AnnualRevenuePrinted = n.GetStringValue(); } },
                { "blog_url", n => { BlogUrl = n.GetObjectValue<global::Soenneker.Apollo.OpenApiClient.Models.PeopleEnrichment200ResponsePersonOrganizationBlogUrl>(global::Soenneker.Apollo.OpenApiClient.Models.PeopleEnrichment200ResponsePersonOrganizationBlogUrl.CreateFromDiscriminatorValue); } },
                { "city", n => { City = n.GetStringValue(); } },
                { "country", n => { Country = n.GetStringValue(); } },
                { "crunchbase_url", n => { CrunchbaseUrl = n.GetObjectValue<global::Soenneker.Apollo.OpenApiClient.Models.PeopleEnrichment200ResponsePersonOrganizationCrunchbaseUrl>(global::Soenneker.Apollo.OpenApiClient.Models.PeopleEnrichment200ResponsePersonOrganizationCrunchbaseUrl.CreateFromDiscriminatorValue); } },
                { "current_technologies", n => { CurrentTechnologies = n.GetCollectionOfObjectValues<global::Soenneker.Apollo.OpenApiClient.Models.PeopleEnrichment200ResponsePersonOrganizationCurrentTechnologiesItem>(global::Soenneker.Apollo.OpenApiClient.Models.PeopleEnrichment200ResponsePersonOrganizationCurrentTechnologiesItem.CreateFromDiscriminatorValue)?.AsList(); } },
                { "estimated_num_employees", n => { EstimatedNumEmployees = n.GetIntValue(); } },
                { "facebook_url", n => { FacebookUrl = n.GetStringValue(); } },
                { "founded_year", n => { FoundedYear = n.GetIntValue(); } },
                { "funding_events", n => { FundingEvents = n.GetCollectionOfObjectValues<global::Soenneker.Apollo.OpenApiClient.Models.PeopleEnrichment200ResponsePersonOrganizationFundingEventsItem>(global::Soenneker.Apollo.OpenApiClient.Models.PeopleEnrichment200ResponsePersonOrganizationFundingEventsItem.CreateFromDiscriminatorValue)?.AsList(); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "industries", n => { Industries = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "industry", n => { Industry = n.GetStringValue(); } },
                { "industry_tag_hash", n => { IndustryTagHash = n.GetObjectValue<global::Soenneker.Apollo.OpenApiClient.Models.PeopleEnrichment200ResponsePersonOrganizationIndustryTagHash>(global::Soenneker.Apollo.OpenApiClient.Models.PeopleEnrichment200ResponsePersonOrganizationIndustryTagHash.CreateFromDiscriminatorValue); } },
                { "industry_tag_id", n => { IndustryTagId = n.GetStringValue(); } },
                { "keywords", n => { Keywords = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "languages", n => { Languages = n.GetCollectionOfObjectValues<global::Soenneker.Apollo.OpenApiClient.Models.PeopleEnrichment200ResponsePersonOrganization_languages>(global::Soenneker.Apollo.OpenApiClient.Models.PeopleEnrichment200ResponsePersonOrganization_languages.CreateFromDiscriminatorValue)?.AsList(); } },
                { "latest_funding_round_date", n => { LatestFundingRoundDate = n.GetStringValue(); } },
                { "latest_funding_stage", n => { LatestFundingStage = n.GetStringValue(); } },
                { "linkedin_uid", n => { LinkedinUid = n.GetStringValue(); } },
                { "linkedin_url", n => { LinkedinUrl = n.GetStringValue(); } },
                { "logo_url", n => { LogoUrl = n.GetStringValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "num_suborganizations", n => { NumSuborganizations = n.GetIntValue(); } },
                { "org_chart_removed", n => { OrgChartRemoved = n.GetBoolValue(); } },
                { "org_chart_root_people_ids", n => { OrgChartRootPeopleIds = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "org_chart_sector", n => { OrgChartSector = n.GetStringValue(); } },
                { "org_chart_show_department_filter", n => { OrgChartShowDepartmentFilter = n.GetBoolValue(); } },
                { "owned_by_organization_id", n => { OwnedByOrganizationId = n.GetObjectValue<global::Soenneker.Apollo.OpenApiClient.Models.PeopleEnrichment200ResponsePersonOrganizationOwnedByOrganizationId>(global::Soenneker.Apollo.OpenApiClient.Models.PeopleEnrichment200ResponsePersonOrganizationOwnedByOrganizationId.CreateFromDiscriminatorValue); } },
                { "phone", n => { Phone = n.GetObjectValue<global::Soenneker.Apollo.OpenApiClient.Models.PeopleEnrichment200ResponsePersonOrganizationPhone>(global::Soenneker.Apollo.OpenApiClient.Models.PeopleEnrichment200ResponsePersonOrganizationPhone.CreateFromDiscriminatorValue); } },
                { "postal_code", n => { PostalCode = n.GetStringValue(); } },
                { "primary_domain", n => { PrimaryDomain = n.GetStringValue(); } },
                { "primary_phone", n => { PrimaryPhone = n.GetObjectValue<global::Soenneker.Apollo.OpenApiClient.Models.PeopleEnrichment200ResponsePersonOrganizationPrimaryPhone>(global::Soenneker.Apollo.OpenApiClient.Models.PeopleEnrichment200ResponsePersonOrganizationPrimaryPhone.CreateFromDiscriminatorValue); } },
                { "publicly_traded_exchange", n => { PubliclyTradedExchange = n.GetObjectValue<global::Soenneker.Apollo.OpenApiClient.Models.PeopleEnrichment200ResponsePersonOrganizationPubliclyTradedExchange>(global::Soenneker.Apollo.OpenApiClient.Models.PeopleEnrichment200ResponsePersonOrganizationPubliclyTradedExchange.CreateFromDiscriminatorValue); } },
                { "publicly_traded_symbol", n => { PubliclyTradedSymbol = n.GetObjectValue<global::Soenneker.Apollo.OpenApiClient.Models.PeopleEnrichment200ResponsePersonOrganizationPubliclyTradedSymbol>(global::Soenneker.Apollo.OpenApiClient.Models.PeopleEnrichment200ResponsePersonOrganizationPubliclyTradedSymbol.CreateFromDiscriminatorValue); } },
                { "raw_address", n => { RawAddress = n.GetStringValue(); } },
                { "retail_location_count", n => { RetailLocationCount = n.GetIntValue(); } },
                { "secondary_industries", n => { SecondaryIndustries = n.GetCollectionOfObjectValues<global::Soenneker.Apollo.OpenApiClient.Models.PeopleEnrichment200ResponsePersonOrganization_secondary_industries>(global::Soenneker.Apollo.OpenApiClient.Models.PeopleEnrichment200ResponsePersonOrganization_secondary_industries.CreateFromDiscriminatorValue)?.AsList(); } },
                { "seo_description", n => { SeoDescription = n.GetStringValue(); } },
                { "short_description", n => { ShortDescription = n.GetStringValue(); } },
                { "snippets_loaded", n => { SnippetsLoaded = n.GetBoolValue(); } },
                { "state", n => { State = n.GetStringValue(); } },
                { "street_address", n => { StreetAddress = n.GetStringValue(); } },
                { "suborganizations", n => { Suborganizations = n.GetCollectionOfObjectValues<global::Soenneker.Apollo.OpenApiClient.Models.PeopleEnrichment200ResponsePersonOrganization_suborganizations>(global::Soenneker.Apollo.OpenApiClient.Models.PeopleEnrichment200ResponsePersonOrganization_suborganizations.CreateFromDiscriminatorValue)?.AsList(); } },
                { "technology_names", n => { TechnologyNames = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "total_funding", n => { TotalFunding = n.GetIntValue(); } },
                { "total_funding_printed", n => { TotalFundingPrinted = n.GetStringValue(); } },
                { "twitter_url", n => { TwitterUrl = n.GetStringValue(); } },
                { "website_url", n => { WebsiteUrl = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteIntValue("alexa_ranking", AlexaRanking);
            writer.WriteObjectValue<global::Soenneker.Apollo.OpenApiClient.Models.PeopleEnrichment200ResponsePersonOrganizationAngellistUrl>("angellist_url", AngellistUrl);
            writer.WriteIntValue("annual_revenue", AnnualRevenue);
            writer.WriteStringValue("annual_revenue_printed", AnnualRevenuePrinted);
            writer.WriteObjectValue<global::Soenneker.Apollo.OpenApiClient.Models.PeopleEnrichment200ResponsePersonOrganizationBlogUrl>("blog_url", BlogUrl);
            writer.WriteStringValue("city", City);
            writer.WriteStringValue("country", Country);
            writer.WriteObjectValue<global::Soenneker.Apollo.OpenApiClient.Models.PeopleEnrichment200ResponsePersonOrganizationCrunchbaseUrl>("crunchbase_url", CrunchbaseUrl);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Apollo.OpenApiClient.Models.PeopleEnrichment200ResponsePersonOrganizationCurrentTechnologiesItem>("current_technologies", CurrentTechnologies);
            writer.WriteIntValue("estimated_num_employees", EstimatedNumEmployees);
            writer.WriteStringValue("facebook_url", FacebookUrl);
            writer.WriteIntValue("founded_year", FoundedYear);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Apollo.OpenApiClient.Models.PeopleEnrichment200ResponsePersonOrganizationFundingEventsItem>("funding_events", FundingEvents);
            writer.WriteStringValue("id", Id);
            writer.WriteCollectionOfPrimitiveValues<string>("industries", Industries);
            writer.WriteStringValue("industry", Industry);
            writer.WriteObjectValue<global::Soenneker.Apollo.OpenApiClient.Models.PeopleEnrichment200ResponsePersonOrganizationIndustryTagHash>("industry_tag_hash", IndustryTagHash);
            writer.WriteStringValue("industry_tag_id", IndustryTagId);
            writer.WriteCollectionOfPrimitiveValues<string>("keywords", Keywords);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Apollo.OpenApiClient.Models.PeopleEnrichment200ResponsePersonOrganization_languages>("languages", Languages);
            writer.WriteStringValue("latest_funding_round_date", LatestFundingRoundDate);
            writer.WriteStringValue("latest_funding_stage", LatestFundingStage);
            writer.WriteStringValue("linkedin_uid", LinkedinUid);
            writer.WriteStringValue("linkedin_url", LinkedinUrl);
            writer.WriteStringValue("logo_url", LogoUrl);
            writer.WriteStringValue("name", Name);
            writer.WriteIntValue("num_suborganizations", NumSuborganizations);
            writer.WriteBoolValue("org_chart_removed", OrgChartRemoved);
            writer.WriteCollectionOfPrimitiveValues<string>("org_chart_root_people_ids", OrgChartRootPeopleIds);
            writer.WriteStringValue("org_chart_sector", OrgChartSector);
            writer.WriteBoolValue("org_chart_show_department_filter", OrgChartShowDepartmentFilter);
            writer.WriteObjectValue<global::Soenneker.Apollo.OpenApiClient.Models.PeopleEnrichment200ResponsePersonOrganizationOwnedByOrganizationId>("owned_by_organization_id", OwnedByOrganizationId);
            writer.WriteObjectValue<global::Soenneker.Apollo.OpenApiClient.Models.PeopleEnrichment200ResponsePersonOrganizationPhone>("phone", Phone);
            writer.WriteStringValue("postal_code", PostalCode);
            writer.WriteStringValue("primary_domain", PrimaryDomain);
            writer.WriteObjectValue<global::Soenneker.Apollo.OpenApiClient.Models.PeopleEnrichment200ResponsePersonOrganizationPrimaryPhone>("primary_phone", PrimaryPhone);
            writer.WriteObjectValue<global::Soenneker.Apollo.OpenApiClient.Models.PeopleEnrichment200ResponsePersonOrganizationPubliclyTradedExchange>("publicly_traded_exchange", PubliclyTradedExchange);
            writer.WriteObjectValue<global::Soenneker.Apollo.OpenApiClient.Models.PeopleEnrichment200ResponsePersonOrganizationPubliclyTradedSymbol>("publicly_traded_symbol", PubliclyTradedSymbol);
            writer.WriteStringValue("raw_address", RawAddress);
            writer.WriteIntValue("retail_location_count", RetailLocationCount);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Apollo.OpenApiClient.Models.PeopleEnrichment200ResponsePersonOrganization_secondary_industries>("secondary_industries", SecondaryIndustries);
            writer.WriteStringValue("seo_description", SeoDescription);
            writer.WriteStringValue("short_description", ShortDescription);
            writer.WriteBoolValue("snippets_loaded", SnippetsLoaded);
            writer.WriteStringValue("state", State);
            writer.WriteStringValue("street_address", StreetAddress);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Apollo.OpenApiClient.Models.PeopleEnrichment200ResponsePersonOrganization_suborganizations>("suborganizations", Suborganizations);
            writer.WriteCollectionOfPrimitiveValues<string>("technology_names", TechnologyNames);
            writer.WriteIntValue("total_funding", TotalFunding);
            writer.WriteStringValue("total_funding_printed", TotalFundingPrinted);
            writer.WriteStringValue("twitter_url", TwitterUrl);
            writer.WriteStringValue("website_url", WebsiteUrl);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
