// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Apollo.OpenApiClient.Models
{
    /// <summary>Sort the matching accounts by 1 of the following options:- `account_last_activity_date`: The most recent activity date recorded first.- `account_created_at`: The most recently created first.- `account_updated_at`: The most recently updated first.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum SearchForAccountsRequestSortByField
    {
        [EnumMember(Value = "account_last_activity_date")]
        #pragma warning disable CS1591
        AccountLastActivityDate,
        #pragma warning restore CS1591
        [EnumMember(Value = "account_created_at")]
        #pragma warning disable CS1591
        AccountCreatedAt,
        #pragma warning restore CS1591
        [EnumMember(Value = "account_updated_at")]
        #pragma warning disable CS1591
        AccountUpdatedAt,
        #pragma warning restore CS1591
    }
}
