// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Apollo.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class SearchConversations200ResponseConversationsItem : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>IDs of associated accounts.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? AccountIds { get; set; }
#nullable restore
#else
        public List<string> AccountIds { get; set; }
#endif
        /// <summary>Names of associated accounts.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? AccountNames { get; set; }
#nullable restore
#else
        public List<string> AccountNames { get; set; }
#endif
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Whether the authenticated user can access this conversation.</summary>
        public bool? CanAccessConversation { get; set; }
        /// <summary>Number of comments on the conversation.</summary>
        public int? CommentCount { get; set; }
        /// <summary>Filter by dialer calls, or video conference calls.</summary>
        public global::Soenneker.Apollo.OpenApiClient.Models.SearchConversations200ResponseConversationsItemConversationType? ConversationType { get; set; }
        /// <summary>Deals associated with the conversation.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Apollo.OpenApiClient.Models.SearchConversations200ResponseConversationsItemDealsItem>? Deals { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Apollo.OpenApiClient.Models.SearchConversations200ResponseConversationsItemDealsItem> Deals { get; set; }
#endif
        /// <summary>Duration of the conversation in seconds.</summary>
        public int? Duration { get; set; }
        /// <summary>Name of the conversation host.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Host { get; set; }
#nullable restore
#else
        public string Host { get; set; }
#endif
        /// <summary>User ID of the conversation host.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? HostId { get; set; }
#nullable restore
#else
        public string HostId { get; set; }
#endif
        /// <summary>Unique conversation ID.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>Whether the conversation is internal.</summary>
        public bool? IsInternal { get; set; }
        /// <summary>Privacy setting of the conversation.</summary>
        public bool? IsPrivate { get; set; }
        /// <summary>Label names associated with the conversation.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Apollo.OpenApiClient.Models.SearchConversations200ResponseConversationsItemLabelIdNames? LabelIdNames { get; set; }
#nullable restore
#else
        public global::Soenneker.Apollo.OpenApiClient.Models.SearchConversations200ResponseConversationsItemLabelIdNames LabelIdNames { get; set; }
#endif
        /// <summary>Organization associated with the result.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Apollo.OpenApiClient.Models.SearchConversations200ResponseConversationsItemOrganization? Organization { get; set; }
#nullable restore
#else
        public global::Soenneker.Apollo.OpenApiClient.Models.SearchConversations200ResponseConversationsItemOrganization Organization { get; set; }
#endif
        /// <summary>Names of the conversation participants.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? ParticipantNames { get; set; }
#nullable restore
#else
        public List<string> ParticipantNames { get; set; }
#endif
        /// <summary>Detailed information about conversation participants.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Apollo.OpenApiClient.Models.SearchConversations200ResponseConversationsItemParticipantsInfoItem>? ParticipantsInfo { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Apollo.OpenApiClient.Models.SearchConversations200ResponseConversationsItemParticipantsInfoItem> ParticipantsInfo { get; set; }
#endif
        /// <summary>Conversation start time (ISO 8601). Apollo uses Greenwich Mean Time (GMT) for all date and time values.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? StartTime { get; set; }
#nullable restore
#else
        public string StartTime { get; set; }
#endif
        /// <summary>Current processing state of the conversation.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? State { get; set; }
#nullable restore
#else
        public string State { get; set; }
#endif
        /// <summary>URL of the conversation thumbnail image.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ThumbnailUrl { get; set; }
#nullable restore
#else
        public string ThumbnailUrl { get; set; }
#endif
        /// <summary>Conversation topic or title.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Topic { get; set; }
#nullable restore
#else
        public string Topic { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Apollo.OpenApiClient.Models.SearchConversations200ResponseConversationsItem"/> and sets the default values.
        /// </summary>
        public SearchConversations200ResponseConversationsItem()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Apollo.OpenApiClient.Models.SearchConversations200ResponseConversationsItem"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Apollo.OpenApiClient.Models.SearchConversations200ResponseConversationsItem CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Apollo.OpenApiClient.Models.SearchConversations200ResponseConversationsItem();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "account_ids", n => { AccountIds = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "account_names", n => { AccountNames = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "can_access_conversation", n => { CanAccessConversation = n.GetBoolValue(); } },
                { "comment_count", n => { CommentCount = n.GetIntValue(); } },
                { "conversation_type", n => { ConversationType = n.GetEnumValue<global::Soenneker.Apollo.OpenApiClient.Models.SearchConversations200ResponseConversationsItemConversationType>(); } },
                { "deals", n => { Deals = n.GetCollectionOfObjectValues<global::Soenneker.Apollo.OpenApiClient.Models.SearchConversations200ResponseConversationsItemDealsItem>(global::Soenneker.Apollo.OpenApiClient.Models.SearchConversations200ResponseConversationsItemDealsItem.CreateFromDiscriminatorValue)?.AsList(); } },
                { "duration", n => { Duration = n.GetIntValue(); } },
                { "host", n => { Host = n.GetStringValue(); } },
                { "host_id", n => { HostId = n.GetStringValue(); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "is_internal", n => { IsInternal = n.GetBoolValue(); } },
                { "is_private", n => { IsPrivate = n.GetBoolValue(); } },
                { "label_id_names", n => { LabelIdNames = n.GetObjectValue<global::Soenneker.Apollo.OpenApiClient.Models.SearchConversations200ResponseConversationsItemLabelIdNames>(global::Soenneker.Apollo.OpenApiClient.Models.SearchConversations200ResponseConversationsItemLabelIdNames.CreateFromDiscriminatorValue); } },
                { "organization", n => { Organization = n.GetObjectValue<global::Soenneker.Apollo.OpenApiClient.Models.SearchConversations200ResponseConversationsItemOrganization>(global::Soenneker.Apollo.OpenApiClient.Models.SearchConversations200ResponseConversationsItemOrganization.CreateFromDiscriminatorValue); } },
                { "participant_names", n => { ParticipantNames = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "participants_info", n => { ParticipantsInfo = n.GetCollectionOfObjectValues<global::Soenneker.Apollo.OpenApiClient.Models.SearchConversations200ResponseConversationsItemParticipantsInfoItem>(global::Soenneker.Apollo.OpenApiClient.Models.SearchConversations200ResponseConversationsItemParticipantsInfoItem.CreateFromDiscriminatorValue)?.AsList(); } },
                { "start_time", n => { StartTime = n.GetStringValue(); } },
                { "state", n => { State = n.GetStringValue(); } },
                { "thumbnail_url", n => { ThumbnailUrl = n.GetStringValue(); } },
                { "topic", n => { Topic = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfPrimitiveValues<string>("account_ids", AccountIds);
            writer.WriteCollectionOfPrimitiveValues<string>("account_names", AccountNames);
            writer.WriteBoolValue("can_access_conversation", CanAccessConversation);
            writer.WriteIntValue("comment_count", CommentCount);
            writer.WriteEnumValue<global::Soenneker.Apollo.OpenApiClient.Models.SearchConversations200ResponseConversationsItemConversationType>("conversation_type", ConversationType);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Apollo.OpenApiClient.Models.SearchConversations200ResponseConversationsItemDealsItem>("deals", Deals);
            writer.WriteIntValue("duration", Duration);
            writer.WriteStringValue("host", Host);
            writer.WriteStringValue("host_id", HostId);
            writer.WriteStringValue("id", Id);
            writer.WriteBoolValue("is_internal", IsInternal);
            writer.WriteBoolValue("is_private", IsPrivate);
            writer.WriteObjectValue<global::Soenneker.Apollo.OpenApiClient.Models.SearchConversations200ResponseConversationsItemLabelIdNames>("label_id_names", LabelIdNames);
            writer.WriteObjectValue<global::Soenneker.Apollo.OpenApiClient.Models.SearchConversations200ResponseConversationsItemOrganization>("organization", Organization);
            writer.WriteCollectionOfPrimitiveValues<string>("participant_names", ParticipantNames);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Apollo.OpenApiClient.Models.SearchConversations200ResponseConversationsItemParticipantsInfoItem>("participants_info", ParticipantsInfo);
            writer.WriteStringValue("start_time", StartTime);
            writer.WriteStringValue("state", State);
            writer.WriteStringValue("thumbnail_url", ThumbnailUrl);
            writer.WriteStringValue("topic", Topic);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
