// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Apollo.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class SearchForContacts200ResponseContactsItemAccountAccountRuleConfigStatusesItem : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The created_at property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Apollo.OpenApiClient.Models.SearchForContacts200ResponseContactsItemAccountAccountRuleConfigStatusesItemCreatedAt? CreatedAt { get; set; }
#nullable restore
#else
        public global::Soenneker.Apollo.OpenApiClient.Models.SearchForContacts200ResponseContactsItemAccountAccountRuleConfigStatusesItemCreatedAt CreatedAt { get; set; }
#endif
        /// <summary>The id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>The key property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Key { get; set; }
#nullable restore
#else
        public string Key { get; set; }
#endif
        /// <summary>The rule_action_config_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? RuleActionConfigId { get; set; }
#nullable restore
#else
        public string RuleActionConfigId { get; set; }
#endif
        /// <summary>The rule_config_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? RuleConfigId { get; set; }
#nullable restore
#else
        public string RuleConfigId { get; set; }
#endif
        /// <summary>The id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SearchForContacts200ResponseContactsItemAccountAccountRuleConfigStatusesItemId { get; set; }
#nullable restore
#else
        public string SearchForContacts200ResponseContactsItemAccountAccountRuleConfigStatusesItemId { get; set; }
#endif
        /// <summary>The status_cd property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? StatusCd { get; set; }
#nullable restore
#else
        public string StatusCd { get; set; }
#endif
        /// <summary>The updated_at property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Apollo.OpenApiClient.Models.SearchForContacts200ResponseContactsItemAccountAccountRuleConfigStatusesItemUpdatedAt? UpdatedAt { get; set; }
#nullable restore
#else
        public global::Soenneker.Apollo.OpenApiClient.Models.SearchForContacts200ResponseContactsItemAccountAccountRuleConfigStatusesItemUpdatedAt UpdatedAt { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Apollo.OpenApiClient.Models.SearchForContacts200ResponseContactsItemAccountAccountRuleConfigStatusesItem"/> and sets the default values.
        /// </summary>
        public SearchForContacts200ResponseContactsItemAccountAccountRuleConfigStatusesItem()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Apollo.OpenApiClient.Models.SearchForContacts200ResponseContactsItemAccountAccountRuleConfigStatusesItem"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Apollo.OpenApiClient.Models.SearchForContacts200ResponseContactsItemAccountAccountRuleConfigStatusesItem CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Apollo.OpenApiClient.Models.SearchForContacts200ResponseContactsItemAccountAccountRuleConfigStatusesItem();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "created_at", n => { CreatedAt = n.GetObjectValue<global::Soenneker.Apollo.OpenApiClient.Models.SearchForContacts200ResponseContactsItemAccountAccountRuleConfigStatusesItemCreatedAt>(global::Soenneker.Apollo.OpenApiClient.Models.SearchForContacts200ResponseContactsItemAccountAccountRuleConfigStatusesItemCreatedAt.CreateFromDiscriminatorValue); } },
                { "_id", n => { Id = n.GetStringValue(); } },
                { "key", n => { Key = n.GetStringValue(); } },
                { "rule_action_config_id", n => { RuleActionConfigId = n.GetStringValue(); } },
                { "rule_config_id", n => { RuleConfigId = n.GetStringValue(); } },
                { "id", n => { SearchForContacts200ResponseContactsItemAccountAccountRuleConfigStatusesItemId = n.GetStringValue(); } },
                { "status_cd", n => { StatusCd = n.GetStringValue(); } },
                { "updated_at", n => { UpdatedAt = n.GetObjectValue<global::Soenneker.Apollo.OpenApiClient.Models.SearchForContacts200ResponseContactsItemAccountAccountRuleConfigStatusesItemUpdatedAt>(global::Soenneker.Apollo.OpenApiClient.Models.SearchForContacts200ResponseContactsItemAccountAccountRuleConfigStatusesItemUpdatedAt.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Apollo.OpenApiClient.Models.SearchForContacts200ResponseContactsItemAccountAccountRuleConfigStatusesItemCreatedAt>("created_at", CreatedAt);
            writer.WriteStringValue("_id", Id);
            writer.WriteStringValue("key", Key);
            writer.WriteStringValue("rule_action_config_id", RuleActionConfigId);
            writer.WriteStringValue("rule_config_id", RuleConfigId);
            writer.WriteStringValue("id", SearchForContacts200ResponseContactsItemAccountAccountRuleConfigStatusesItemId);
            writer.WriteStringValue("status_cd", StatusCd);
            writer.WriteObjectValue<global::Soenneker.Apollo.OpenApiClient.Models.SearchForContacts200ResponseContactsItemAccountAccountRuleConfigStatusesItemUpdatedAt>("updated_at", UpdatedAt);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
