// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Apollo.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class SearchForAccounts200Response : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The accounts property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Apollo.OpenApiClient.Models.SearchForAccounts200ResponseAccountsItem>? Accounts { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Apollo.OpenApiClient.Models.SearchForAccounts200ResponseAccountsItem> Accounts { get; set; }
#endif
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The breadcrumbs property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Apollo.OpenApiClient.Models.SearchForAccounts200ResponseBreadcrumbsItem>? Breadcrumbs { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Apollo.OpenApiClient.Models.SearchForAccounts200ResponseBreadcrumbsItem> Breadcrumbs { get; set; }
#endif
        /// <summary>The disable_eu_prospecting property</summary>
        public bool? DisableEuProspecting { get; set; }
        /// <summary>The has_join property</summary>
        public bool? HasJoin { get; set; }
        /// <summary>The num_fetch_result property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Apollo.OpenApiClient.Models.SearchForAccounts200ResponseNumFetchResult? NumFetchResult { get; set; }
#nullable restore
#else
        public global::Soenneker.Apollo.OpenApiClient.Models.SearchForAccounts200ResponseNumFetchResult NumFetchResult { get; set; }
#endif
        /// <summary>The pagination property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Apollo.OpenApiClient.Models.SearchForAccounts200ResponsePagination? Pagination { get; set; }
#nullable restore
#else
        public global::Soenneker.Apollo.OpenApiClient.Models.SearchForAccounts200ResponsePagination Pagination { get; set; }
#endif
        /// <summary>The partial_results_limit property</summary>
        public int? PartialResultsLimit { get; set; }
        /// <summary>The partial_results_only property</summary>
        public bool? PartialResultsOnly { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Apollo.OpenApiClient.Models.SearchForAccounts200Response"/> and sets the default values.
        /// </summary>
        public SearchForAccounts200Response()
        {
            AdditionalData = new Dictionary<string, object>();
            DisableEuProspecting = true;
            HasJoin = true;
            PartialResultsLimit = 0;
            PartialResultsOnly = true;
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Apollo.OpenApiClient.Models.SearchForAccounts200Response"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Apollo.OpenApiClient.Models.SearchForAccounts200Response CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Apollo.OpenApiClient.Models.SearchForAccounts200Response();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "accounts", n => { Accounts = n.GetCollectionOfObjectValues<global::Soenneker.Apollo.OpenApiClient.Models.SearchForAccounts200ResponseAccountsItem>(global::Soenneker.Apollo.OpenApiClient.Models.SearchForAccounts200ResponseAccountsItem.CreateFromDiscriminatorValue)?.AsList(); } },
                { "breadcrumbs", n => { Breadcrumbs = n.GetCollectionOfObjectValues<global::Soenneker.Apollo.OpenApiClient.Models.SearchForAccounts200ResponseBreadcrumbsItem>(global::Soenneker.Apollo.OpenApiClient.Models.SearchForAccounts200ResponseBreadcrumbsItem.CreateFromDiscriminatorValue)?.AsList(); } },
                { "disable_eu_prospecting", n => { DisableEuProspecting = n.GetBoolValue(); } },
                { "has_join", n => { HasJoin = n.GetBoolValue(); } },
                { "num_fetch_result", n => { NumFetchResult = n.GetObjectValue<global::Soenneker.Apollo.OpenApiClient.Models.SearchForAccounts200ResponseNumFetchResult>(global::Soenneker.Apollo.OpenApiClient.Models.SearchForAccounts200ResponseNumFetchResult.CreateFromDiscriminatorValue); } },
                { "pagination", n => { Pagination = n.GetObjectValue<global::Soenneker.Apollo.OpenApiClient.Models.SearchForAccounts200ResponsePagination>(global::Soenneker.Apollo.OpenApiClient.Models.SearchForAccounts200ResponsePagination.CreateFromDiscriminatorValue); } },
                { "partial_results_limit", n => { PartialResultsLimit = n.GetIntValue(); } },
                { "partial_results_only", n => { PartialResultsOnly = n.GetBoolValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::Soenneker.Apollo.OpenApiClient.Models.SearchForAccounts200ResponseAccountsItem>("accounts", Accounts);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Apollo.OpenApiClient.Models.SearchForAccounts200ResponseBreadcrumbsItem>("breadcrumbs", Breadcrumbs);
            writer.WriteBoolValue("disable_eu_prospecting", DisableEuProspecting);
            writer.WriteBoolValue("has_join", HasJoin);
            writer.WriteObjectValue<global::Soenneker.Apollo.OpenApiClient.Models.SearchForAccounts200ResponseNumFetchResult>("num_fetch_result", NumFetchResult);
            writer.WriteObjectValue<global::Soenneker.Apollo.OpenApiClient.Models.SearchForAccounts200ResponsePagination>("pagination", Pagination);
            writer.WriteIntValue("partial_results_limit", PartialResultsLimit);
            writer.WriteBoolValue("partial_results_only", PartialResultsOnly);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
