// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Apollo.OpenApiClient.Models
{
    /// <summary>
    /// Required when &lt;code&gt;date_ranges[].modality&lt;/code&gt; is &lt;code&gt;custom_range&lt;/code&gt;. Specifies the exact date window as ISO 8601 date strings.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class SyncReportRequestFiltersSmartDatetimeRange : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>&quot;End date (inclusive). Format: &lt;code&gt;YYYY-MM-DD&lt;/code&gt;. &lt;br&gt;&lt;br&gt;Example: &lt;code&gt;2024-03-31&lt;/code&gt;&quot;</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Max { get; set; }
#nullable restore
#else
        public string Max { get; set; }
#endif
        /// <summary>&quot;Start date (inclusive). Format: &lt;code&gt;YYYY-MM-DD&lt;/code&gt;. &lt;br&gt;&lt;br&gt;Example: &lt;code&gt;2024-01-01&lt;/code&gt;&quot;</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Min { get; set; }
#nullable restore
#else
        public string Min { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Apollo.OpenApiClient.Models.SyncReportRequestFiltersSmartDatetimeRange"/> and sets the default values.
        /// </summary>
        public SyncReportRequestFiltersSmartDatetimeRange()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Apollo.OpenApiClient.Models.SyncReportRequestFiltersSmartDatetimeRange"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Apollo.OpenApiClient.Models.SyncReportRequestFiltersSmartDatetimeRange CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Apollo.OpenApiClient.Models.SyncReportRequestFiltersSmartDatetimeRange();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "max", n => { Max = n.GetStringValue(); } },
                { "min", n => { Min = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("max", Max);
            writer.WriteStringValue("min", Min);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
