// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Apollo.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class SyncReportRequestSortsItem : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Sort ascending (&lt;code&gt;true&lt;/code&gt;) or descending (&lt;code&gt;false&lt;/code&gt;).</summary>
        public bool? Asc { get; set; }
        /// <summary>Sort by a metric column. Provide the same structure as a metric entry in the &lt;code&gt;metrics&lt;/code&gt; array.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Apollo.OpenApiClient.Models.SyncReportRequestSortsItemMetric? Metric { get; set; }
#nullable restore
#else
        public global::Soenneker.Apollo.OpenApiClient.Models.SyncReportRequestSortsItemMetric Metric { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Apollo.OpenApiClient.Models.SyncReportRequestSortsItem"/> and sets the default values.
        /// </summary>
        public SyncReportRequestSortsItem()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Apollo.OpenApiClient.Models.SyncReportRequestSortsItem"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Apollo.OpenApiClient.Models.SyncReportRequestSortsItem CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Apollo.OpenApiClient.Models.SyncReportRequestSortsItem();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "asc", n => { Asc = n.GetBoolValue(); } },
                { "metric", n => { Metric = n.GetObjectValue<global::Soenneker.Apollo.OpenApiClient.Models.SyncReportRequestSortsItemMetric>(global::Soenneker.Apollo.OpenApiClient.Models.SyncReportRequestSortsItemMetric.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("asc", Asc);
            writer.WriteObjectValue<global::Soenneker.Apollo.OpenApiClient.Models.SyncReportRequestSortsItemMetric>("metric", Metric);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
