// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Apollo.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class UpdateATaskRequest : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Only applies to tasks with a `scheduled` status. A call script or talking points for a `call` type task.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CallScript { get; set; }
#nullable restore
#else
        public string CallScript { get; set; }
#endif
        /// <summary>&quot;The Apollo ID for the contact you want on the receiving end of the action. &lt;br&gt;&lt;br&gt;Example: `66e34b81740c50074e3d1bd4`&quot;</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ContactId { get; set; }
#nullable restore
#else
        public string ContactId { get; set; }
#endif
        /// <summary>&quot;The ID of the user considered the creator of this task. Only applies to tasks with a `scheduled` status. &lt;br&gt;&lt;br&gt;If this task currently has a `scheduled` status and you omit this parameter, Apollo resets it to the user associated with your API key. &lt;br&gt;&lt;br&gt;Example: `60affe7d6e270a00f5db6fe4`&quot;</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CreatorId { get; set; }
#nullable restore
#else
        public string CreatorId { get; set; }
#endif
        /// <summary>&quot;Only applies to tasks with a `scheduled` status. The full date and time when the task is due, in &lt;a href=\&quot;https://www.rfc-editor.org/rfc/rfc3339#section-5.6\&quot; target=\&quot;_blank\&quot;&gt;ISO 8601&lt;/a&gt; format. &lt;br&gt;&lt;br&gt;Example: `2025-02-15T08:10:30Z`&quot;</summary>
        public DateTimeOffset? DueAt { get; set; }
        /// <summary>&quot;A description for the task. This should be a human-readable message. &lt;br&gt;&lt;br&gt;Example: `This contact expressed interest in the Sequences feature specifically. Be prepared to discuss.`&quot;</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Note { get; set; }
#nullable restore
#else
        public string Note { get; set; }
#endif
        /// <summary>&quot;Assign a priority to the task: `high`, `medium`, or `low`. &lt;br&gt;&lt;br&gt;If this task currently has a `scheduled` status and you omit this parameter, Apollo resets its priority to `medium`.&quot;</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Priority { get; set; }
#nullable restore
#else
        public string Priority { get; set; }
#endif
        /// <summary>Numeric-coded alternative to `priority`. Only applies to tasks that are not `scheduled` (already `completed` or `skipped`).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Apollo.OpenApiClient.Models.UpdateATaskRequestPriorityCd? PriorityCd { get; set; }
#nullable restore
#else
        public global::Soenneker.Apollo.OpenApiClient.Models.UpdateATaskRequestPriorityCd PriorityCd { get; set; }
#endif
        /// <summary>Only applies to tasks with a `scheduled` status. Names of team-defined relevant fields to surface for this task.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Apollo.OpenApiClient.Models.UpdateATaskRequest_relevant_fields>? RelevantFields { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Apollo.OpenApiClient.Models.UpdateATaskRequest_relevant_fields> RelevantFields { get; set; }
#endif
        /// <summary>&quot;Only applies to tasks with a `scheduled` status. To mark a task done, use the &lt;a href=\&quot;https://docs.apollo.io/reference/complete-a-task\&quot;&gt;Complete a Task&lt;/a&gt; or &lt;a href=\&quot;https://docs.apollo.io/reference/skip-a-task\&quot;&gt;Skip a Task&lt;/a&gt; endpoints instead of setting this directly. &lt;br&gt;&lt;br&gt;Example: `scheduled`&quot;</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Status { get; set; }
#nullable restore
#else
        public string Status { get; set; }
#endif
        /// <summary>&quot;Only applies to tasks with a `scheduled` status. A title for the task. &lt;br&gt;&lt;br&gt;Example: `Follow up on demo request`&quot;</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Title { get; set; }
#nullable restore
#else
        public string Title { get; set; }
#endif
        /// <summary>&quot;Only applies to tasks with a `scheduled` status. Set the task to 1 of the following task types: &lt;ul&gt; &lt;li&gt; `call`: Call the contact. &lt;/li&gt; &lt;li&gt; `outreach_manual_email`: Email the contact. &lt;/li&gt; &lt;li&gt; `linkedin_step_connect`: Send a LinkedIn invitation to connect with the contact. &lt;/li&gt; &lt;li&gt; `linkedin_step_message`: Send a direct message to the contact&apos;s LinkedIn profile. &lt;/li&gt; &lt;li&gt; `linkedin_step_view_profile`: View the contact&apos;s LinkedIn profile. &lt;/li&gt; &lt;li&gt; `linkedin_step_interact_post`: Interact with the contact&apos;s recent LinkedIn posts. &lt;/li&gt; &lt;li&gt; `action_item`: Take generic action for the contact. &lt;/li&gt; &lt;/ul&gt;&quot;</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Type { get; set; }
#nullable restore
#else
        public string Type { get; set; }
#endif
        /// <summary>&quot;The ID for the task owner within your team&apos;s Apollo account. Only applies to tasks with a `scheduled` status. &lt;br&gt;&lt;br&gt;Example: `66302798d03b9601c7934ebf`&quot;</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? UserId { get; set; }
#nullable restore
#else
        public string UserId { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Apollo.OpenApiClient.Models.UpdateATaskRequest"/> and sets the default values.
        /// </summary>
        public UpdateATaskRequest()
        {
            AdditionalData = new Dictionary<string, object>();
            Priority = "medium";
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Apollo.OpenApiClient.Models.UpdateATaskRequest"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Apollo.OpenApiClient.Models.UpdateATaskRequest CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Apollo.OpenApiClient.Models.UpdateATaskRequest();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "call_script", n => { CallScript = n.GetStringValue(); } },
                { "contact_id", n => { ContactId = n.GetStringValue(); } },
                { "creator_id", n => { CreatorId = n.GetStringValue(); } },
                { "due_at", n => { DueAt = n.GetDateTimeOffsetValue(); } },
                { "note", n => { Note = n.GetStringValue(); } },
                { "priority", n => { Priority = n.GetStringValue(); } },
                { "priority_cd", n => { PriorityCd = n.GetObjectValue<global::Soenneker.Apollo.OpenApiClient.Models.UpdateATaskRequestPriorityCd>(global::Soenneker.Apollo.OpenApiClient.Models.UpdateATaskRequestPriorityCd.CreateFromDiscriminatorValue); } },
                { "relevant_fields", n => { RelevantFields = n.GetCollectionOfObjectValues<global::Soenneker.Apollo.OpenApiClient.Models.UpdateATaskRequest_relevant_fields>(global::Soenneker.Apollo.OpenApiClient.Models.UpdateATaskRequest_relevant_fields.CreateFromDiscriminatorValue)?.AsList(); } },
                { "status", n => { Status = n.GetStringValue(); } },
                { "title", n => { Title = n.GetStringValue(); } },
                { "type", n => { Type = n.GetStringValue(); } },
                { "user_id", n => { UserId = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("call_script", CallScript);
            writer.WriteStringValue("contact_id", ContactId);
            writer.WriteStringValue("creator_id", CreatorId);
            writer.WriteDateTimeOffsetValue("due_at", DueAt);
            writer.WriteStringValue("note", Note);
            writer.WriteStringValue("priority", Priority);
            writer.WriteObjectValue<global::Soenneker.Apollo.OpenApiClient.Models.UpdateATaskRequestPriorityCd>("priority_cd", PriorityCd);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Apollo.OpenApiClient.Models.UpdateATaskRequest_relevant_fields>("relevant_fields", RelevantFields);
            writer.WriteStringValue("status", Status);
            writer.WriteStringValue("title", Title);
            writer.WriteStringValue("type", Type);
            writer.WriteStringValue("user_id", UserId);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
