// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Apollo.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class UpdateAContact200ResponseContactPhoneNumbersItem : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The dialer_flags property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public UntypedNode? DialerFlags { get; set; }
#nullable restore
#else
        public UntypedNode DialerFlags { get; set; }
#endif
        /// <summary>The dnc_other_info property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public UntypedNode? DncOtherInfo { get; set; }
#nullable restore
#else
        public UntypedNode DncOtherInfo { get; set; }
#endif
        /// <summary>The dnc_status property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public UntypedNode? DncStatus { get; set; }
#nullable restore
#else
        public UntypedNode DncStatus { get; set; }
#endif
        /// <summary>The position property</summary>
        public int? Position { get; set; }
        /// <summary>The raw_number property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? RawNumber { get; set; }
#nullable restore
#else
        public string RawNumber { get; set; }
#endif
        /// <summary>The sanitized_number property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SanitizedNumber { get; set; }
#nullable restore
#else
        public string SanitizedNumber { get; set; }
#endif
        /// <summary>The status property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Status { get; set; }
#nullable restore
#else
        public string Status { get; set; }
#endif
        /// <summary>The type property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Type { get; set; }
#nullable restore
#else
        public string Type { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Apollo.OpenApiClient.Models.UpdateAContact200ResponseContactPhoneNumbersItem"/> and sets the default values.
        /// </summary>
        public UpdateAContact200ResponseContactPhoneNumbersItem()
        {
            AdditionalData = new Dictionary<string, object>();
            Position = 0;
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Apollo.OpenApiClient.Models.UpdateAContact200ResponseContactPhoneNumbersItem"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Apollo.OpenApiClient.Models.UpdateAContact200ResponseContactPhoneNumbersItem CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Apollo.OpenApiClient.Models.UpdateAContact200ResponseContactPhoneNumbersItem();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "dialer_flags", n => { DialerFlags = n.GetObjectValue<UntypedNode>(UntypedNode.CreateFromDiscriminatorValue); } },
                { "dnc_other_info", n => { DncOtherInfo = n.GetObjectValue<UntypedNode>(UntypedNode.CreateFromDiscriminatorValue); } },
                { "dnc_status", n => { DncStatus = n.GetObjectValue<UntypedNode>(UntypedNode.CreateFromDiscriminatorValue); } },
                { "position", n => { Position = n.GetIntValue(); } },
                { "raw_number", n => { RawNumber = n.GetStringValue(); } },
                { "sanitized_number", n => { SanitizedNumber = n.GetStringValue(); } },
                { "status", n => { Status = n.GetStringValue(); } },
                { "type", n => { Type = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<UntypedNode>("dialer_flags", DialerFlags);
            writer.WriteObjectValue<UntypedNode>("dnc_other_info", DncOtherInfo);
            writer.WriteObjectValue<UntypedNode>("dnc_status", DncStatus);
            writer.WriteIntValue("position", Position);
            writer.WriteStringValue("raw_number", RawNumber);
            writer.WriteStringValue("sanitized_number", SanitizedNumber);
            writer.WriteStringValue("status", Status);
            writer.WriteStringValue("type", Type);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
