// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Apollo.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class UpdateAnAccount200ResponseAccount : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The account_playbook_statuses property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Apollo.OpenApiClient.Models.UpdateAnAccount200ResponseAccount_account_playbook_statuses>? AccountPlaybookStatuses { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Apollo.OpenApiClient.Models.UpdateAnAccount200ResponseAccount_account_playbook_statuses> AccountPlaybookStatuses { get; set; }
#endif
        /// <summary>The account_rule_config_statuses property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Apollo.OpenApiClient.Models.UpdateAnAccount200ResponseAccount_account_rule_config_statuses>? AccountRuleConfigStatuses { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Apollo.OpenApiClient.Models.UpdateAnAccount200ResponseAccount_account_rule_config_statuses> AccountRuleConfigStatuses { get; set; }
#endif
        /// <summary>The account_stage_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AccountStageId { get; set; }
#nullable restore
#else
        public string AccountStageId { get; set; }
#endif
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The created_at property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CreatedAt { get; set; }
#nullable restore
#else
        public string CreatedAt { get; set; }
#endif
        /// <summary>The creator_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public UntypedNode? CreatorId { get; set; }
#nullable restore
#else
        public UntypedNode CreatorId { get; set; }
#endif
        /// <summary>The crm_owner_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public UntypedNode? CrmOwnerId { get; set; }
#nullable restore
#else
        public UntypedNode CrmOwnerId { get; set; }
#endif
        /// <summary>The crm_record_url property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public UntypedNode? CrmRecordUrl { get; set; }
#nullable restore
#else
        public UntypedNode CrmRecordUrl { get; set; }
#endif
        /// <summary>The custom_field_errors property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Apollo.OpenApiClient.Models.UpdateAnAccount200ResponseAccountCustomFieldErrors? CustomFieldErrors { get; set; }
#nullable restore
#else
        public global::Soenneker.Apollo.OpenApiClient.Models.UpdateAnAccount200ResponseAccountCustomFieldErrors CustomFieldErrors { get; set; }
#endif
        /// <summary>The domain property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Domain { get; set; }
#nullable restore
#else
        public string Domain { get; set; }
#endif
        /// <summary>The existence_level property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ExistenceLevel { get; set; }
#nullable restore
#else
        public string ExistenceLevel { get; set; }
#endif
        /// <summary>The has_intent_signal_account property</summary>
        public bool? HasIntentSignalAccount { get; set; }
        /// <summary>The hubspot_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public UntypedNode? HubspotId { get; set; }
#nullable restore
#else
        public UntypedNode HubspotId { get; set; }
#endif
        /// <summary>The id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>The intent_signal_account property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public UntypedNode? IntentSignalAccount { get; set; }
#nullable restore
#else
        public UntypedNode IntentSignalAccount { get; set; }
#endif
        /// <summary>The label_ids property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Apollo.OpenApiClient.Models.UpdateAnAccount200ResponseAccount_label_ids>? LabelIds { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Apollo.OpenApiClient.Models.UpdateAnAccount200ResponseAccount_label_ids> LabelIds { get; set; }
#endif
        /// <summary>The linkedin_url property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public UntypedNode? LinkedinUrl { get; set; }
#nullable restore
#else
        public UntypedNode LinkedinUrl { get; set; }
#endif
        /// <summary>The modality property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Modality { get; set; }
#nullable restore
#else
        public string Modality { get; set; }
#endif
        /// <summary>The name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>The organization_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public UntypedNode? OrganizationId { get; set; }
#nullable restore
#else
        public UntypedNode OrganizationId { get; set; }
#endif
        /// <summary>The original_source property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? OriginalSource { get; set; }
#nullable restore
#else
        public string OriginalSource { get; set; }
#endif
        /// <summary>The owner_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? OwnerId { get; set; }
#nullable restore
#else
        public string OwnerId { get; set; }
#endif
        /// <summary>The parent_account_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public UntypedNode? ParentAccountId { get; set; }
#nullable restore
#else
        public UntypedNode ParentAccountId { get; set; }
#endif
        /// <summary>The phone property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Phone { get; set; }
#nullable restore
#else
        public string Phone { get; set; }
#endif
        /// <summary>The phone_status property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PhoneStatus { get; set; }
#nullable restore
#else
        public string PhoneStatus { get; set; }
#endif
        /// <summary>The salesforce_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public UntypedNode? SalesforceId { get; set; }
#nullable restore
#else
        public UntypedNode SalesforceId { get; set; }
#endif
        /// <summary>The sanitized_phone property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SanitizedPhone { get; set; }
#nullable restore
#else
        public string SanitizedPhone { get; set; }
#endif
        /// <summary>The show_intent property</summary>
        public bool? ShowIntent { get; set; }
        /// <summary>The source property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Source { get; set; }
#nullable restore
#else
        public string Source { get; set; }
#endif
        /// <summary>The source_display_name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SourceDisplayName { get; set; }
#nullable restore
#else
        public string SourceDisplayName { get; set; }
#endif
        /// <summary>The team_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TeamId { get; set; }
#nullable restore
#else
        public string TeamId { get; set; }
#endif
        /// <summary>The typed_custom_fields property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Apollo.OpenApiClient.Models.UpdateAnAccount200ResponseAccountTypedCustomFields? TypedCustomFields { get; set; }
#nullable restore
#else
        public global::Soenneker.Apollo.OpenApiClient.Models.UpdateAnAccount200ResponseAccountTypedCustomFields TypedCustomFields { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Apollo.OpenApiClient.Models.UpdateAnAccount200ResponseAccount"/> and sets the default values.
        /// </summary>
        public UpdateAnAccount200ResponseAccount()
        {
            AdditionalData = new Dictionary<string, object>();
            HasIntentSignalAccount = true;
            ShowIntent = true;
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Apollo.OpenApiClient.Models.UpdateAnAccount200ResponseAccount"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Apollo.OpenApiClient.Models.UpdateAnAccount200ResponseAccount CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Apollo.OpenApiClient.Models.UpdateAnAccount200ResponseAccount();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "account_playbook_statuses", n => { AccountPlaybookStatuses = n.GetCollectionOfObjectValues<global::Soenneker.Apollo.OpenApiClient.Models.UpdateAnAccount200ResponseAccount_account_playbook_statuses>(global::Soenneker.Apollo.OpenApiClient.Models.UpdateAnAccount200ResponseAccount_account_playbook_statuses.CreateFromDiscriminatorValue)?.AsList(); } },
                { "account_rule_config_statuses", n => { AccountRuleConfigStatuses = n.GetCollectionOfObjectValues<global::Soenneker.Apollo.OpenApiClient.Models.UpdateAnAccount200ResponseAccount_account_rule_config_statuses>(global::Soenneker.Apollo.OpenApiClient.Models.UpdateAnAccount200ResponseAccount_account_rule_config_statuses.CreateFromDiscriminatorValue)?.AsList(); } },
                { "account_stage_id", n => { AccountStageId = n.GetStringValue(); } },
                { "created_at", n => { CreatedAt = n.GetStringValue(); } },
                { "creator_id", n => { CreatorId = n.GetObjectValue<UntypedNode>(UntypedNode.CreateFromDiscriminatorValue); } },
                { "crm_owner_id", n => { CrmOwnerId = n.GetObjectValue<UntypedNode>(UntypedNode.CreateFromDiscriminatorValue); } },
                { "crm_record_url", n => { CrmRecordUrl = n.GetObjectValue<UntypedNode>(UntypedNode.CreateFromDiscriminatorValue); } },
                { "custom_field_errors", n => { CustomFieldErrors = n.GetObjectValue<global::Soenneker.Apollo.OpenApiClient.Models.UpdateAnAccount200ResponseAccountCustomFieldErrors>(global::Soenneker.Apollo.OpenApiClient.Models.UpdateAnAccount200ResponseAccountCustomFieldErrors.CreateFromDiscriminatorValue); } },
                { "domain", n => { Domain = n.GetStringValue(); } },
                { "existence_level", n => { ExistenceLevel = n.GetStringValue(); } },
                { "has_intent_signal_account", n => { HasIntentSignalAccount = n.GetBoolValue(); } },
                { "hubspot_id", n => { HubspotId = n.GetObjectValue<UntypedNode>(UntypedNode.CreateFromDiscriminatorValue); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "intent_signal_account", n => { IntentSignalAccount = n.GetObjectValue<UntypedNode>(UntypedNode.CreateFromDiscriminatorValue); } },
                { "label_ids", n => { LabelIds = n.GetCollectionOfObjectValues<global::Soenneker.Apollo.OpenApiClient.Models.UpdateAnAccount200ResponseAccount_label_ids>(global::Soenneker.Apollo.OpenApiClient.Models.UpdateAnAccount200ResponseAccount_label_ids.CreateFromDiscriminatorValue)?.AsList(); } },
                { "linkedin_url", n => { LinkedinUrl = n.GetObjectValue<UntypedNode>(UntypedNode.CreateFromDiscriminatorValue); } },
                { "modality", n => { Modality = n.GetStringValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "organization_id", n => { OrganizationId = n.GetObjectValue<UntypedNode>(UntypedNode.CreateFromDiscriminatorValue); } },
                { "original_source", n => { OriginalSource = n.GetStringValue(); } },
                { "owner_id", n => { OwnerId = n.GetStringValue(); } },
                { "parent_account_id", n => { ParentAccountId = n.GetObjectValue<UntypedNode>(UntypedNode.CreateFromDiscriminatorValue); } },
                { "phone", n => { Phone = n.GetStringValue(); } },
                { "phone_status", n => { PhoneStatus = n.GetStringValue(); } },
                { "salesforce_id", n => { SalesforceId = n.GetObjectValue<UntypedNode>(UntypedNode.CreateFromDiscriminatorValue); } },
                { "sanitized_phone", n => { SanitizedPhone = n.GetStringValue(); } },
                { "show_intent", n => { ShowIntent = n.GetBoolValue(); } },
                { "source", n => { Source = n.GetStringValue(); } },
                { "source_display_name", n => { SourceDisplayName = n.GetStringValue(); } },
                { "team_id", n => { TeamId = n.GetStringValue(); } },
                { "typed_custom_fields", n => { TypedCustomFields = n.GetObjectValue<global::Soenneker.Apollo.OpenApiClient.Models.UpdateAnAccount200ResponseAccountTypedCustomFields>(global::Soenneker.Apollo.OpenApiClient.Models.UpdateAnAccount200ResponseAccountTypedCustomFields.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::Soenneker.Apollo.OpenApiClient.Models.UpdateAnAccount200ResponseAccount_account_playbook_statuses>("account_playbook_statuses", AccountPlaybookStatuses);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Apollo.OpenApiClient.Models.UpdateAnAccount200ResponseAccount_account_rule_config_statuses>("account_rule_config_statuses", AccountRuleConfigStatuses);
            writer.WriteStringValue("account_stage_id", AccountStageId);
            writer.WriteStringValue("created_at", CreatedAt);
            writer.WriteObjectValue<UntypedNode>("creator_id", CreatorId);
            writer.WriteObjectValue<UntypedNode>("crm_owner_id", CrmOwnerId);
            writer.WriteObjectValue<UntypedNode>("crm_record_url", CrmRecordUrl);
            writer.WriteObjectValue<global::Soenneker.Apollo.OpenApiClient.Models.UpdateAnAccount200ResponseAccountCustomFieldErrors>("custom_field_errors", CustomFieldErrors);
            writer.WriteStringValue("domain", Domain);
            writer.WriteStringValue("existence_level", ExistenceLevel);
            writer.WriteBoolValue("has_intent_signal_account", HasIntentSignalAccount);
            writer.WriteObjectValue<UntypedNode>("hubspot_id", HubspotId);
            writer.WriteStringValue("id", Id);
            writer.WriteObjectValue<UntypedNode>("intent_signal_account", IntentSignalAccount);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Apollo.OpenApiClient.Models.UpdateAnAccount200ResponseAccount_label_ids>("label_ids", LabelIds);
            writer.WriteObjectValue<UntypedNode>("linkedin_url", LinkedinUrl);
            writer.WriteStringValue("modality", Modality);
            writer.WriteStringValue("name", Name);
            writer.WriteObjectValue<UntypedNode>("organization_id", OrganizationId);
            writer.WriteStringValue("original_source", OriginalSource);
            writer.WriteStringValue("owner_id", OwnerId);
            writer.WriteObjectValue<UntypedNode>("parent_account_id", ParentAccountId);
            writer.WriteStringValue("phone", Phone);
            writer.WriteStringValue("phone_status", PhoneStatus);
            writer.WriteObjectValue<UntypedNode>("salesforce_id", SalesforceId);
            writer.WriteStringValue("sanitized_phone", SanitizedPhone);
            writer.WriteBoolValue("show_intent", ShowIntent);
            writer.WriteStringValue("source", Source);
            writer.WriteStringValue("source_display_name", SourceDisplayName);
            writer.WriteStringValue("team_id", TeamId);
            writer.WriteObjectValue<global::Soenneker.Apollo.OpenApiClient.Models.UpdateAnAccount200ResponseAccountTypedCustomFields>("typed_custom_fields", TypedCustomFields);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
