// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Apollo.OpenApiClient.Models
{
    /// <summary>
    /// Update who can access the sequence. This replaced the legacy `permissions` parameter. &lt;br&gt;&lt;br&gt;Changing `access_type` or any of the sharing access arrays requires a plan that includes sharing; `visibility` can be updated on any plan.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class UpdateSequenceRequestSharingPermission : IAdditionalDataHolder, IParsable
    {
        /// <summary>The level of access your team receives when `visibility` is `everyone`. Ignored when `visibility` is `restricted`. &lt;br&gt;&lt;br&gt;Choose 1 of the following options: &lt;ul&gt;&lt;li&gt;`can_view`: Team members can view the sequence.&lt;/li&gt;&lt;li&gt;`can_edit`: Team members can view and edit the sequence.&lt;/li&gt;&lt;li&gt;`full_access`: Team members can view, edit, and share the sequence.&lt;/li&gt;&lt;/ul&gt;</summary>
        public global::Soenneker.Apollo.OpenApiClient.Models.UpdateSequenceRequestSharingPermissionAccessType? AccessType { get; set; }
        /// <summary>Share the sequence with specific users or teams, in addition to whatever `visibility` grants. &lt;br&gt;&lt;br&gt;Note that the response returns the current shares as a single `sharing_accesses` array; to change them, use these `added_`, `updated_`, and `deleted_` arrays instead. &lt;br&gt;&lt;br&gt;If an entry sets `user_or_team_type` to `team`, its `access_type` also overrides the `access_type` you pass at the top level of `sharing_permission`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Apollo.OpenApiClient.Models.UpdateSequenceRequestSharingPermissionAddedSharingAccessesItem>? AddedSharingAccesses { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Apollo.OpenApiClient.Models.UpdateSequenceRequestSharingPermissionAddedSharingAccessesItem> AddedSharingAccesses { get; set; }
#endif
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Stop sharing the sequence with specific users or teams. Entries are matched on `user_or_team_id`; an entry for the sequence owner is ignored.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Apollo.OpenApiClient.Models.UpdateSequenceRequestSharingPermissionDeletedSharingAccessesItem>? DeletedSharingAccesses { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Apollo.OpenApiClient.Models.UpdateSequenceRequestSharingPermissionDeletedSharingAccessesItem> DeletedSharingAccesses { get; set; }
#endif
        /// <summary>Change the access level of users or teams the sequence is already shared with. Entries are matched on `user_or_team_id`; an entry for the sequence owner is ignored.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Apollo.OpenApiClient.Models.UpdateSequenceRequestSharingPermissionUpdatedSharingAccessesItem>? UpdatedSharingAccesses { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Apollo.OpenApiClient.Models.UpdateSequenceRequestSharingPermissionUpdatedSharingAccessesItem> UpdatedSharingAccesses { get; set; }
#endif
        /// <summary>Set to `everyone` to share the sequence with your whole team, or `restricted` to limit it to the owner and the users or teams listed in `sharing_accesses`. &lt;br&gt;&lt;br&gt;Changing `visibility` resets `access_type` to `can_view` when the new value is `everyone`, and to `null` when it is `restricted`.</summary>
        public global::Soenneker.Apollo.OpenApiClient.Models.UpdateSequenceRequestSharingPermissionVisibility? Visibility { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Apollo.OpenApiClient.Models.UpdateSequenceRequestSharingPermission"/> and sets the default values.
        /// </summary>
        public UpdateSequenceRequestSharingPermission()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Apollo.OpenApiClient.Models.UpdateSequenceRequestSharingPermission"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Apollo.OpenApiClient.Models.UpdateSequenceRequestSharingPermission CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Apollo.OpenApiClient.Models.UpdateSequenceRequestSharingPermission();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "access_type", n => { AccessType = n.GetEnumValue<global::Soenneker.Apollo.OpenApiClient.Models.UpdateSequenceRequestSharingPermissionAccessType>(); } },
                { "added_sharing_accesses", n => { AddedSharingAccesses = n.GetCollectionOfObjectValues<global::Soenneker.Apollo.OpenApiClient.Models.UpdateSequenceRequestSharingPermissionAddedSharingAccessesItem>(global::Soenneker.Apollo.OpenApiClient.Models.UpdateSequenceRequestSharingPermissionAddedSharingAccessesItem.CreateFromDiscriminatorValue)?.AsList(); } },
                { "deleted_sharing_accesses", n => { DeletedSharingAccesses = n.GetCollectionOfObjectValues<global::Soenneker.Apollo.OpenApiClient.Models.UpdateSequenceRequestSharingPermissionDeletedSharingAccessesItem>(global::Soenneker.Apollo.OpenApiClient.Models.UpdateSequenceRequestSharingPermissionDeletedSharingAccessesItem.CreateFromDiscriminatorValue)?.AsList(); } },
                { "updated_sharing_accesses", n => { UpdatedSharingAccesses = n.GetCollectionOfObjectValues<global::Soenneker.Apollo.OpenApiClient.Models.UpdateSequenceRequestSharingPermissionUpdatedSharingAccessesItem>(global::Soenneker.Apollo.OpenApiClient.Models.UpdateSequenceRequestSharingPermissionUpdatedSharingAccessesItem.CreateFromDiscriminatorValue)?.AsList(); } },
                { "visibility", n => { Visibility = n.GetEnumValue<global::Soenneker.Apollo.OpenApiClient.Models.UpdateSequenceRequestSharingPermissionVisibility>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteEnumValue<global::Soenneker.Apollo.OpenApiClient.Models.UpdateSequenceRequestSharingPermissionAccessType>("access_type", AccessType);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Apollo.OpenApiClient.Models.UpdateSequenceRequestSharingPermissionAddedSharingAccessesItem>("added_sharing_accesses", AddedSharingAccesses);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Apollo.OpenApiClient.Models.UpdateSequenceRequestSharingPermissionDeletedSharingAccessesItem>("deleted_sharing_accesses", DeletedSharingAccesses);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Apollo.OpenApiClient.Models.UpdateSequenceRequestSharingPermissionUpdatedSharingAccessesItem>("updated_sharing_accesses", UpdatedSharingAccesses);
            writer.WriteEnumValue<global::Soenneker.Apollo.OpenApiClient.Models.UpdateSequenceRequestSharingPermissionVisibility>("visibility", Visibility);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
