// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Apollo.OpenApiClient.Labels.Add_entity_ids_to_label_names;
using Soenneker.Apollo.OpenApiClient.Labels.Item;
using Soenneker.Apollo.OpenApiClient.Labels.Remove_entity_ids_from_label_names;
using Soenneker.Apollo.OpenApiClient.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Apollo.OpenApiClient.Labels
{
    /// <summary>
    /// Builds and executes requests for operations under \labels
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class LabelsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The add_entity_ids_to_label_names property</summary>
        public global::Soenneker.Apollo.OpenApiClient.Labels.Add_entity_ids_to_label_names.Add_entity_ids_to_label_namesRequestBuilder Add_entity_ids_to_label_names
        {
            get => new global::Soenneker.Apollo.OpenApiClient.Labels.Add_entity_ids_to_label_names.Add_entity_ids_to_label_namesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The remove_entity_ids_from_label_names property</summary>
        public global::Soenneker.Apollo.OpenApiClient.Labels.Remove_entity_ids_from_label_names.Remove_entity_ids_from_label_namesRequestBuilder Remove_entity_ids_from_label_names
        {
            get => new global::Soenneker.Apollo.OpenApiClient.Labels.Remove_entity_ids_from_label_names.Remove_entity_ids_from_label_namesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>Gets an item from the Soenneker.Apollo.OpenApiClient.labels.item collection</summary>
        /// <param name="position">The Apollo ID for the list you want to update.&lt;br&gt;&lt;br&gt;To find list IDs, call the &lt;a href=&quot;https://docs.apollo.io/reference/get-a-list-of-all-lists&quot;&gt;Get a List of All Lists endpoint&lt;/a&gt; and identify the `id` value.&lt;br&gt;&lt;br&gt;Example: `6612a4b7c8d9e0f123456789`</param>
        /// <returns>A <see cref="global::Soenneker.Apollo.OpenApiClient.Labels.Item.LabelsItemRequestBuilder"/></returns>
        public global::Soenneker.Apollo.OpenApiClient.Labels.Item.LabelsItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("id", position);
                return new global::Soenneker.Apollo.OpenApiClient.Labels.Item.LabelsItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Apollo.OpenApiClient.Labels.LabelsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public LabelsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/labels", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Apollo.OpenApiClient.Labels.LabelsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public LabelsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/labels", rawUrl)
        {
        }
        /// <summary>
        /// ## Endpoint essentials**API key access:** `api/v1/labels/index` or `Master API key`**OAuth scopes:** `tags_list`**Credit usage:** `0 credits` — [Learn more about API pricing and credits](https://docs.apollo.io/docs/api-pricing).Use the Get a List of All Lists endpoint to retrieve information about every &lt;a href=&quot;https://knowledge.apollo.io/hc/en-us/articles/4409728608525-Create-and-Use-a-List&quot; target=&quot;_blank&quot;&gt;list&lt;/a&gt; that has been created in your Apollo account. This endpoint can be used to check the available lists before you use the &lt;a href=&quot;https://docs.apollo.io/reference/create-a-contact&quot;&gt;Create a Contact endpoint&lt;/a&gt;. &lt;br&gt;&lt;br&gt;This endpoint doesn&apos;t require any parameters.
        /// </summary>
        /// <returns>A List&lt;global::Soenneker.Apollo.OpenApiClient.Models.GetAListOfAllLists200ResponseItem&gt;</returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Apollo.OpenApiClient.Labels.GetAListOfAllLists200Response401Error">When receiving a 401 status code</exception>
        /// <exception cref="global::Soenneker.Apollo.OpenApiClient.Models.GetAListOfAllLists403Response">When receiving a 403 status code</exception>
        /// <exception cref="global::Soenneker.Apollo.OpenApiClient.Models.GetAListOfAllLists429Response">When receiving a 429 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<List<global::Soenneker.Apollo.OpenApiClient.Models.GetAListOfAllLists200ResponseItem>?> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<List<global::Soenneker.Apollo.OpenApiClient.Models.GetAListOfAllLists200ResponseItem>> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "401", global::Soenneker.Apollo.OpenApiClient.Labels.GetAListOfAllLists200Response401Error.CreateFromDiscriminatorValue },
                { "403", global::Soenneker.Apollo.OpenApiClient.Models.GetAListOfAllLists403Response.CreateFromDiscriminatorValue },
                { "429", global::Soenneker.Apollo.OpenApiClient.Models.GetAListOfAllLists429Response.CreateFromDiscriminatorValue },
            };
            var collectionResult = await RequestAdapter.SendCollectionAsync<global::Soenneker.Apollo.OpenApiClient.Models.GetAListOfAllLists200ResponseItem>(requestInfo, global::Soenneker.Apollo.OpenApiClient.Models.GetAListOfAllLists200ResponseItem.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
            return collectionResult?.AsList();
        }
        /// <summary>
        /// ## Endpoint essentials**API key access:** `api/v1/labels/create` or `Master API key`**OAuth scopes:** `lists_create`**Credit usage:** `0 credits` — [Learn more about API pricing and credits](https://docs.apollo.io/docs/api-pricing).A &lt;a href=&quot;https://knowledge.apollo.io/hc/en-us/articles/4409728608525-Create-and-Use-a-List&quot; target=&quot;_blank&quot;&gt;list&lt;/a&gt; is a saved group of contacts or accounts in Apollo that you can organize, action, and track together.&lt;br&gt;&lt;br&gt;Use the Create a List endpoint to create a new, empty contact or account list in your team&apos;s Apollo account. After you create a list, add records to it with the &lt;a href=&quot;https://docs.apollo.io/reference/add-records-to-a-list&quot;&gt;Add Records to a List endpoint&lt;/a&gt;.&lt;br&gt;&lt;br&gt;List names must be unique for each modality within your team. If you try to create a list with a name that already exists for the same modality, Apollo returns a `422` response.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Apollo.OpenApiClient.Models.CreateAList200Response"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Apollo.OpenApiClient.Labels.CreateAList200Response401Error">When receiving a 401 status code</exception>
        /// <exception cref="global::Soenneker.Apollo.OpenApiClient.Models.CreateAList403Response">When receiving a 403 status code</exception>
        /// <exception cref="global::Soenneker.Apollo.OpenApiClient.Models.CreateAList422Response">When receiving a 422 status code</exception>
        /// <exception cref="global::Soenneker.Apollo.OpenApiClient.Models.CreateAList429Response">When receiving a 429 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Apollo.OpenApiClient.Models.CreateAList200Response?> PostAsync(global::Soenneker.Apollo.OpenApiClient.Models.CreateAListRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Apollo.OpenApiClient.Models.CreateAList200Response> PostAsync(global::Soenneker.Apollo.OpenApiClient.Models.CreateAListRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "401", global::Soenneker.Apollo.OpenApiClient.Labels.CreateAList200Response401Error.CreateFromDiscriminatorValue },
                { "403", global::Soenneker.Apollo.OpenApiClient.Models.CreateAList403Response.CreateFromDiscriminatorValue },
                { "422", global::Soenneker.Apollo.OpenApiClient.Models.CreateAList422Response.CreateFromDiscriminatorValue },
                { "429", global::Soenneker.Apollo.OpenApiClient.Models.CreateAList429Response.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.Apollo.OpenApiClient.Models.CreateAList200Response>(requestInfo, global::Soenneker.Apollo.OpenApiClient.Models.CreateAList200Response.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// ## Endpoint essentials**API key access:** `api/v1/labels/index` or `Master API key`**OAuth scopes:** `tags_list`**Credit usage:** `0 credits` — [Learn more about API pricing and credits](https://docs.apollo.io/docs/api-pricing).Use the Get a List of All Lists endpoint to retrieve information about every &lt;a href=&quot;https://knowledge.apollo.io/hc/en-us/articles/4409728608525-Create-and-Use-a-List&quot; target=&quot;_blank&quot;&gt;list&lt;/a&gt; that has been created in your Apollo account. This endpoint can be used to check the available lists before you use the &lt;a href=&quot;https://docs.apollo.io/reference/create-a-contact&quot;&gt;Create a Contact endpoint&lt;/a&gt;. &lt;br&gt;&lt;br&gt;This endpoint doesn&apos;t require any parameters.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// ## Endpoint essentials**API key access:** `api/v1/labels/create` or `Master API key`**OAuth scopes:** `lists_create`**Credit usage:** `0 credits` — [Learn more about API pricing and credits](https://docs.apollo.io/docs/api-pricing).A &lt;a href=&quot;https://knowledge.apollo.io/hc/en-us/articles/4409728608525-Create-and-Use-a-List&quot; target=&quot;_blank&quot;&gt;list&lt;/a&gt; is a saved group of contacts or accounts in Apollo that you can organize, action, and track together.&lt;br&gt;&lt;br&gt;Use the Create a List endpoint to create a new, empty contact or account list in your team&apos;s Apollo account. After you create a list, add records to it with the &lt;a href=&quot;https://docs.apollo.io/reference/add-records-to-a-list&quot;&gt;Add Records to a List endpoint&lt;/a&gt;.&lt;br&gt;&lt;br&gt;List names must be unique for each modality within your team. If you try to create a list with a name that already exists for the same modality, Apollo returns a `422` response.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(global::Soenneker.Apollo.OpenApiClient.Models.CreateAListRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(global::Soenneker.Apollo.OpenApiClient.Models.CreateAListRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Apollo.OpenApiClient.Labels.LabelsRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Apollo.OpenApiClient.Labels.LabelsRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Apollo.OpenApiClient.Labels.LabelsRequestBuilder(rawUrl, RequestAdapter);
        }
    }
}
#pragma warning restore CS0618
